-- fishcalc.lua -- PURE fishing math + fishdb queries (no Ashita, no imgui).
-- The brain of the fishing gear system (docs/design/fishing-gear.md): rod
-- verdicts port the server's own fail formulas VERBATIM (fishingutils.cpp
-- CalculateLoseChance :719 / CalculateSnapChance :784 / CalculateBreakChance
-- :828, CatsAndBoats/catseyexi@base, re-verified against source 2026-07-18),
-- and bait isolation derives live from the shipped pools/affinity tables.
-- Everything here is headless-testable; fishwatch/fishui provide the live
-- inputs (player skill, owned items) and render the answers.

local M = {};

-- ---------------------------------------------------------------------------
-- Database access. fishdb ships with the addon (data/fishdb.lua, generated by
-- tools/gen_fishdb.py). Fail soft: a missing db disables features, never errors.
-- Generator omits zero fields -- every reader below defaults with `or 0`.
-- ---------------------------------------------------------------------------
local _db = nil;
local _indexes = nil;   -- forward-declared: _setDb clears it (hard rule 8)
function M.db()
    if _db == nil then
        local ok, d = pcall(require, 'dlac\\data\\fishdb');
        _db = (ok and type(d) == 'table') and d or false;
    end
    return _db or nil;
end
function M._setDb(d) _db = d; _indexes = nil; end   -- test seam

-- ---------------------------------------------------------------------------
-- Server fail formulas. fish rec: { sk (the fish's skill level = maxSkill),
-- sz (0 small / 1 large), leg, rank (strength ranking) }. rod rec: { sz,
-- minR, maxR, brk, leg }. skill = the player's EFFECTIVE fishing skill
-- (display skill + worn Mod::FISH -- GetFishingSkill :1062).
-- ---------------------------------------------------------------------------
local function u8(v)   -- the server does this math in uint8; emulate the wrap
    v = math.floor(v) % 256;
    return v;
end

-- CalculateLoseChance :719-782. Returns chance, reason ('toobig'|'toosmall'|
-- 'lowskill'|nil). The three candidates compete: size failures win only when
-- they beat the low-skill chance (source :765-779). tooBig's over-skill rebate
-- is UNGUARDED uint8 math in the source -- past-zero it wraps high and clamps
-- back to 50 (tooSmall got the std::min guard :753; tooBig did not).
function M.loseChance(fish, rod, skill)
    local maxSkill = fish.sk or 0;
    local tooBig, tooSmall, lowSkill = 0, 0, 0;
    if (rod.leg or 0) == 0 then
        if (fish.sz or 0) > (rod.sz or 0) and (fish.rank or 0) > (rod.maxR or 0) then
            tooBig = u8(50 + (maxSkill - skill));
        elseif (fish.sz or 0) < (rod.sz or 0) and (fish.rank or 0) < (rod.minR or 0) then
            tooSmall = 50;
            if skill < maxSkill then tooSmall = tooSmall + (maxSkill - skill); end
            if skill > maxSkill then tooSmall = tooSmall - math.min(skill - maxSkill, tooSmall); end
        end
    end
    if skill + 7 < maxSkill then
        lowSkill = math.floor((maxSkill - (skill + 7)) * 0.8);
    end
    if tooBig > 0 and tooBig > lowSkill then
        return math.max(0, math.min(50, tooBig)), 'toobig';
    elseif tooSmall > 0 and tooSmall > lowSkill then
        return math.max(0, math.min(50, tooSmall)), 'toosmall';
    elseif lowSkill > 0 then
        return math.max(0, math.min(55, lowSkill)), 'lowskill';
    end
    return 0, nil;
end

-- CalculateSnapChance :784-826 (line snap).
function M.snapChance(fish, rod, skill)
    local maxSkill = fish.sk or 0;
    local levelDiffBonus = (skill + 10 > maxSkill) and 2 or 0;
    local sizePenalty, legendaryBonus = 0, 0;
    if (rod.leg or 0) == 0 and (fish.sz or 0) > (rod.sz or 0) then sizePenalty = 2; end
    if (fish.leg or 0) ~= 0 then
        if (rod.leg or 0) == 0 then sizePenalty = sizePenalty + 3;
        else legendaryBonus = 1; end
    end
    local durability = (rod.maxR or 0) + levelDiffBonus + legendaryBonus - sizePenalty;
    if (fish.rank or 0) > durability then
        return math.max(0, math.min(55, math.floor(((fish.rank or 0) - durability) * 8.5)));
    end
    return 0;
end

-- CalculateBreakChance :828-869 (rod break). Unbreakable rods (Ebisu, Judge's,
-- Goldfish Basket) return 0 forever. NOTE the source quirks ported faithfully:
-- legendaryBonus needs a LARGE fish (not a legendary one) on a legendary rod,
-- and a legendary fish on a normal rod REPLACES the size penalty with 5.
function M.breakChance(fish, rod, skill)
    if (rod.brk or 0) == 0 then return 0; end
    local maxSkill = fish.sk or 0;
    local levelDiffBonus = (skill + 10 > maxSkill) and 2 or 0;
    local sizePenalty, legendaryBonus = 0, 0;
    if (rod.leg or 0) == 0 and (fish.sz or 0) > (rod.sz or 0) then sizePenalty = 2;
    elseif (rod.leg or 0) ~= 0 and (fish.sz or 0) == 1 then legendaryBonus = 1; end
    if (rod.leg or 0) == 0 and (fish.leg or 0) ~= 0 then sizePenalty = 5; end
    local durability = (rod.maxR or 0) + levelDiffBonus + legendaryBonus;
    if (fish.rank or 0) > durability then
        return math.max(0, math.min(55, math.floor(((fish.rank or 0) - durability + sizePenalty) * 1.3)));
    end
    return 0;
end

-- The full verdict for one fish + rod + effective skill.
function M.verdictFor(fish, rod, skill)
    local lose, why = M.loseChance(fish, rod, skill);
    local snap = M.snapChance(fish, rod, skill);
    local brk = M.breakChance(fish, rod, skill);
    return { lose = lose, loseWhy = why, snap = snap, brk = brk,
             ok = (lose == 0 and snap == 0 and brk == 0) };
end

-- The legendary rods outrank everything at equal risk (Henrik's ruling
-- 2026-07-18: "Lu Shang's always beats base rods, Ebisu always beats Lu
-- Shang's"). The tier sits BELOW the risk sort on purpose: a fish that
-- would snap Lu Shang's still gets the safe base rod recommended.
local LEG_RANK = {
    [19321] = 4,   -- Ebisu Rod +1 (unobtainable here, but if ever owned...)
    [17011] = 3,   -- Ebisu Fishing Rod
    [19320] = 2,   -- Lu Shang's Fishing Rod +1
    [17386] = 1,   -- Lu Shang's Fishing Rod
};
function M.legRank(id) return LEG_RANK[id] or 0; end

-- Rank every rod in the db for a target fish. ownedSet is { [rodItemId]=true }
-- (or nil = rank all). Sort: clean verdicts first, then least total risk, then
-- the legendary-rod tier (Ebisu > Lu Shang's > the field), then
-- legendary-matches-legendary, then mini-game muscle (attack incl. legendary
-- bonus when both sides are legendary, then hook time), then the server's own
-- rating column, then name -- deterministic, no magic scalars.
function M.rodsFor(fish, skill, ownedSet)
    local db = M.db(); if db == nil then return {}; end
    local out = {};
    for id, rod in pairs(db.rods) do
        local v = M.verdictFor(fish, rod, skill);
        out[#out + 1] = {
            id = id, rod = rod, v = v,
            owned = (ownedSet ~= nil and ownedSet[id] == true) or false,
            risk = v.lose + v.snap + v.brk,
            atk = (rod.atk or 0) + (((fish.leg or 0) ~= 0 and (rod.leg or 0) ~= 0) and (rod.lgdAtk or 0) or 0),
        };
    end
    table.sort(out, function(a, b)
        if a.v.ok ~= b.v.ok then return a.v.ok; end
        if a.risk ~= b.risk then return a.risk < b.risk; end
        local aRank, bRank = LEG_RANK[a.id] or 0, LEG_RANK[b.id] or 0;
        if aRank ~= bRank then return aRank > bRank; end
        local aLeg = ((fish.leg or 0) ~= 0 and (a.rod.leg or 0) ~= 0) and 1 or 0;
        local bLeg = ((fish.leg or 0) ~= 0 and (b.rod.leg or 0) ~= 0) and 1 or 0;
        if aLeg ~= bLeg then return aLeg > bLeg; end
        if a.atk ~= b.atk then return a.atk > b.atk; end
        if (a.rod.tim or 0) ~= (b.rod.tim or 0) then return (a.rod.tim or 0) > (b.rod.tim or 0); end
        if (a.rod.rating or 0) ~= (b.rod.rating or 0) then return (a.rod.rating or 0) > (b.rod.rating or 0); end
        return (a.rod.n or '') < (b.rod.n or '');
    end);
    return out;
end

-- Best OWNED rod for a fish (first owned entry of the ranking), or nil.
function M.bestOwnedRod(fish, skill, ownedSet)
    for _, r in ipairs(M.rodsFor(fish, skill, ownedSet)) do
        if r.owned then return r; end
    end
    return nil;
end

-- ---------------------------------------------------------------------------
-- Lazy reverse indexes over the shipped tables.
-- ---------------------------------------------------------------------------
local function indexes()
    local db = M.db(); if db == nil then return nil; end
    if _indexes ~= nil then return _indexes; end
    local fishBaits = {};   -- fishid -> { {b=baitid, p=power}... }
    for b, m in pairs(db.aff or {}) do
        for f, p in pairs(m) do
            fishBaits[f] = fishBaits[f] or {};
            local t = fishBaits[f];
            t[#t + 1] = { b = b, p = p };
        end
    end
    local fishSpots = {};   -- fishid -> { {z=zone, a=area}... }
    for z, ars in pairs(db.pools or {}) do
        for a, list in pairs(ars) do
            for _, f in ipairs(list) do
                fishSpots[f] = fishSpots[f] or {};
                local t = fishSpots[f];
                t[#t + 1] = { z = z, a = a };
            end
        end
    end
    _indexes = { fishBaits = fishBaits, fishSpots = fishSpots };
    return _indexes;
end

-- Baits that can hook this fish, best power first.
function M.baitsFor(fishid)
    local db = M.db(); local ix = indexes();
    if db == nil or ix == nil then return {}; end
    local out = {};
    for _, e in ipairs(ix.fishBaits[fishid] or {}) do
        local rec = db.baits[e.b];
        out[#out + 1] = { id = e.b, power = e.p, bait = rec };
    end
    table.sort(out, function(a, b)
        if a.power ~= b.power then return a.power > b.power; end
        return ((a.bait and a.bait.n) or '') < ((b.bait and b.bait.n) or '');
    end);
    return out;
end

-- Everything a bait can hook (reverse lookup), optionally limited to a zone.
function M.fishForBait(baitid, zoneid)
    local db = M.db(); if db == nil then return {}; end
    local m = (db.aff or {})[baitid];
    if m == nil then return {}; end
    local inZone = nil;
    if zoneid ~= nil and db.pools[zoneid] ~= nil then
        inZone = {};
        for _, list in pairs(db.pools[zoneid]) do
            for _, f in ipairs(list) do inZone[f] = true; end
        end
    end
    local out = {};
    for f, p in pairs(m) do
        if db.fish[f] ~= nil and (inZone == nil or inZone[f]) then
            out[#out + 1] = { id = f, power = p, fish = db.fish[f] };
        end
    end
    table.sort(out, function(a, b)
        if a.power ~= b.power then return a.power > b.power; end
        return (a.fish.n or '') < (b.fish.n or '');
    end);
    return out;
end

-- Mob-bite risk for a bait in a zone area: fishing_mob rows hook when their
-- required bait (b) is 0 (any) or matches, same for the alternative (ab);
-- area 0 = the whole zone.
function M.mobRisk(zoneid, areaid, baitid)
    local db = M.db(); if db == nil then return nil; end
    for _, mob in ipairs((db.mobs or {})[zoneid] or {}) do
        local areaOk = (mob.a or 0) == 0 or mob.a == areaid;
        local baitOk = (mob.b or 0) == 0 or mob.b == baitid or (mob.ab or 0) == baitid;
        if areaOk and baitOk then return mob; end
    end
    return nil;
end

-- The flagship: every (zone, area, bait) row for a target fish, ISOLATED rows
-- first ("only this fish shares the pool with that bait"), then by fewest
-- competitors. Competitors = other pool members the bait has affinity for.
-- Conservative by design: KI-gated or quest-gated competitors still count (a
-- player missing the KI sees BETTER isolation than promised, never worse).
-- Items/monsters ride separate pools -- callers must show mobRisk + the
-- "items can always bite" footnote rather than promising exclusivity.
function M.isolationFor(fishid)
    local db = M.db(); local ix = indexes();
    if db == nil or ix == nil then return {}; end
    local rows = {};
    for _, spot in ipairs(ix.fishSpots[fishid] or {}) do
        local pool = (db.pools[spot.z] or {})[spot.a] or {};
        for _, e in ipairs(ix.fishBaits[fishid] or {}) do
            local others = {};
            for _, f in ipairs(pool) do
                if f ~= fishid and (db.aff[e.b] or {})[f] ~= nil then
                    others[#others + 1] = f;
                end
            end
            rows[#rows + 1] = {
                z = spot.z, a = spot.a, bait = e.b, power = e.p,
                zoneName = (db.zones[spot.z] or {}).n or ('Zone ' .. spot.z),
                areaName = ((db.areaNames or {})[spot.z] or {})[spot.a],
                baitName = (db.baits[e.b] or {}).n or ('Bait ' .. e.b),
                others = others, clean = (#others == 0),
                mob = M.mobRisk(spot.z, spot.a, e.b),
            };
        end
    end
    table.sort(rows, function(a, b)
        if a.clean ~= b.clean then return a.clean; end
        if #a.others ~= #b.others then return #a.others < #b.others; end
        if a.power ~= b.power then return a.power > b.power; end
        if a.zoneName ~= b.zoneName then return a.zoneName < b.zoneName; end
        return a.bait < b.bait;
    end);
    return rows;
end

-- ---------------------------------------------------------------------------
-- Search + display helpers.
-- ---------------------------------------------------------------------------
function M.searchFish(q)
    local db = M.db(); if db == nil then return {}; end
    q = tostring(q or ''):lower();
    local out = {};
    for id, f in pairs(db.fish) do
        local n = (f.n or ''):lower();
        if q == '' or n:find(q, 1, true) ~= nil then
            out[#out + 1] = { id = id, fish = f,
                              pfx = (n:sub(1, #q) == q) and 0 or 1 };
        end
    end
    table.sort(out, function(a, b)
        if a.pfx ~= b.pfx then return a.pfx < b.pfx; end
        return (a.fish.n or '') < (b.fish.n or '');
    end);
    return out;
end

-- Bite-window hints from the fish's hour pattern (fishingutils.h HOURPATTERN;
-- specials per GetHourlyModifier: 2 = all but dawn/dusk, 3 = ONLY 5:00/17:00,
-- 4 = night). Cosine-curve patterns get an honest 'varies'.
local HOUR_HINT = {
    [2] = 'any hour except dawn/dusk (5:00/17:00)',
    [3] = 'dawn/dusk ONLY (5:00 and 17:00)',
    [4] = 'night (20:00-3:00)',
};
function M.hourHint(hp)
    if hp == nil or hp == 0 then return 'any hour'; end
    return HOUR_HINT[hp] or 'varies by hour';
end
function M.moonHint(mp)
    if mp == nil or mp == 0 then return nil; end
    return 'moon-sensitive';
end

-- Ladder score for the manifest fish block: Mod::FISH (catalog
-- Stats.FishingSkill -- adds to effective skill directly) dominates; the
-- CatsEyeXI cx-mods -- identified 2026-07-18 as Expert Angler: cx4 = Fatigue
-- Limit +%, cx5 = Golden Arrow Rate +% (bg-wiki CatsEyeXI Ventures page) --
-- are quality-of-life, so they stay tiebreakers below real skill.
function M.gearScore(fishStat, bonus)
    local s = (tonumber(fishStat) or 0) * 1000;
    if type(bonus) == 'table' then
        s = s + (bonus.cx4 or 0) * 2 + (bonus.cx5 or 0);
    end
    return s;
end
function M.bonusFor(itemId)
    local db = M.db(); if db == nil then return nil; end
    return (db.gearBonus or {})[itemId];
end

-- Worn-at-once Fish+ total from a bag-counts table: per slot the best owned
-- Mod::FISH piece (rings twice when two are owned -- two fingers). Rod/bait
-- slots excluded -- they're the pick, not the bonus. Shared by fishui's
-- status label and fishbar's verdict tags (one effective-skill convention).
function M.wornFishTotal(counts)
    local db = M.db();
    if db == nil or type(counts) ~= 'table' then return 0; end
    local bySlot = {};
    for id, g in pairs(db.gearBonus or {}) do
        local f = tonumber(g.fish) or 0;
        if f > 0 and (counts[id] or 0) >= 1 and g.sl ~= 'Range' and g.sl ~= 'Ammo' then
            local cur = bySlot[g.sl];
            local pair = (g.sl == 'Ring' and (counts[id] or 0) >= 2) and f * 2 or f;
            if cur == nil or pair > cur then bySlot[g.sl] = pair; end
        end
    end
    local sum = 0;
    for _, v in pairs(bySlot) do sum = sum + v; end
    return sum;
end

return M;
