--[[
    dlac/servers/ascensionxi/manifest.lua -- the AscensionXI server pack (dlac ADR 0035).
    GENERATED by the ascensionxi repo's tools/dlac-pack/gen_pack.py -- do not hand-edit;
    re-run the generator after a server data change and commit the pack to dlac.
]]--
return {
    fmt  = 1,
    id   = 'ascensionxi',
    name = 'AscensionXI',

    maxLevel = 75,

    -- AscensionXI is stock-LSB-lineage: no game modes, no prestige, no 0x1A4
    -- protocol family, no venture economy -- those capabilities simply do
    -- not exist here, so the CEXI modules never mount and their gates stay
    -- shut by construction.
    caps = {
        wearMainJobOnly = true,   -- LSB equip eligibility: sub never widens
    },

    const = {
        augFormat          = 'lsb',   -- stock LSB augment extdata (not CEXI's private format)
        catalogMin         = 10267,
        mpPlayerMultiplier = 1,
        mpSjDivisor        = 2,
    },

    -- gearvault: the Gear Vault integration (0x1E0 ops 0x40-0x7F --
    -- docs/design/gear-vault-integration.md)
    modules = { 'gearvault' },

    files = {
        'catalog', 'spells', 'abilities', 'zones',
        'gearsets', 'latentstats', 'levelscaling',
    },

    counts = {
        catalog      = 15401,
        spells       = 537,
        abilities    = 485,
        zones        = 300,
        gearsets     = 126,
        latentstats  = 856,
        levelscaling = 8,
    },
};
