--[[
    dlac/servers/ascensionxi/modules.lua -- the pack's MODULE list, hand-
    maintained (ADR 0035). Outranks manifest.modules in gear/serverpack.lua.

    Which client modules exist is a CODE fact owned by this repo, not a data
    fact for a generator to emit: manifest.lua is GENERATED by the ascensionxi
    repo's tools/dlac-pack/gen_pack.py, and a 2026-08-27 regeneration emitted
    modules = {} -- which silently unloaded the entire Gear Vault (no tab, no
    mirror, no /dl vault, no error; a fresh install shipped dark,
    docs/design/ascensionxi-server-handover-2026-08-27.md par.4a). This file is
    written only by hand, so a regeneration can never drop client code again.
]]--
return { 'gearvault' };
