--[[
    dlac/servers/ascensionxi/modules.lua -- the pack's MODULE list, hand-
    maintained (ADR 0035). Outranks manifest.modules in gear/serverpack.lua.

    Which client modules exist is a CODE fact owned by this repo, not a data
    fact for a generator to emit: manifest.lua is GENERATED by the ascensionxi
    repo's tools/dlac-pack/gen_pack.py, and a 2026-08-27 regeneration emitted
    modules = {} -- which silently unloaded the entire Gear Vault (no tab, no
    mirror, no /dl vault, no error; a fresh install shipped dark,
    docs/design/ascensionxi-server-handover-2026-08-27.md par.4a). This file is
    written only by hand, so a regeneration can never drop client code again.

    Void Restock (`voidrestock`) left this list on 2026-09-27: the Nexus addon
    in the AscensionXI repo owns restocking now (docs/design/void-restock.md).
    `telemetry` (2026-10-05) is the combat telemetry client and AutoAcc v1
    (docs/design/ascensionxi-combat-telemetry-autoacc.md).
]]--
return { 'gearvault', 'helm', 'digging', 'ascension', 'restocknotice', 'telemetry' };
