--[[
accwatch.lua -- prints a mob's EVA and the ACC you need to cap hit rate on it,
once, at the moment you engage. OFF by default:
    /dl acc        toggle on/off
    /dl acc now    report your CURRENT target on demand (no engage needed)
    /dl acc debug  trace engage/inject/reply/cache decisions to chat

Data: accdata.lua, GENERATED by tools/acc_calc.py --luadata from the public
CatsEyeXI server source (catalog model: ships with the addon, never fetched).
Entries are exact at the spawn range's endpoints (zone-aware sub-job rule).

Exact levels, two ways (Henrik 07-14: checker's levels come from the /check
reply itself, widescan only backfills NMs):
 - AUTO-CHECK: every engage fires the same c2s 0x0DD request the Check menu
   sends (pure read; mobs notify nobody -- only checked PLAYERS see "checks
   you", and engage targets are mobs). The acc line waits ~0.8s for the
   reply, which is cached and swallowed (e.blocked) so chat stays clean --
   the level arrives without the user noticing. Manual /check outside that
   window still prints normally. Injection precedent: craftwatch 0x10F.
 - PASSIVE: any /check reply (0x029 p1) or widescan reply (0x0F4) caches
   idx -> level for the zone regardless (wiped on zone-in).
A live level collapses the range to one exact number, marked *. NMs answer
"impossible to gauge" (no level) -> widescan stays their only level source.

Caps (physical_hit_rate.lua): 99% for 1H mainhand / H2H -> ACC = EVA + 48;
95% for 2H -> ACC = EVA + 40. The mainhand is sniffed from the equipped
weapon's skill type so the right cap is chosen automatically.

Level correction (accdata.corrected zones): a PC fighting a mob ABOVE their
level gets +4 ACC per level of difference. That is what the shipped server
code does, and it is CANON here (Henrik ruling 2026-07-14) -- the code's
"Accuracy Penalty" comment is stale, not a bug awaiting a fix. The printed
ACC target folds the correction in. If tools/acc_calc.py ever warns that the
upstream sign flipped, revisit report() below.
]]

local M = {};
M.enabled = false;
M.debug = false;    -- /dl acc debug: trace engage/inject/reply/cache decisions

local _cfok, _cfmt = pcall(require, 'dlac\\chatfmt');
_cfok = _cfok and type(_cfmt) == 'table';
local function say(s) if _cfok and _cfmt.msg then _cfmt.msg(s); else print('[dlac] ' .. s); end end
local function dbg(s) if M.debug then say('acc dbg: ' .. s); end end

local _dok, DATA = pcall(require, 'dlac\\accdata');
_dok = _dok and type(DATA) == 'table' and type(DATA.zones) == 'table';

-- entity name -> accdata key: lowercase alphanumerics only (mirror of the
-- generator's squash(); survives apostrophes/underscores/spacing differences)
local function squash(name)
    return (tostring(name or ''):lower():gsub('[^%a%d]+', ''));
end

-- item resource .Skill of the equipped mainhand: 2H = gsword 4, gaxe 6,
-- scythe 7, polearm 8, gkatana 10, staff 12. H2H (1) caps like 1H.
local TWOHAND = { [4] = true, [6] = true, [7] = true, [8] = true, [10] = true, [12] = true };

local function mainhandIs2H()
    local is2h = false;
    pcall(function()
        local inv = AshitaCore:GetMemoryManager():GetInventory();
        local eitem = inv:GetEquippedItem(0);                     -- slot 0 = Main
        if eitem == nil or eitem.Index == 0 then return; end
        local cont = math.floor(eitem.Index / 256) % 256;         -- packed: high byte = container
        local slot = eitem.Index % 256;                           -- (augments.lua:231)
        local item = inv:GetContainerItem(cont, slot);
        if item == nil or item.Id == 0 then return; end
        local res = AshitaCore:GetResourceManager():GetItemById(item.Id);
        if res ~= nil and TWOHAND[res.Skill] == true then is2h = true; end
    end);
    return is2h;
end

local function band(a, b)
    local lo, hi = math.min(a, b), math.max(a, b);
    if lo == hi then return tostring(lo); end
    return ('%d-%d'):format(lo, hi);
end

-- EVA at an exact level: linear interpolation between the accdata endpoints
-- (EVA is ~linear inside a spawn range; good to +-1 for the usual short spans)
local function evaAt(e, lvl)
    if e[2] <= e[1] then return e[3]; end
    return math.floor(e[3] + (e[4] - e[3]) * (lvl - e[1]) / (e[2] - e[1]) + 0.5);
end

-- passive exact-level cache, checker-style: /check replies (non-NM) and any
-- widescan replies that happen to arrive. actIndex -> level, wiped on zone-in.
local seenLevels = {};
local CHECK_MSG = { [0xAA] = 1, [0xAB] = 1, [0xAC] = 1, [0xAD] = 1, [0xAE] = 1,
                    [0xAF] = 1, [0xB0] = 1, [0xB1] = 1, [0xB2] = 1 };

local function report(actIndex, why)
    if not _dok then
        say('acc: accdata.lua missing/bad -- regenerate: python tools\\acc_calc.py --luadata accdata.lua');
        return;
    end
    local name = '';
    pcall(function() name = AshitaCore:GetMemoryManager():GetEntity():GetName(actIndex) or ''; end);
    if name == '' then return; end
    local zone = -1;
    pcall(function() zone = AshitaCore:GetMemoryManager():GetParty():GetMemberZone(0); end);
    local z = DATA.zones[zone];
    local e = z ~= nil and z[squash(name)] or nil;
    if e == nil then
        local seen = seenLevels[actIndex];
        say(('acc%s: %s%s -- not in the static table for this zone (custom mob? the widescan layer will learn these)'):format(
            why or '', name, seen ~= nil and (' Lv%d*'):format(seen) or ''));
        return;
    end
    local lo, hi, evLo, evHi, nm, desc = e[1], e[2], e[3], e[4], e[5], e[6];
    local exact = '';
    local seen = seenLevels[actIndex];
    if seen ~= nil and seen >= lo and seen <= hi then             -- live level known: collapse
        lo, hi = seen, seen;                                      -- the range to one number
        evLo = evaAt(e, seen);
        evHi = evLo;
        exact = '*';                                              -- * = level observed live
    end
    local is2h = mainhandIs2H();
    local add = is2h and 40 or 48;                                -- to 95% / 99%
    local needLo, needHi = evLo + add, evHi + add;
    local corr = '';
    if DATA.corrected ~= nil and DATA.corrected[zone] == true then
        local pl = 0;
        pcall(function() pl = AshitaCore:GetMemoryManager():GetPlayer():GetMainJobLevel() or 0; end);
        if pl > 0 and pl < hi then
            needLo = needLo - math.max(0, lo - pl) * 4;           -- +4 ACC per level the mob is
            needHi = needHi - math.max(0, hi - pl) * 4;           -- above you (see header: canon)
            corr = (' [lvl-corr, you Lv%d]'):format(pl);
        end
    end
    say(('acc%s: %s Lv%s%s (%s%s)  EVA %s  ->  ACC %s to cap (%s %d%%)%s'):format(
        why or '', name, band(lo, hi), exact, desc, nm == 1 and ', NM' or '',
        band(evLo, evHi), band(needLo, needHi), is2h and '2H' or '1H/H2H', is2h and 95 or 99, corr));
end

-- ---------------------------------------------------------------------------
-- Ashita glue (guarded so the module stays headless-loadable, craftwatch:581)
-- ---------------------------------------------------------------------------
local lastTarget = nil;   -- debounce: same-mob re-engage inside 5s stays quiet
local lastAt = 0;
local pending = nil;      -- { idx, at }: engage waiting for its auto-check reply
local muteIdx = -1;       -- swallow check replies for this idx until muteUntil
local muteUntil = 0;      -- (only replies OUR auto-check caused; manual /check prints)

if ashita ~= nil and ashita.events ~= nil and type(ashita.events.register) == 'function' then
    -- level learning: /check reply 0x029 (p1 = exact level, non-NM only --
    -- gated on the check message/type ids so other battle messages can't
    -- pollute the cache) and widescan reply 0x0F4 (levels for everything,
    -- NMs included). Auto-check replies are blocked here and the deferred
    -- engage report fires the moment they land.
    ashita.events.register('packet_in', 'dlac-accwatch-in', function(e)
        if e.id == 0x00A then seenLevels = {}; pending = nil; return; end   -- indexes recycle
        if e.id ~= 0x029 and e.id ~= 0x0F4 then return; end
        pcall(function()
            local d = e.data;
            if e.id == 0x0F4 then
                local idx = d:byte(0x04 + 1) + d:byte(0x05 + 1) * 256;
                local lvl = d:byte(0x06 + 1);
                if idx > 0 and lvl > 0 then
                    seenLevels[idx] = lvl;
                    dbg(('widescan cache idx=0x%03X Lv%d'):format(idx, lvl));
                end
                return;
            end
            if #d < 0x1A then return; end
            local p1  = d:byte(0x0C + 1) + d:byte(0x0D + 1) * 256;
            local hi  = d:byte(0x0E + 1) + d:byte(0x0F + 1) * 256;
            local p2  = d:byte(0x10 + 1);
            local tgt = d:byte(0x16 + 1) + d:byte(0x17 + 1) * 256;
            local msg = d:byte(0x18 + 1) + d:byte(0x19 + 1) * 256;
            local isCheck = (CHECK_MSG[msg] ~= nil and p2 >= 0x40 and p2 <= 0x47)
                         or msg == 0xF9;                          -- 0xF9 = impossible to gauge (NM)
            if not isCheck then
                if pending ~= nil and pending.idx == tgt then     -- reply-shaped miss: show why
                    dbg(('0x029 for pending idx=0x%03X NOT check-shaped: msg=0x%02X p2=0x%02X p1=%d'):format(
                        tgt, msg, p2, p1));
                end
                return;
            end
            dbg(('check reply tgt=0x%03X msg=0x%02X p2=0x%02X p1=%d%s%s'):format(
                tgt, msg, p2, p1,
                (tgt == muteIdx and os.clock() < muteUntil) and ' [mute]' or '',
                (pending ~= nil and pending.idx == tgt) and ' [pending hit]' or ''));
            if CHECK_MSG[msg] ~= nil and hi == 0 and p1 > 0 and p1 < 200 then
                seenLevels[tgt] = p1;
            end
            if tgt == muteIdx and os.clock() < muteUntil then
                e.blocked = true;                                 -- our auto-check: keep chat clean
            end
            if pending ~= nil and pending.idx == tgt then
                local idx = pending.idx;
                pending = nil;
                report(idx, nil);
            end
        end);
    end);

    ashita.events.register('packet_out', 'dlac-accwatch-out', function(e)
        if not M.enabled or e.id ~= 0x01A then return; end
        pcall(function()
            local d = e.data;
            local action = d:byte(0x0A + 1) + d:byte(0x0B + 1) * 256;
            if action ~= 0x02 then return; end                    -- 0x02 = engage
            local idx = d:byte(0x08 + 1) + d:byte(0x09 + 1) * 256;
            local sid = d:byte(0x04 + 1) + d:byte(0x05 + 1) * 256
                      + d:byte(0x06 + 1) * 65536 + d:byte(0x07 + 1) * 16777216;
            if sid == lastTarget and os.clock() - lastAt < 5 then return; end
            lastTarget = sid;
            lastAt = os.clock();
            -- auto-check: the request the Check menu sends. Layout from the
            -- SERVER's 0x0dd_equip_inspect.h (NOT the XiPackets u16 guess!):
            -- 16 bytes -- UniqueNo u32 @0x04, ActIndex u32 @0x08, Kind u8
            -- @0x0C (0 = Check, enum-validated) + 3 pad. A 12-byte packet is
            -- dropped by the validator without a reply (the v1 bug).
            dbg(('engage idx=0x%03X sid=%d -> auto-check'):format(idx, sid));
            pending = { idx = idx, at = os.clock() };
            muteIdx = idx;
            muteUntil = os.clock() + 1.0;
            local ok, err = pcall(function()
                AshitaCore:GetPacketManager():AddOutgoingPacket(0x0DD, {
                    0xDD, 0x08, 0x00, 0x00,
                    d:byte(0x04 + 1), d:byte(0x05 + 1), d:byte(0x06 + 1), d:byte(0x07 + 1),
                    d:byte(0x08 + 1), d:byte(0x09 + 1), 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00 });
            end);
            if not ok then                                        -- can't inject: report now
                say('auto-check inject FAILED (' .. tostring(err) .. ') -- reporting from cache');
                pending = nil;
                report(idx, nil);
            end
        end);
    end);

    -- fallback: the check reply never came (lag, dynamic entity, filtered) --
    -- print the report from whatever is cached rather than staying silent.
    ashita.events.register('d3d_present', 'dlac-accwatch-tick', function()
        if pending == nil then return; end
        if os.clock() - pending.at > 0.8 then
            local idx = pending.idx;
            pending = nil;
            muteIdx = -1;   -- no reply came; don't eat a later manual /check
            dbg(('auto-check TIMED OUT for idx=0x%03X -- server dropped the request or reply unmatched'):format(idx));
            pcall(report, idx, nil);
        end
    end);

    -- /dl acc [now] -- toggle the engage watch, or report the current target.
    ashita.events.register('command', 'dlac-accwatch-cmd', function(e)
        pcall(function()
            local raw = string.lower(e.command or '');
            local a, b = raw:match('^/dl%s+(%S+)%s*(%S*)');
            if a == nil then a, b = raw:match('^/dlac%s+(%S+)%s*(%S*)'); end
            if a ~= 'acc' then return; end
            e.blocked = true;
            if b == 'now' then
                local idx = 0;
                pcall(function() idx = AshitaCore:GetMemoryManager():GetTarget():GetTargetIndex(0); end);
                if idx == nil or idx == 0 then say('acc: no target.'); return; end
                report(idx, '(target)');
                return;
            end
            if b == 'debug' then
                M.debug = not M.debug;
                say('acc debug ' .. (M.debug and 'ON -- traces engage/inject/reply/cache' or 'OFF') .. '.');
                return;
            end
            M.enabled = not M.enabled;
            say('acc-on-engage ' .. (M.enabled and 'ON -- engage something (or /dl acc now on a target).' or 'OFF.'));
        end);
    end);
end

return M;
