--[[
accwatch.lua -- tells you where your ACC stands against the mob you fight,
at engage AND on every battle-target switch (auto-target). OFF by default:
    /dl acc        toggle. Each fight prints one line (Henrik's format):
                   <Mob> Lv<L> - MobEVA <E> - CurrentAcc: <A> - AccCmp: <E-A>
                   - AccCmpLvl: <(youLv-mobLv)*4> - AccPct: <expected hit%>
                   - AccCap: <ACC still needed to cap; negative = over cap>
                   (range mobs use the worst-case end; live level = exact *)
    /dl acc now    same labeled line for the CURRENT target (no engage needed;
                   falls back to the prose detail line when your ACC is not
                   known yet -- engage once or /checkparam to prime it)
    /dl acc family <name>  assign a mob FAMILY to the current target (saved
                   per char in accfamilies.lua; bare = show, clear = remove).
                   CUSTOM MOBS (dynamic spawns, idx 0x800+; the Wajaom
                   Toucans) exist in NO zone's static table -- but accdata
                   ships an EVA-by-level curve per family, so family + the
                   LIVE level (auto-/check on engage, widescan) prices them
                   anyway. A name that exists in ANY zone (Toucan -> Bird in
                   Bibiki Bay) resolves its family automatically; the manual
                   assignment is for names the table has never seen. The
                   curve is a floor; the /check bracket corrects it live.
    /dl acc debug  trace engage/inject/reply/cache decisions to chat

Triggers: c2s 0x01A action 0x02 (attack) and action 0x0F (change target --
what the client sends when auto-target swaps you to the next mob while you
stay engaged).

Data: accdata.lua, GENERATED by tools/acc_calc.py --luadata from the public
CatsEyeXI server source (catalog model: ships with the addon, never fetched).
Entries are exact at the spawn range's endpoints (zone-aware sub-job rule).

Exact levels, two ways (Henrik 07-14: checker's levels come from the /check
reply itself, widescan only backfills NMs):
 - AUTO-CHECK: every engage fires the same c2s 0x0DD request the Check menu
   sends (pure read; mobs notify nobody -- only checked PLAYERS see "checks
   you", and engage targets are mobs). The acc line waits ~0.8s for the
   reply, which is cached and swallowed (e.blocked) so chat stays clean --
   the level arrives without the user noticing. Manual /check outside that
   window still prints normally. Injection precedent: craftwatch 0x10F.
 - AUTO-CHECKPARAM: the same engage also fires 0x0DD Kind 2 at YOURSELF,
   first (server replies in order, so the ACC lands before the report).
   CHECKPARAM_PRIMARY (msg 712) p1 = your current mainhand ACC with gear/
   food/buffs. The reply burst is swallowed the same way. The report then
   ends with the verdict: "you N: CAPPED (+x)" or "you N: +x more".
 - PASSIVE: any /check reply (0x029 p1) or widescan reply (0x0F4) caches
   idx -> level for the zone regardless (wiped on zone-in).
A live level collapses the range to one exact number, marked *. NMs answer
"impossible to gauge" (no level) -> widescan stays their only level source.

Caps (physical_hit_rate.lua): 99% for 1H mainhand / H2H -> ACC = EVA + 48;
95% for 2H -> ACC = EVA + 40. The mainhand is sniffed from the equipped
weapon's skill type so the right cap is chosen automatically.

Level correction (Henrik ruling v3, 2026-07-14, live -- supersedes v2's
penalty-only reading): SIGNED and EVERYWHERE, 4 ACC (= 2% hit) per level of
difference -- a mob ABOVE your level costs 4 ACC per level, a mob BELOW
grants 4 ACC per level ("just as I get -4 when I am underleveled"). 75-era
server with no Adoulin zones; the published repo's zone list and sign are
treated as wrong for live. The printed need folds the correction in (need
can go far negative on grey mobs -- that is the point: AutoAcc releases
everything). Ground truth if this needs re-litigating: dlacprobe
/probe tally (battle-log hit-rate counter).

AUTOACC FEED (2026-07-14): every report also writes <char>\dlac\accstate.lua
    return { seq = N, valid = bool, capGap = need - yourACC, at = os.time(), mob = '...' }
(capGap is the printed AccCap number: negative = over cap by that much). The
dispatch ENGINE hot-reads it and uses the surplus to release AutoAcc-typed
set pieces (dlac:AutoAcc markers -- see dispatch.lua "Type automations").
valid=false whenever the number cannot be computed -- mob not in the table
(custom/HNM), your ACC not yet measured, accdata missing -- and when the
watch is toggled OFF: the engine then leaves AutoAcc pieces worn as normal
gear. seq bumps per write so the engine re-freezes its removal budget once
per measurement, not once per frame.
]]

local M = {};
M.enabled = false;
M.debug = false;    -- /dl acc debug: trace engage/inject/reply/cache decisions

local _cfok, _cfmt = pcall(require, 'dlac\\chatfmt');
_cfok = _cfok and type(_cfmt) == 'table';
local function say(s) if _cfok and _cfmt.msg then _cfmt.msg(s); else print('[dlac] ' .. s); end end
local function dbg(s) if M.debug then say('acc dbg: ' .. s); end end

local _dok, DATA = pcall(require, 'dlac\\accdata');
_dok = _dok and type(DATA) == 'table' and type(DATA.zones) == 'table';

-- entity name -> accdata key: lowercase alphanumerics only (mirror of the
-- generator's squash(); survives apostrophes/underscores/spacing differences)
local function squash(name)
    return (tostring(name or ''):lower():gsub('[^%a%d]+', ''));
end

-- item resource .Skill of the equipped mainhand: 2H = gsword 4, gaxe 6,
-- scythe 7, polearm 8, gkatana 10, staff 12. H2H (1) caps like 1H.
local TWOHAND = { [4] = true, [6] = true, [7] = true, [8] = true, [10] = true, [12] = true };

local function mainhandIs2H()
    local is2h = false;
    pcall(function()
        local inv = AshitaCore:GetMemoryManager():GetInventory();
        local eitem = inv:GetEquippedItem(0);                     -- slot 0 = Main
        if eitem == nil or eitem.Index == 0 then return; end
        local cont = math.floor(eitem.Index / 256) % 256;         -- packed: high byte = container
        local slot = eitem.Index % 256;                           -- (augments.lua:231)
        local item = inv:GetContainerItem(cont, slot);
        if item == nil or item.Id == 0 then return; end
        local res = AshitaCore:GetResourceManager():GetItemById(item.Id);
        if res ~= nil and TWOHAND[res.Skill] == true then is2h = true; end
    end);
    return is2h;
end

local function band(a, b)
    local lo, hi = math.min(a, b), math.max(a, b);
    if lo == hi then return tostring(lo); end
    return ('%d-%d'):format(lo, hi);
end

-- EVA at an exact level: linear interpolation between the accdata endpoints
-- (EVA is ~linear inside a spawn range; good to +-1 for the usual short spans)
local function evaAt(e, lvl)
    if e[2] <= e[1] then return e[3]; end
    return math.floor(e[3] + (e[4] - e[3]) * (lvl - e[1]) / (e[2] - e[1]) + 0.5);
end

-- passive exact-level cache, checker-style: /check replies (non-NM) and any
-- widescan replies that happen to arrive. actIndex -> level, wiped on zone-in.
local seenLevels = {};
local CHECK_MSG = { [0xAA] = 1, [0xAB] = 1, [0xAC] = 1, [0xAD] = 1, [0xAE] = 1,
                    [0xAF] = 1, [0xB0] = 1, [0xB1] = 1, [0xB2] = 1 };

-- learned EVA bounds from the /check brackets. The server compares RAW
-- mainhand ACC vs RAW EVA (no level correction): High Eva <=> EVA-30 > ACC,
-- Low Eva <=> EVA+10 <= ACC. The public-repo formula underestimates some
-- live mobs (field 2026-07-14: Wajaom Tiger Lv69 -- model 269, bracket
-- proved >=287; private tuning we cannot read), so every check reply narrows
-- [lo,hi] per (zone, mob, level) and the report clamps the model into the
-- learned bounds. Session-scoped. The learn runs BEFORE the pending report
-- fires, so even a first-ever engage prints bracket-corrected numbers.
local learned = {};   -- 'zone/squashedname@lvl' -> { lo, hi }
local HIGH_EVA = { [0xAA] = 1, [0xAB] = 1, [0xAC] = 1 };
local LOW_EVA  = { [0xB0] = 1, [0xB1] = 1, [0xB2] = 1 };

local function learnKey(zone, name, lvl)
    return tostring(zone) .. '/' .. squash(name) .. '@' .. tostring(lvl);
end

local function learnEva(zone, tgt, lvl, msg)
    if M.myAcc == nil or lvl == nil or lvl <= 0 then return; end
    local name = '';
    pcall(function() name = AshitaCore:GetMemoryManager():GetEntity():GetName(tgt) or ''; end);
    if name == '' then return; end
    local k = learnKey(zone, name, lvl);
    local lo, hi = 0, 9999;
    if HIGH_EVA[msg] ~= nil then
        lo = M.myAcc + 31;
    elseif LOW_EVA[msg] ~= nil then
        hi = M.myAcc - 10;
    else                                                          -- neutral eva bracket
        lo, hi = M.myAcc - 9, M.myAcc + 30;
    end
    local b = learned[k] or { lo = 0, hi = 9999 };
    b.lo = math.max(b.lo, lo);
    b.hi = math.min(b.hi, hi);
    if b.lo > b.hi then                                           -- contradicts older bounds
        b.lo, b.hi = lo, hi;                                      -- (regear/repop): trust newest
    end
    learned[k] = b;
    dbg(('bracket: %s EVA in [%d..%d]'):format(k, b.lo, b.hi));
end

-- /checkparam reply burst (server enums/msg_basic.h): PRIMARY 712 carries the
-- player's CURRENT mainhand ACC (gear+food+buffs) as p1. The rest are muted
-- alongside it when our auto-checkparam fired them.
M.myAcc = nil;
local CHECKPARAM_MSG = { [712] = 1, [713] = 1, [714] = 1, [715] = 1, [731] = 1, [733] = 1 };

local function myIndex()
    local idx, sid = 0, 0;
    pcall(function()
        local pt = AshitaCore:GetMemoryManager():GetParty();
        idx = pt:GetMemberTargetIndex(0) or 0;
        sid = pt:GetMemberServerId(0) or 0;
    end);
    return idx, sid;
end

-- ---------------------------------------------------------------------------
-- AutoAcc feed: publish the cap gap to <char>\dlac\accstate.lua for the
-- dispatch engine (two Lua states, files are the only bridge -- craftstate
-- precedent). gap == nil means "could not compute" -> valid = false, which
-- tells the engine to leave AutoAcc pieces worn (Henrik: unknown mobs are
-- handled as per usual).
-- ---------------------------------------------------------------------------
local accSeq = 0;

local function charDlacDir()
    local name, id;
    pcall(function()
        local party = AshitaCore:GetMemoryManager():GetParty();
        name = party:GetMemberName(0);
        id   = party:GetMemberServerId(0);
        if name == '' then name = nil; end
    end);
    if name == nil or id == nil then return nil; end
    return string.format('%sconfig\\addons\\luashitacast\\%s_%u\\dlac\\',
        AshitaCore:GetInstallPath(), name, id);
end

local function writeAccState(gap, mob)
    pcall(function()
        local dir = charDlacDir();
        if dir == nil then return; end
        accSeq = accSeq + 1;
        local f = io.open(dir .. 'accstate.lua', 'wb');
        if f == nil then return; end
        f:write(string.format('return { seq = %d, valid = %s, capGap = %d, at = %d, mob = %q }\n',
            accSeq, tostring(gap ~= nil), math.floor(tonumber(gap) or 0), os.time(), tostring(mob or '')));
        f:close();
        dbg(('accstate: %s%s'):format(gap ~= nil and ('capGap ' .. tostring(gap)) or 'INVALID',
            (mob ~= nil and mob ~= '') and (' (' .. tostring(mob) .. ')') or ''));
    end);
end

-- ---------------------------------------------------------------------------
-- Custom-mob fallback (Henrik 2026-07-14, the Wajaom Toucans): CatsEyeXI
-- spawns custom mobs (dynamic entities, idx 0x800+) that exist in NO zone's
-- static table -- the zone lookup misses, and widescan cannot help because it
-- only collapses level ranges for mobs already IN the table. But customs
-- reuse stock pools/families ("Toucan" = family Bird), and accdata ships one
-- EVA-by-level curve per family. So: resolve the FAMILY -- a per-char manual
-- assignment (accfamilies.lua, /dl acc family) wins, else a cross-zone name
-- match -- and price the mob from the curve at its LIVE level. The
-- synthesized entry flows through the normal report path, so the bracket
-- clamp, the accstate feed and AutoAcc all just work. Curves are a FLOOR
-- (most common job combo, no pool mods, non-NM); /check brackets correct.
-- ---------------------------------------------------------------------------
local function familyEva(key, lvl)
    if not _dok or type(DATA.families) ~= 'table' then return nil; end
    local curve = DATA.families[key];
    if type(curve) ~= 'table' then return nil; end
    lvl = math.floor(tonumber(lvl) or 0);
    if lvl < 1 or lvl > #curve then return nil; end
    return curve[lvl];
end
M._familyEva = familyEva;                     -- headless tests

-- Player input -> curve key: exact squash, then singular (drop one trailing
-- 's': 'birds' -> 'bird'), then unique prefix. nil + a chat-ready why on miss.
local function resolveFamilyKey(input)
    if not _dok or type(DATA.families) ~= 'table' then
        return nil, 'accdata has no family curves -- regenerate accdata.lua';
    end
    local q = squash(input);
    if q == '' then return nil, 'give a family name, e.g. /dl acc family bird'; end
    if DATA.families[q] ~= nil then return q; end
    if string.sub(q, -1) == 's' and DATA.families[string.sub(q, 1, -2)] ~= nil then
        return string.sub(q, 1, -2);
    end
    local hit, hits = nil, 0;
    for k in pairs(DATA.families) do
        if string.sub(k, 1, #q) == q then hit = k; hits = hits + 1; end
    end
    if hits == 1 then return hit; end
    if hits > 1 then return nil, ('"%s" matches %d families -- be more specific'):format(tostring(input), hits); end
    return nil, ('unknown family "%s"'):format(tostring(input));
end
M._resolveFamilyKey = resolveFamilyKey;       -- headless tests

-- The family a squashed name maps to ANYWHERE in the static table (first word
-- of the entry's 'Family MJOB/SJOB' desc). Lazy full-table index, built once.
local _nameFam = nil;
local function crossZoneFamily(sqName)
    if not _dok then return nil; end
    if _nameFam == nil then
        _nameFam = {};
        for _, zt in pairs(DATA.zones) do
            for nm, e in pairs(zt) do
                if _nameFam[nm] == nil and type(e[6]) == 'string' then
                    local fam = string.match(e[6], '^(%S+)');
                    if fam ~= nil then _nameFam[nm] = squash(fam); end
                end
            end
        end
    end
    return _nameFam[sqName];
end
M._crossZoneFamily = crossZoneFamily;         -- headless tests

-- Per-char manual assignments: '<zone>/<squashedname>' -> family key. Loaded
-- lazily (charDlacDir needs a logged-in character); saved on every change.
local _customFam = nil;
local function customFams()
    if _customFam ~= nil then return _customFam; end
    local dir = charDlacDir();
    if dir == nil then return {}; end          -- pre-login throwaway: retry next call
    _customFam = {};
    pcall(function()
        local chunk = loadfile(dir .. 'accfamilies.lua');
        if chunk ~= nil then
            local ok, t = pcall(chunk);
            if ok and type(t) == 'table' then
                for k, v in pairs(t) do
                    if type(k) == 'string' and type(v) == 'string' then _customFam[k] = v; end
                end
            end
        end
    end);
    return _customFam;
end

local function saveCustomFams()
    pcall(function()
        local dir = charDlacDir();
        if dir == nil or _customFam == nil then return; end
        local keys = {};
        for k in pairs(_customFam) do keys[#keys + 1] = k; end
        table.sort(keys);
        local f = io.open(dir .. 'accfamilies.lua', 'wb');
        if f == nil then return; end
        f:write('-- dlac acc watch: manual family assignments for custom mobs\n');
        f:write('-- ("/dl acc family <name>" with the mob targeted). zone/squashedname -> family curve.\n');
        f:write('return {\n');
        for _, k in ipairs(keys) do
            f:write(('[%q] = %q,\n'):format(k, _customFam[k]));
        end
        f:write('}\n');
        f:close();
    end);
end

local function report(actIndex, why, full)
    if not _dok then
        say('acc: accdata.lua missing/bad -- regenerate: python tools\\acc_calc.py --luadata accdata.lua');
        writeAccState(nil);
        return;
    end
    local name = '';
    pcall(function() name = AshitaCore:GetMemoryManager():GetEntity():GetName(actIndex) or ''; end);
    if name == '' then return; end
    local zone = -1;
    pcall(function() zone = AshitaCore:GetMemoryManager():GetParty():GetMemberZone(0); end);
    local z = DATA.zones[zone];
    local e = z ~= nil and z[squash(name)] or nil;
    if e == nil then
        -- Custom-mob fallback: family (manual assignment wins, else cross-zone
        -- name match) + live level -> synthesize the entry from the family curve.
        local sq = squash(name);
        local fam = customFams()[tostring(zone) .. '/' .. sq] or crossZoneFamily(sq);
        local seen = seenLevels[actIndex];
        local ev = (fam ~= nil and seen ~= nil) and familyEva(fam, seen) or nil;
        if ev ~= nil then
            e = { seen, seen, ev, ev, 0, fam .. ' (family curve)' };
            dbg(('custom fallback: %s -> family %s, Lv%d -> EVA %d'):format(name, fam, seen, ev));
        elseif fam ~= nil then
            say(('acc%s: %s -- custom mob, family "%s" known, but no live level yet: engage it again once a /check has answered (engage auto-checks), or open widescan once.'):format(
                why or '', name, fam));
            writeAccState(nil, name);
            return;
        else
            say(('acc%s: %s%s -- not in this zone\'s table and no family known (custom mob). Target it and assign one: /dl acc family <family>  (e.g. bird)'):format(
                why or '', name, seen ~= nil and (' Lv%d*'):format(seen) or ''));
            writeAccState(nil, name);   -- MobEVA unknown -> AutoAcc stands down (pieces stay worn)
            return;
        end
    end
    local lo, hi, evLo, evHi, nm, desc = e[1], e[2], e[3], e[4], e[5], e[6];
    local exact = '';
    local seen = seenLevels[actIndex];
    if seen ~= nil and seen >= lo and seen <= hi then             -- live level known: collapse
        lo, hi = seen, seen;                                      -- the range to one number
        evLo = evaAt(e, seen);
        evHi = evLo;
        exact = '*';                                              -- * = level observed live
    end
    local braNote = '';
    if exact ~= '' then                                           -- clamp into bracket-learned bounds
        local b = learned[learnKey(zone, name, lo)];
        if b ~= nil then
            local e2 = math.max(b.lo, math.min(b.hi, evLo));
            if e2 ~= evLo then
                braNote = (' [bracket-corrected, model %d]'):format(evLo);
                evLo, evHi = e2, e2;
            end
        end
    end
    local is2h = mainhandIs2H();
    local add = is2h and 40 or 48;                                -- to 95% / 99%
    local needLo, needHi = evLo + add, evHi + add;
    local corr = '';
    local pl = 0;                                                 -- ruling v3: signed, everywhere
    pcall(function() pl = AshitaCore:GetMemoryManager():GetPlayer():GetMainJobLevel() or 0; end);
    if pl > 0 then
        needLo = needLo + (lo - pl) * 4;                          -- +4 ACC needed per level the mob
        needHi = needHi + (hi - pl) * 4;                          -- is above you, -4 per level below
        if pl ~= hi then
            corr = (' [lvl corr %+d ACC, you Lv%d]'):format((pl - hi) * 4, pl);
        end
    end
    local cap = is2h and 95 or 99;
    -- AutoAcc feed: publish the printed AccCap number (worst-case end, level
    -- correction folded in). No measured ACC yet -> invalid, engine stands down.
    if M.myAcc ~= nil then
        writeAccState(math.max(needLo, needHi) - M.myAcc, name);
    else
        writeAccState(nil, name);
    end
    -- default (engage/switch) output, Henrik's format 2026-07-15. Range mobs
    -- use the worst-case (highest level/EVA) end. Full line: /dl acc now.
    if full ~= true and M.myAcc ~= nil then
        local acc = M.myAcc;
        local eHi = math.max(evLo, evHi);
        local lvlTerm = 0;
        if pl > 0 then lvlTerm = (pl - hi) * 4; end               -- ruling v3: signed both ways
        local pct = math.max(20, math.min(cap, 75 + (acc + lvlTerm - eHi) / 2));
        say(('%s Lv%s%s - MobEVA %s - CurrentAcc: %d - AccCmp: %d - AccCmpLvl: %d - AccPct: %.0f%% - AccCap: %d'):format(
            name, band(lo, hi), exact, band(evLo, evHi), acc,
            eHi - acc, lvlTerm, pct, math.max(needLo, needHi) - acc));
        return;
    end
    local you = '';
    if M.myAcc ~= nil then                                        -- fresh from auto-checkparam
        -- correction can invert the band (higher mob level -> lower need)
        local nLo, nHi = math.min(needLo, needHi), math.max(needLo, needHi);
        if M.myAcc >= nHi then
            you = ('  |  you %d: CAPPED (+%d)'):format(M.myAcc, M.myAcc - nHi);
        elseif M.myAcc < nLo then
            you = ('  |  you %d: +%s more'):format(M.myAcc, band(nLo - M.myAcc, nHi - M.myAcc));
        else
            you = ('  |  you %d: caps part of the Lv range'):format(M.myAcc);
        end
        if exact ~= '' then                                       -- exact level -> exact hit rate
            local hit = math.max(20, math.min(cap, cap - (nLo - M.myAcc) / 2));
            you = you .. (' ~%.0f%% hit'):format(hit);
        end
    end
    say(('acc%s: %s Lv%s%s (%s%s)  EVA %s%s  ->  ACC %s to cap (%s %d%%)%s%s'):format(
        why or '', name, band(lo, hi), exact, desc, nm == 1 and ', NM' or '',
        band(evLo, evHi), braNote, band(needLo, needHi), is2h and '2H' or '1H/H2H', cap, corr, you));
end

-- ---------------------------------------------------------------------------
-- Ashita glue (guarded so the module stays headless-loadable, craftwatch:581)
-- ---------------------------------------------------------------------------
local lastTarget = nil;   -- debounce: same-mob re-engage inside 5s stays quiet
local lastAt = 0;
local pending = nil;      -- { idx, at }: engage waiting for its auto-check reply
local muteIdx = -1;       -- swallow check replies for this idx until muteUntil
local muteUntil = 0;      -- (only replies OUR auto-check caused; manual /check prints)
local muteSelfIdx = -1;   -- same idea for our auto-checkparam's reply burst
local muteSelfUntil = 0;

if ashita ~= nil and ashita.events ~= nil and type(ashita.events.register) == 'function' then
    -- level learning: /check reply 0x029 (p1 = exact level, non-NM only --
    -- gated on the check message/type ids so other battle messages can't
    -- pollute the cache) and widescan reply 0x0F4 (levels for everything,
    -- NMs included). Auto-check replies are blocked here and the deferred
    -- engage report fires the moment they land.
    ashita.events.register('packet_in', 'dlac-accwatch-in', function(e)
        if e.id == 0x00A then seenLevels = {}; pending = nil; return; end   -- indexes recycle
        if e.id ~= 0x029 and e.id ~= 0x0F4 then return; end
        pcall(function()
            local d = e.data;
            if e.id == 0x0F4 then
                local idx = d:byte(0x04 + 1) + d:byte(0x05 + 1) * 256;
                local lvl = d:byte(0x06 + 1);
                if idx > 0 and lvl > 0 then
                    seenLevels[idx] = lvl;
                    dbg(('widescan cache idx=0x%03X Lv%d'):format(idx, lvl));
                end
                return;
            end
            if #d < 0x1A then return; end
            local p1  = d:byte(0x0C + 1) + d:byte(0x0D + 1) * 256;
            local hi  = d:byte(0x0E + 1) + d:byte(0x0F + 1) * 256;
            local p2  = d:byte(0x10 + 1);
            local tgt = d:byte(0x16 + 1) + d:byte(0x17 + 1) * 256;
            local msg = d:byte(0x18 + 1) + d:byte(0x19 + 1) * 256;
            if CHECKPARAM_MSG[msg] ~= nil then                    -- /checkparam reply burst
                if tgt == muteSelfIdx and os.clock() < muteSelfUntil then
                    e.blocked = true;                             -- ours: keep chat clean
                end
                if msg == 712 and hi == 0 and p1 > 0 and p1 < 4096 then
                    local midx = myIndex();
                    if tgt == midx then                           -- self, not a pet checkparam
                        M.myAcc = p1;
                        dbg(('checkparam: your mainhand ACC = %d'):format(p1));
                    end
                end
                return;
            end
            local isCheck = (CHECK_MSG[msg] ~= nil and p2 >= 0x40 and p2 <= 0x47)
                         or msg == 0xF9;                          -- 0xF9 = impossible to gauge (NM)
            if not isCheck then
                if pending ~= nil and pending.idx == tgt then     -- reply-shaped miss: show why
                    dbg(('0x029 for pending idx=0x%03X NOT check-shaped: msg=0x%02X p2=0x%02X p1=%d'):format(
                        tgt, msg, p2, p1));
                end
                return;
            end
            dbg(('check reply tgt=0x%03X msg=0x%02X p2=0x%02X p1=%d%s%s'):format(
                tgt, msg, p2, p1,
                (tgt == muteIdx and os.clock() < muteUntil) and ' [mute]' or '',
                (pending ~= nil and pending.idx == tgt) and ' [pending hit]' or ''));
            if CHECK_MSG[msg] ~= nil then
                if hi == 0 and p1 > 0 and p1 < 200 then
                    seenLevels[tgt] = p1;
                end
                local zone = -1;
                pcall(function() zone = AshitaCore:GetMemoryManager():GetParty():GetMemberZone(0); end);
                learnEva(zone, tgt, seenLevels[tgt], msg);        -- narrows EVA bounds BEFORE the report fires
            end
            if tgt == muteIdx and os.clock() < muteUntil then
                e.blocked = true;                                 -- our auto-check: keep chat clean
            end
            if pending ~= nil and pending.idx == tgt then
                local idx = pending.idx;
                pending = nil;
                report(idx, nil);
            end
        end);
    end);

    ashita.events.register('packet_out', 'dlac-accwatch-out', function(e)
        if not M.enabled or e.id ~= 0x01A then return; end
        pcall(function()
            local d = e.data;
            local action = d:byte(0x0A + 1) + d:byte(0x0B + 1) * 256;
            if action ~= 0x02 and action ~= 0x0F then return; end -- attack / change target
            local idx = d:byte(0x08 + 1) + d:byte(0x09 + 1) * 256;
            local sid = d:byte(0x04 + 1) + d:byte(0x05 + 1) * 256
                      + d:byte(0x06 + 1) * 65536 + d:byte(0x07 + 1) * 16777216;
            if sid == lastTarget and os.clock() - lastAt < 5 then return; end
            lastTarget = sid;
            lastAt = os.clock();
            -- auto-check: the request the Check menu sends. Layout from the
            -- SERVER's 0x0dd_equip_inspect.h (NOT the XiPackets u16 guess!):
            -- 16 bytes -- UniqueNo u32 @0x04, ActIndex u32 @0x08, Kind u8
            -- @0x0C (0 = Check, enum-validated) + 3 pad. A 12-byte packet is
            -- dropped by the validator without a reply (the v1 bug).
            dbg(('%s idx=0x%03X sid=%d -> auto-checkparam + auto-check'):format(
                action == 0x02 and 'engage' or 'target switch', idx, sid));
            pending = { idx = idx, at = os.clock() };
            muteIdx = idx;
            muteUntil = os.clock() + 1.0;
            -- /checkparam (self) FIRST: the server answers in order, so the
            -- fresh ACC (CHECKPARAM_PRIMARY p1) lands before the mob check
            -- reply triggers the report. Same 0x0DD struct, Kind 2, self ids.
            local midx, msid = myIndex();
            if msid > 0 then
                muteSelfIdx = midx;
                muteSelfUntil = os.clock() + 1.0;
                pcall(function()
                    AshitaCore:GetPacketManager():AddOutgoingPacket(0x0DD, {
                        0xDD, 0x08, 0x00, 0x00,
                        msid % 256, math.floor(msid / 256) % 256,
                        math.floor(msid / 65536) % 256, math.floor(msid / 16777216) % 256,
                        midx % 256, math.floor(midx / 256) % 256, 0x00, 0x00,
                        0x02, 0x00, 0x00, 0x00 });
                end);
            end
            local ok, err = pcall(function()
                AshitaCore:GetPacketManager():AddOutgoingPacket(0x0DD, {
                    0xDD, 0x08, 0x00, 0x00,
                    d:byte(0x04 + 1), d:byte(0x05 + 1), d:byte(0x06 + 1), d:byte(0x07 + 1),
                    d:byte(0x08 + 1), d:byte(0x09 + 1), 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00 });
            end);
            if not ok then                                        -- can't inject: report now
                say('auto-check inject FAILED (' .. tostring(err) .. ') -- reporting from cache');
                pending = nil;
                report(idx, nil);
            end
        end);
    end);

    -- fallback: the check reply never came (lag, dynamic entity, filtered) --
    -- print the report from whatever is cached rather than staying silent.
    ashita.events.register('d3d_present', 'dlac-accwatch-tick', function()
        if pending == nil then return; end
        if os.clock() - pending.at > 0.8 then
            local idx = pending.idx;
            pending = nil;
            muteIdx = -1;   -- no reply came; don't eat a later manual /check
            dbg(('auto-check TIMED OUT for idx=0x%03X -- server dropped the request or reply unmatched'):format(idx));
            pcall(report, idx, nil);
        end
    end);

    -- /dl acc [now] -- toggle the engage watch, or report the current target.
    ashita.events.register('command', 'dlac-accwatch-cmd', function(e)
        pcall(function()
            local raw = string.lower(e.command or '');
            local a, b = raw:match('^/dl%s+(%S+)%s*(%S*)');
            if a == nil then a, b = raw:match('^/dlac%s+(%S+)%s*(%S*)'); end
            if a ~= 'acc' then return; end
            e.blocked = true;
            if b == 'now' then
                local idx = 0;
                pcall(function() idx = AshitaCore:GetMemoryManager():GetTarget():GetTargetIndex(0); end);
                if idx == nil or idx == 0 then say('acc: no target.'); return; end
                report(idx, '(target)');   -- same labeled line as engage (Henrik 07-15)
                return;
            end
            if b == 'debug' then
                M.debug = not M.debug;
                say('acc debug ' .. (M.debug and 'ON -- traces engage/inject/reply/cache' or 'OFF') .. '.');
                return;
            end
            if b == 'family' then
                -- Assign/show/clear the CURRENT TARGET's family (custom mobs).
                local arg = raw:match('^/dl%s+acc%s+family%s*(.*)$')
                         or raw:match('^/dlac%s+acc%s+family%s*(.*)$') or '';
                arg = arg:match('^%s*(.-)%s*$') or '';
                local idx = 0;
                pcall(function() idx = AshitaCore:GetMemoryManager():GetTarget():GetTargetIndex(0); end);
                if idx == nil or idx == 0 then say('acc family: target the mob first.'); return; end
                local name = '';
                pcall(function() name = AshitaCore:GetMemoryManager():GetEntity():GetName(idx) or ''; end);
                if name == '' then say('acc family: cannot read the target\'s name.'); return; end
                local zone = -1;
                pcall(function() zone = AshitaCore:GetMemoryManager():GetParty():GetMemberZone(0); end);
                local fkey = tostring(zone) .. '/' .. squash(name);
                local fams = customFams();
                if arg == '' then
                    local assigned = fams[fkey];
                    local auto = crossZoneFamily(squash(name));
                    if assigned ~= nil then
                        say(('acc family: %s = %s (assigned; "/dl acc family clear" to remove).'):format(name, assigned));
                    elseif auto ~= nil then
                        say(('acc family: %s = %s (automatic name match -- no assignment needed).'):format(name, auto));
                    else
                        say(('acc family: %s is unknown -- assign one: /dl acc family <family>  (e.g. bird).'):format(name));
                    end
                    return;
                end
                if arg == 'clear' or arg == 'off' or arg == 'none' then
                    if fams[fkey] ~= nil then
                        fams[fkey] = nil;
                        saveCustomFams();
                        say(('acc family: cleared %s.'):format(name));
                    else
                        say(('acc family: %s has no manual assignment.'):format(name));
                    end
                    return;
                end
                local key, whyNot = resolveFamilyKey(arg);
                if key == nil then
                    say('acc family: ' .. tostring(whyNot) .. '.');
                    return;
                end
                fams[fkey] = key;
                saveCustomFams();
                say(('acc family: %s = %s (saved).'):format(name, key));
                report(idx, '(family set)');   -- instant feedback; explains itself if the level is still missing
                return;
            end
            M.enabled = not M.enabled;
            if not M.enabled then writeAccState(nil); end   -- watch off -> AutoAcc inert
            say('acc watch ' .. (M.enabled and
                'ON -- each fight: Mob/EVA/CurrentAcc/AccCmp/AccCmpLvl/AccPct/AccCap; /dl acc now = detail.'
                or 'OFF.'));
        end);
    end);
end

return M;
