-- digdata.lua -- the chocobo-digging database, to be GENERATED by
-- tools/gen_digdata.py from the CatsEyeXI server's chocobo-digging data
-- (following the gen_petmods.py / gen_zones.py pattern). Do not hand-edit the
-- generated sections; rebuild with:
--   python tools/gen_digdata.py      (maintainer only, ships with updates)
-- Loaded lazily and fails soft (feature/digcalc.lua M.db) -- a missing or
-- partial table disables the data-backed queries, never errors.
--
-- ===========================================================================
-- !! DATA STATUS (issue #94) !!  The per-zone loot pools below (`zones`) are
-- the CatsEyeXI-SPECIFIC part of the data: the 26 enabled digging zones, each
-- item's dig weight and rank requirement, grouped by pool. Those numbers live
-- ONLY in the server's private chocobo-digging source and MUST be populated by
-- running gen_digdata.py against that checkout (maintainer-only) BEFORE the
-- digging guide ships. Until then `zones` is empty and every by-zone query
-- fails soft. The odds engine (digcalc) is fully implemented and tested against
-- hand-computed pools independent of this table; the conditional rule tables
-- below are FFXI-standard and complete. See the PR for #94 for the hand-over.
-- ===========================================================================
--
-- Shapes (docs/design/chocobo-dig.md, PRD #93 / issue #94):
--   zones[zoneId] = { n = "Zone Name", pools = { <Pool> = { <item>, ... } } }
--     <Pool> in { "Treasure", "Regular", "Bore", "Burrow" } (server grant order)
--     <item> = { id = <itemId>, n = "English Name", w = <weight>, rank = <req> }
--       w    = dig weight (higher = more likely; digcalc: q = min(1, w/(1000*mu)))
--       rank = dig-rank requirement, index into `ranks` below (0 = Amateur)
--   cond = the conditional Regular-pool rule tables (maps + gates), below.
--   ranks = the 0..10 dig-rank ladder (index = rank number).

return {

-- The dig-rank ladder (0..10 = the CatsEye craftRank range for Digging),
-- matching the server's first-dig zone cooldown clamp(60 - 5*rank, 10, 60)s:
-- Amateur(0)=60s .. Adept(8)=20s, Veteran(9)=15s, Expert(10)=10s (the 10s floor
-- makes rank 10 the effective max). Rock/ore gates reference it by index
-- (Novice = 3, Craftsman = 6). Loot rankReq itself never exceeds Adept(8), so
-- ranks 9/10 only sharpen the rank LABEL + the timing detection (issue #100).
ranks = {
  [0] = "Amateur",
  [1] = "Recruit",
  [2] = "Initiate",
  [3] = "Novice",
  [4] = "Apprentice",
  [5] = "Journeyman",
  [6] = "Craftsman",
  [7] = "Artisan",
  [8] = "Adept",
  [9] = "Veteran",
  [10] = "Expert",
},

-- The enabled digging zones + their loot pools. GENERATED (see DATA STATUS
-- above) -- empty until gen_digdata.py runs against the private source. The
-- generator emits exactly the 26 zones where digging is enabled on the server
-- (not the 58 that merely carry loot data).
zones = {
  [2] = { n = "Carpenters Landing", pools = {
    Treasure = {
      { id = 4386, n = "King Truffle", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17396, n = "Little Worm", w = 100, rank = 0 },
      { id = 688, n = "Arrowwood Log", w = 100, rank = 0 },
      { id = 4504, n = "Acorn", w = 50, rank = 1 },
      { id = 695, n = "Willow Log", w = 50, rank = 1 },
      { id = 691, n = "Maple Log", w = 50, rank = 2 },
      { id = 697, n = "Holly Log", w = 50, rank = 2 },
      { id = 918, n = "Sprig of Mistletoe", w = 10, rank = 5 },
      { id = 4447, n = "Scream Fungus", w = 10, rank = 6 },
    },
    Bore = {
      { id = 688, n = "Arrowwood Log", w = 240, rank = 0 },
      { id = 696, n = "Yew Log", w = 150, rank = 0 },
      { id = 690, n = "Elm Log", w = 100, rank = 1 },
      { id = 699, n = "Oak Log", w = 50, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 10, rank = 3 },
      { id = 700, n = "Mahogany Log", w = 5, rank = 4 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
      { id = 720, n = "Piece of Ancient Lumber", w = 1, rank = 6 },
      { id = 1446, n = "Lacquer Tree Log", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
  } },
  [4] = { n = "Bibiki Bay", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2603, n = "Coin of Birth", w = 5, rank = 8 },
    },
    Regular = {
      { id = 641, n = "Chunk of Tin Ore", w = 50, rank = 0 },
      { id = 17395, n = "Lugworm", w = 50, rank = 0 },
      { id = 17397, n = "Shell Bug", w = 10, rank = 1 },
      { id = 888, n = "Seashell", w = 100, rank = 1 },
      { id = 4484, n = "Shall Shell", w = 50, rank = 2 },
      { id = 847, n = "Bird Feather", w = 50, rank = 2 },
      { id = 893, n = "Giant Femur", w = 50, rank = 2 },
      { id = 738, n = "Chunk of Platinum Ore", w = 5, rank = 7 },
      { id = 887, n = "Coral Fragment", w = 5, rank = 7 },
    },
    Bore = {
      { id = 880, n = "Bone Chip", w = 150, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 150, rank = 0 },
      { id = 888, n = "Seashell", w = 150, rank = 1 },
      { id = 1587, n = "Handful of High-Quality Pugil Scales", w = 50, rank = 2 },
      { id = 1586, n = "Titanictus Shell", w = 50, rank = 4 },
      { id = 902, n = "Demon Horn", w = 10, rank = 5 },
      { id = 866, n = "Handful of Wyvern Scales", w = 5, rank = 6 },
      { id = 885, n = "Turtle Shell", w = 5, rank = 6 },
      { id = 886, n = "Demon Skull", w = 1, rank = 7 },
      { id = 867, n = "Handful of Dragon Scales", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 1845, n = "Clump of Red Moko Grass", w = 100, rank = 0 },
      { id = 845, n = "Black Chocobo Feather", w = 50, rank = 1 },
      { id = 838, n = "Spider Web", w = 5, rank = 3 },
      { id = 843, n = "Giant Bird Plume", w = 10, rank = 2 },
      { id = 844, n = "Phoenix Feather", w = 1, rank = 6 },
    },
  } },
  [51] = { n = "Wajaom Woodlands", pools = {
    Treasure = {
      { id = 2488, n = "Piece of Alexandrite", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 100, rank = 0 },
      { id = 833, n = "Clump of Moko Grass", w = 100, rank = 0 },
      { id = 2213, n = "Handful of Pine Nuts", w = 50, rank = 1 },
      { id = 845, n = "Black Chocobo Feather", w = 50, rank = 1 },
      { id = 702, n = "Ebony Log", w = 50, rank = 2 },
      { id = 838, n = "Spider Web", w = 10, rank = 3 },
      { id = 2164, n = "Pephredo Hive Chip", w = 10, rank = 4 },
      { id = 646, n = "Chunk of Adaman Ore", w = 10, rank = 6 },
    },
    Bore = {
      { id = 768, n = "Flint Stone", w = 240, rank = 0 },
      { id = 678, n = "Chunk of Aluminum Ore", w = 100, rank = 1 },
      { id = 737, n = "Chunk of Gold Ore", w = 50, rank = 2 },
      { id = 645, n = "Chunk of Darksteel Ore", w = 10, rank = 3 },
      { id = 2475, n = "Chunk of Kaolin", w = 10, rank = 3 },
      { id = 738, n = "Chunk of Platinum Ore", w = 5, rank = 5 },
      { id = 739, n = "Chunk of Orichalcum Ore", w = 1, rank = 6 },
    },
    Burrow = {
      { id = 833, n = "Clump of Moko Grass", w = 240, rank = 0 },
      { id = 688, n = "Arrowwood Log", w = 240, rank = 0 },
      { id = 2164, n = "Pephredo Hive Chip", w = 150, rank = 0 },
      { id = 696, n = "Yew Log", w = 150, rank = 0 },
      { id = 845, n = "Black Chocobo Feather", w = 100, rank = 1 },
      { id = 690, n = "Elm Log", w = 100, rank = 1 },
      { id = 699, n = "Oak Log", w = 50, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 10, rank = 3 },
      { id = 700, n = "Mahogany Log", w = 5, rank = 4 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
      { id = 720, n = "Piece of Ancient Lumber", w = 1, rank = 6 },
      { id = 1446, n = "Lacquer Tree Log", w = 1, rank = 7 },
    },
  } },
  [52] = { n = "Bhaflau Thickets", pools = {
    Treasure = {
      { id = 2488, n = "Piece of Alexandrite", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 100, rank = 0 },
      { id = 768, n = "Flint Stone", w = 100, rank = 0 },
      { id = 2213, n = "Handful of Pine Nuts", w = 50, rank = 0 },
      { id = 622, n = "Pinch of Dried Marjoram", w = 50, rank = 0 },
      { id = 2155, n = "Lesser Chigoe", w = 10, rank = 2 },
      { id = 2150, n = "Colibri Feather", w = 50, rank = 1 },
      { id = 838, n = "Spider Web", w = 10, rank = 4 },
      { id = 703, n = "Petrified Log", w = 50, rank = 3 },
      { id = 739, n = "Chunk of Orichalcum Ore", w = 5, rank = 7 },
    },
    Bore = {
      { id = 768, n = "Flint Stone", w = 240, rank = 0 },
      { id = 678, n = "Chunk of Aluminum Ore", w = 100, rank = 1 },
      { id = 737, n = "Chunk of Gold Ore", w = 50, rank = 2 },
      { id = 645, n = "Chunk of Darksteel Ore", w = 10, rank = 3 },
      { id = 2475, n = "Chunk of Kaolin", w = 10, rank = 3 },
      { id = 738, n = "Chunk of Platinum Ore", w = 5, rank = 5 },
      { id = 739, n = "Chunk of Orichalcum Ore", w = 1, rank = 6 },
    },
    Burrow = {
      { id = 833, n = "Clump of Moko Grass", w = 240, rank = 0 },
      { id = 688, n = "Arrowwood Log", w = 240, rank = 0 },
      { id = 2164, n = "Pephredo Hive Chip", w = 150, rank = 0 },
      { id = 696, n = "Yew Log", w = 150, rank = 0 },
      { id = 845, n = "Black Chocobo Feather", w = 100, rank = 1 },
      { id = 690, n = "Elm Log", w = 100, rank = 1 },
      { id = 699, n = "Oak Log", w = 50, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 10, rank = 3 },
      { id = 700, n = "Mahogany Log", w = 5, rank = 4 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
      { id = 720, n = "Piece of Ancient Lumber", w = 1, rank = 6 },
      { id = 1446, n = "Lacquer Tree Log", w = 1, rank = 7 },
    },
  } },
  [100] = { n = "West Ronfaure", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17396, n = "Little Worm", w = 50, rank = 0 },
      { id = 4504, n = "Acorn", w = 50, rank = 0 },
      { id = 833, n = "Clump of Moko Grass", w = 50, rank = 1 },
      { id = 688, n = "Arrowwood Log", w = 50, rank = 0 },
      { id = 691, n = "Maple Log", w = 50, rank = 1 },
      { id = 698, n = "Ash Log", w = 50, rank = 1 },
      { id = 694, n = "Chestnut Log", w = 10, rank = 2 },
      { id = 840, n = "Chocobo Feather", w = 50, rank = 2 },
      { id = 573, n = "Bag of Vegetable Seeds", w = 10, rank = 3 },
      { id = 639, n = "Ronfaure Chestnut", w = 10, rank = 3 },
      { id = 918, n = "Sprig of Mistletoe", w = 10, rank = 3 },
    },
    Bore = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
    Burrow = {
      { id = 4545, n = "Bunch of Gysahl Greens", w = 150, rank = 0 },
      { id = 636, n = "Sprig of Chamomile", w = 50, rank = 0 },
      { id = 617, n = "Ginger Root", w = 50, rank = 1 },
      { id = 5235, n = "Head of Napa", w = 50, rank = 2 },
    },
  } },
  [101] = { n = "East Ronfaure", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17396, n = "Little Worm", w = 50, rank = 0 },
      { id = 4504, n = "Acorn", w = 50, rank = 0 },
      { id = 688, n = "Arrowwood Log", w = 50, rank = 0 },
      { id = 691, n = "Maple Log", w = 50, rank = 1 },
      { id = 698, n = "Ash Log", w = 50, rank = 1 },
      { id = 694, n = "Chestnut Log", w = 10, rank = 2 },
      { id = 574, n = "Bag of Fruit Seeds", w = 10, rank = 2 },
      { id = 639, n = "Ronfaure Chestnut", w = 10, rank = 3 },
      { id = 840, n = "Chocobo Feather", w = 50, rank = 3 },
      { id = 918, n = "Sprig of Mistletoe", w = 10, rank = 4 },
      { id = 4386, n = "King Truffle", w = 10, rank = 7 },
    },
    Bore = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
    Burrow = {
      { id = 4545, n = "Bunch of Gysahl Greens", w = 150, rank = 0 },
      { id = 636, n = "Sprig of Chamomile", w = 50, rank = 0 },
      { id = 617, n = "Ginger Root", w = 50, rank = 1 },
      { id = 5235, n = "Head of Napa", w = 50, rank = 2 },
    },
  } },
  [102] = { n = "La Theine Plateau", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2605, n = "Coin of Glory", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 17396, n = "Little Worm", w = 50, rank = 0 },
      { id = 840, n = "Chocobo Feather", w = 50, rank = 1 },
      { id = 641, n = "Chunk of Tin Ore", w = 50, rank = 0 },
      { id = 642, n = "Chunk of Zinc Ore", w = 50, rank = 1 },
      { id = 688, n = "Arrowwood Log", w = 50, rank = 0 },
      { id = 696, n = "Yew Log", w = 50, rank = 1 },
      { id = 694, n = "Chestnut Log", w = 10, rank = 2 },
      { id = 700, n = "Mahogany Log", w = 10, rank = 3 },
      { id = 622, n = "Pinch of Dried Marjoram", w = 10, rank = 4 },
    },
    Bore = {
      { id = 2364, n = "Piece of Yellow Ginseng", w = 150, rank = 0 },
      { id = 2235, n = "Bag of Wildgrass Seeds", w = 50, rank = 1 },
      { id = 1237, n = "Bag of Tree Cuttings", w = 10, rank = 2 },
      { id = 1236, n = "Bag of Cactus Stems", w = 5, rank = 3 },
    },
    Burrow = {
      { id = 4545, n = "Bunch of Gysahl Greens", w = 150, rank = 0 },
      { id = 636, n = "Sprig of Chamomile", w = 50, rank = 0 },
      { id = 617, n = "Ginger Root", w = 50, rank = 1 },
      { id = 5235, n = "Head of Napa", w = 50, rank = 2 },
    },
  } },
  [103] = { n = "Valkurm Dunes", pools = {
    Treasure = {
      { id = 2606, n = "Coin of Decay", w = 5, rank = 8 },
      { id = 1452, n = "Ordelle Bronzepiece", w = 5, rank = 8 },
      { id = 1455, n = "One Byne Bill", w = 5, rank = 8 },
      { id = 1449, n = "Tukuku Whiteshell", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17395, n = "Lugworm", w = 50, rank = 0 },
      { id = 880, n = "Bone Chip", w = 100, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 50, rank = 1 },
      { id = 888, n = "Seashell", w = 150, rank = 1 },
      { id = 893, n = "Giant Femur", w = 50, rank = 3 },
      { id = 17397, n = "Shell Bug", w = 50, rank = 2 },
      { id = 869, n = "Lizard Molt", w = 50, rank = 3 },
      { id = 4484, n = "Shall Shell", w = 50, rank = 6 },
      { id = 885, n = "Turtle Shell", w = 50, rank = 7 },
    },
    Bore = {
      { id = 880, n = "Bone Chip", w = 150, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 150, rank = 0 },
      { id = 888, n = "Seashell", w = 150, rank = 1 },
      { id = 1587, n = "Handful of High-Quality Pugil Scales", w = 50, rank = 2 },
      { id = 1586, n = "Titanictus Shell", w = 50, rank = 4 },
      { id = 902, n = "Demon Horn", w = 10, rank = 5 },
      { id = 866, n = "Handful of Wyvern Scales", w = 5, rank = 6 },
      { id = 885, n = "Turtle Shell", w = 5, rank = 6 },
      { id = 886, n = "Demon Skull", w = 1, rank = 7 },
      { id = 867, n = "Handful of Dragon Scales", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 1845, n = "Clump of Red Moko Grass", w = 100, rank = 0 },
      { id = 845, n = "Black Chocobo Feather", w = 50, rank = 1 },
      { id = 838, n = "Spider Web", w = 5, rank = 3 },
      { id = 843, n = "Giant Bird Plume", w = 10, rank = 2 },
      { id = 844, n = "Phoenix Feather", w = 1, rank = 6 },
    },
  } },
  [104] = { n = "Jugner Forest", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2603, n = "Coin of Birth", w = 5, rank = 8 },
      { id = 4386, n = "King Truffle", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17396, n = "Little Worm", w = 50, rank = 0 },
      { id = 4504, n = "Acorn", w = 50, rank = 0 },
      { id = 691, n = "Maple Log", w = 50, rank = 1 },
      { id = 695, n = "Willow Log", w = 50, rank = 1 },
      { id = 697, n = "Holly Log", w = 50, rank = 3 },
      { id = 699, n = "Oak Log", w = 50, rank = 2 },
      { id = 918, n = "Sprig of Mistletoe", w = 10, rank = 3 },
      { id = 4447, n = "Scream Fungus", w = 5, rank = 6 },
    },
    Bore = {
      { id = 688, n = "Arrowwood Log", w = 240, rank = 0 },
      { id = 696, n = "Yew Log", w = 150, rank = 0 },
      { id = 690, n = "Elm Log", w = 100, rank = 1 },
      { id = 699, n = "Oak Log", w = 50, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 10, rank = 3 },
      { id = 700, n = "Mahogany Log", w = 5, rank = 4 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
      { id = 720, n = "Piece of Ancient Lumber", w = 1, rank = 6 },
      { id = 1446, n = "Lacquer Tree Log", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
  } },
  [105] = { n = "Batallia Downs", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2604, n = "Coin of Advancement", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 768, n = "Flint Stone", w = 50, rank = 0 },
      { id = 880, n = "Bone Chip", w = 50, rank = 0 },
      { id = 640, n = "Chunk of Copper Ore", w = 50, rank = 1 },
      { id = 847, n = "Bird Feather", w = 50, rank = 1 },
      { id = 643, n = "Chunk of Iron Ore", w = 50, rank = 2 },
      { id = 106, n = "Red Jar", w = 50, rank = 3 },
      { id = 845, n = "Black Chocobo Feather", w = 5, rank = 4 },
      { id = 4449, n = "Reishi Mushroom", w = 5, rank = 5 },
    },
    Bore = {
      { id = 2364, n = "Piece of Yellow Ginseng", w = 150, rank = 0 },
      { id = 2235, n = "Bag of Wildgrass Seeds", w = 50, rank = 1 },
      { id = 1237, n = "Bag of Tree Cuttings", w = 10, rank = 2 },
      { id = 1236, n = "Bag of Cactus Stems", w = 5, rank = 3 },
    },
    Burrow = {
      { id = 656, n = "Beastcoin", w = 100, rank = 0 },
      { id = 750, n = "Silver Beastcoin", w = 50, rank = 1 },
      { id = 748, n = "Gold Beastcoin", w = 10, rank = 2 },
      { id = 749, n = "Mythril Beastcoin", w = 5, rank = 3 },
      { id = 751, n = "Platinum Beastcoin", w = 1, rank = 4 },
    },
  } },
  [106] = { n = "North Gustaberg", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2605, n = "Coin of Glory", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 17396, n = "Little Worm", w = 50, rank = 0 },
      { id = 880, n = "Bone Chip", w = 50, rank = 0 },
      { id = 847, n = "Bird Feather", w = 50, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 50, rank = 0 },
      { id = 846, n = "Insect Wing", w = 50, rank = 0 },
      { id = 1236, n = "Bag of Cactus Stems", w = 10, rank = 1 },
      { id = 869, n = "Lizard Molt", w = 50, rank = 1 },
      { id = 749, n = "Mythril Beastcoin", w = 10, rank = 4 },
      { id = 644, n = "Chunk of Mythril Ore", w = 10, rank = 4 },
      { id = 645, n = "Chunk of Darksteel Ore", w = 10, rank = 7 },
    },
    Bore = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
    Burrow = {
      { id = 4545, n = "Bunch of Gysahl Greens", w = 150, rank = 0 },
      { id = 636, n = "Sprig of Chamomile", w = 50, rank = 0 },
      { id = 617, n = "Ginger Root", w = 50, rank = 1 },
      { id = 5235, n = "Head of Napa", w = 50, rank = 2 },
    },
  } },
  [107] = { n = "South Gustaberg", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2606, n = "Coin of Decay", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 17396, n = "Little Worm", w = 50, rank = 0 },
      { id = 880, n = "Bone Chip", w = 50, rank = 0 },
      { id = 847, n = "Bird Feather", w = 50, rank = 0 },
      { id = 936, n = "Chunk of Rock Salt", w = 50, rank = 0 },
      { id = 846, n = "Insect Wing", w = 50, rank = 0 },
      { id = 575, n = "Bag of Grain Seeds", w = 50, rank = 1 },
      { id = 869, n = "Lizard Molt", w = 50, rank = 1 },
      { id = 749, n = "Mythril Beastcoin", w = 50, rank = 4 },
      { id = 644, n = "Chunk of Mythril Ore", w = 10, rank = 4 },
    },
    Bore = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
    Burrow = {
      { id = 4545, n = "Bunch of Gysahl Greens", w = 150, rank = 0 },
      { id = 636, n = "Sprig of Chamomile", w = 50, rank = 0 },
      { id = 617, n = "Ginger Root", w = 50, rank = 1 },
      { id = 5235, n = "Head of Napa", w = 50, rank = 2 },
    },
  } },
  [108] = { n = "Konschtat Highlands", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2603, n = "Coin of Birth", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 768, n = "Flint Stone", w = 50, rank = 0 },
      { id = 880, n = "Bone Chip", w = 50, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 50, rank = 0 },
      { id = 642, n = "Chunk of Zinc Ore", w = 50, rank = 0 },
      { id = 847, n = "Bird Feather", w = 10, rank = 1 },
      { id = 869, n = "Lizard Molt", w = 50, rank = 1 },
      { id = 749, n = "Mythril Beastcoin", w = 5, rank = 4 },
      { id = 690, n = "Elm Log", w = 5, rank = 4 },
    },
    Bore = {
      { id = 1845, n = "Clump of Red Moko Grass", w = 100, rank = 0 },
      { id = 845, n = "Black Chocobo Feather", w = 50, rank = 1 },
      { id = 838, n = "Spider Web", w = 5, rank = 3 },
      { id = 843, n = "Giant Bird Plume", w = 10, rank = 2 },
      { id = 844, n = "Phoenix Feather", w = 1, rank = 6 },
    },
    Burrow = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
  } },
  [109] = { n = "Pashhow Marshlands", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2604, n = "Coin of Advancement", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 846, n = "Insect Wing", w = 50, rank = 0 },
      { id = 869, n = "Lizard Molt", w = 50, rank = 1 },
      { id = 736, n = "Chunk of Silver Ore", w = 50, rank = 1 },
      { id = 749, n = "Mythril Beastcoin", w = 10, rank = 2 },
      { id = 885, n = "Turtle Shell", w = 10, rank = 2 },
      { id = 695, n = "Willow Log", w = 10, rank = 2 },
      { id = 703, n = "Petrified Log", w = 5, rank = 3 },
      { id = 4448, n = "Puffball", w = 5, rank = 4 },
    },
    Bore = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
    Burrow = {
      { id = 2364, n = "Piece of Yellow Ginseng", w = 150, rank = 0 },
      { id = 2235, n = "Bag of Wildgrass Seeds", w = 50, rank = 1 },
      { id = 1237, n = "Bag of Tree Cuttings", w = 10, rank = 2 },
      { id = 1236, n = "Bag of Cactus Stems", w = 5, rank = 3 },
    },
  } },
  [110] = { n = "Rolanberry Fields", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2605, n = "Coin of Glory", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 100, rank = 0 },
      { id = 17396, n = "Little Worm", w = 100, rank = 0 },
      { id = 768, n = "Flint Stone", w = 100, rank = 0 },
      { id = 846, n = "Insect Wing", w = 50, rank = 1 },
      { id = 749, n = "Mythril Beastcoin", w = 10, rank = 2 },
      { id = 638, n = "Sprig of Sage", w = 10, rank = 2 },
      { id = 106, n = "Red Jar", w = 10, rank = 3 },
      { id = 748, n = "Gold Beastcoin", w = 5, rank = 6 },
      { id = 739, n = "Chunk of Orichalcum Ore", w = 5, rank = 6 },
    },
    Bore = {
      { id = 4566, n = "Deathball", w = 100, rank = 0 },
      { id = 4374, n = "Sleepshroom", w = 100, rank = 0 },
      { id = 4450, n = "Coral Fungus", w = 50, rank = 1 },
      { id = 4373, n = "Woozyshroom", w = 10, rank = 2 },
      { id = 4448, n = "Puffball", w = 10, rank = 3 },
      { id = 4375, n = "Danceshroom", w = 5, rank = 4 },
      { id = 4449, n = "Reishi Mushroom", w = 1, rank = 5 },
      { id = 4386, n = "King Truffle", w = 1, rank = 6 },
    },
    Burrow = {
      { id = 1845, n = "Clump of Red Moko Grass", w = 100, rank = 0 },
      { id = 845, n = "Black Chocobo Feather", w = 50, rank = 1 },
      { id = 838, n = "Spider Web", w = 5, rank = 3 },
      { id = 843, n = "Giant Bird Plume", w = 10, rank = 2 },
      { id = 844, n = "Phoenix Feather", w = 1, rank = 6 },
    },
  } },
  [114] = { n = "Eastern Altepa Desert", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
    },
    Regular = {
      { id = 768, n = "Flint Stone", w = 240, rank = 0 },
      { id = 880, n = "Bone Chip", w = 100, rank = 0 },
      { id = 17296, n = "Pebble", w = 50, rank = 1 },
      { id = 642, n = "Chunk of Zinc Ore", w = 50, rank = 1 },
      { id = 736, n = "Chunk of Silver Ore", w = 50, rank = 2 },
      { id = 893, n = "Giant Femur", w = 50, rank = 3 },
      { id = 866, n = "Handful of Wyvern Scales", w = 50, rank = 4 },
      { id = 644, n = "Chunk of Mythril Ore", w = 10, rank = 5 },
      { id = 738, n = "Chunk of Platinum Ore", w = 10, rank = 5 },
      { id = 942, n = "Philosophers Stone", w = 5, rank = 6 },
    },
    Bore = {
      { id = 768, n = "Flint Stone", w = 240, rank = 0 },
      { id = 678, n = "Chunk of Aluminum Ore", w = 100, rank = 1 },
      { id = 737, n = "Chunk of Gold Ore", w = 50, rank = 2 },
      { id = 645, n = "Chunk of Darksteel Ore", w = 10, rank = 3 },
      { id = 646, n = "Chunk of Adaman Ore", w = 5, rank = 5 },
      { id = 738, n = "Chunk of Platinum Ore", w = 5, rank = 5 },
      { id = 739, n = "Chunk of Orichalcum Ore", w = 1, rank = 6 },
    },
    Burrow = {
      { id = 575, n = "Bag of Grain Seeds", w = 50, rank = 0 },
      { id = 573, n = "Bag of Vegetable Seeds", w = 50, rank = 1 },
      { id = 572, n = "Bag of Herb Seeds", w = 50, rank = 2 },
      { id = 2235, n = "Bag of Wildgrass Seeds", w = 50, rank = 3 },
      { id = 574, n = "Bag of Fruit Seeds", w = 50, rank = 4 },
      { id = 1237, n = "Bag of Tree Cuttings", w = 10, rank = 5 },
      { id = 1236, n = "Bag of Cactus Stems", w = 10, rank = 6 },
    },
  } },
  [115] = { n = "West Sarutabaruta", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2606, n = "Coin of Decay", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 17396, n = "Little Worm", w = 50, rank = 0 },
      { id = 833, n = "Clump of Moko Grass", w = 50, rank = 1 },
      { id = 689, n = "Lauan Log", w = 50, rank = 1 },
      { id = 846, n = "Insect Wing", w = 50, rank = 1 },
      { id = 841, n = "Yagudo Feather", w = 50, rank = 2 },
      { id = 847, n = "Bird Feather", w = 10, rank = 2 },
      { id = 834, n = "Ball of Saruta Cotton", w = 10, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 5, rank = 3 },
    },
    Bore = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
    Burrow = {
      { id = 4545, n = "Bunch of Gysahl Greens", w = 150, rank = 0 },
      { id = 636, n = "Sprig of Chamomile", w = 50, rank = 0 },
      { id = 617, n = "Ginger Root", w = 50, rank = 1 },
      { id = 5235, n = "Head of Napa", w = 50, rank = 2 },
    },
  } },
  [116] = { n = "East Sarutabaruta", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 938, n = "Sprig of Papaka Grass", w = 50, rank = 0 },
      { id = 689, n = "Lauan Log", w = 50, rank = 0 },
      { id = 846, n = "Insect Wing", w = 50, rank = 1 },
      { id = 841, n = "Yagudo Feather", w = 50, rank = 1 },
      { id = 834, n = "Ball of Saruta Cotton", w = 50, rank = 1 },
      { id = 572, n = "Bag of Herb Seeds", w = 50, rank = 2 },
      { id = 847, n = "Bird Feather", w = 10, rank = 2 },
      { id = 702, n = "Ebony Log", w = 10, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 5, rank = 3 },
    },
    Bore = {
      { id = 4096, n = "Fire Crystal", w = 50, rank = 0 },
      { id = 4097, n = "Ice Crystal", w = 50, rank = 0 },
      { id = 4098, n = "Wind Crystal", w = 50, rank = 0 },
      { id = 4099, n = "Earth Crystal", w = 50, rank = 0 },
      { id = 4100, n = "Lightning Crystal", w = 50, rank = 0 },
      { id = 4101, n = "Water Crystal", w = 50, rank = 0 },
      { id = 4102, n = "Light Crystal", w = 50, rank = 0 },
      { id = 4103, n = "Dark Crystal", w = 50, rank = 0 },
    },
    Burrow = {
      { id = 4545, n = "Bunch of Gysahl Greens", w = 150, rank = 0 },
      { id = 636, n = "Sprig of Chamomile", w = 50, rank = 0 },
      { id = 617, n = "Ginger Root", w = 50, rank = 1 },
      { id = 5235, n = "Head of Napa", w = 50, rank = 2 },
    },
  } },
  [117] = { n = "Tahrongi Canyon", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2604, n = "Coin of Advancement", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 50, rank = 0 },
      { id = 880, n = "Bone Chip", w = 50, rank = 0 },
      { id = 888, n = "Seashell", w = 50, rank = 1 },
      { id = 641, n = "Chunk of Tin Ore", w = 50, rank = 1 },
      { id = 893, n = "Giant Femur", w = 50, rank = 2 },
      { id = 846, n = "Insect Wing", w = 50, rank = 2 },
      { id = 841, n = "Yagudo Feather", w = 50, rank = 3 },
      { id = 748, n = "Gold Beastcoin", w = 10, rank = 4 },
      { id = 737, n = "Chunk of Gold Ore", w = 10, rank = 4 },
    },
    Bore = {
      { id = 880, n = "Bone Chip", w = 150, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 150, rank = 0 },
      { id = 888, n = "Seashell", w = 150, rank = 1 },
      { id = 1587, n = "Handful of High-Quality Pugil Scales", w = 50, rank = 2 },
      { id = 1586, n = "Titanictus Shell", w = 50, rank = 4 },
      { id = 902, n = "Demon Horn", w = 10, rank = 5 },
      { id = 866, n = "Handful of Wyvern Scales", w = 5, rank = 6 },
      { id = 885, n = "Turtle Shell", w = 5, rank = 6 },
      { id = 886, n = "Demon Skull", w = 1, rank = 7 },
      { id = 867, n = "Handful of Dragon Scales", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 656, n = "Beastcoin", w = 100, rank = 0 },
      { id = 750, n = "Silver Beastcoin", w = 50, rank = 1 },
      { id = 748, n = "Gold Beastcoin", w = 10, rank = 2 },
      { id = 749, n = "Mythril Beastcoin", w = 5, rank = 3 },
      { id = 751, n = "Platinum Beastcoin", w = 1, rank = 4 },
    },
  } },
  [118] = { n = "Buburimu Peninsula", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2603, n = "Coin of Birth", w = 5, rank = 8 },
      { id = 1452, n = "Ordelle Bronzepiece", w = 5, rank = 8 },
      { id = 1455, n = "One Byne Bill", w = 5, rank = 8 },
      { id = 1449, n = "Tukuku Whiteshell", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17395, n = "Lugworm", w = 100, rank = 0 },
      { id = 17397, n = "Shell Bug", w = 100, rank = 0 },
      { id = 888, n = "Seashell", w = 100, rank = 0 },
      { id = 4484, n = "Shall Shell", w = 50, rank = 1 },
      { id = 847, n = "Bird Feather", w = 50, rank = 1 },
      { id = 641, n = "Chunk of Tin Ore", w = 10, rank = 2 },
      { id = 893, n = "Giant Femur", w = 10, rank = 2 },
      { id = 738, n = "Chunk of Platinum Ore", w = 5, rank = 4 },
      { id = 887, n = "Coral Fragment", w = 5, rank = 6 },
    },
    Bore = {
      { id = 880, n = "Bone Chip", w = 150, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 150, rank = 0 },
      { id = 888, n = "Seashell", w = 150, rank = 1 },
      { id = 1587, n = "Handful of High-Quality Pugil Scales", w = 50, rank = 2 },
      { id = 1586, n = "Titanictus Shell", w = 50, rank = 4 },
      { id = 902, n = "Demon Horn", w = 10, rank = 5 },
      { id = 866, n = "Handful of Wyvern Scales", w = 5, rank = 6 },
      { id = 885, n = "Turtle Shell", w = 5, rank = 6 },
      { id = 886, n = "Demon Skull", w = 1, rank = 7 },
      { id = 867, n = "Handful of Dragon Scales", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 1845, n = "Clump of Red Moko Grass", w = 100, rank = 0 },
      { id = 845, n = "Black Chocobo Feather", w = 50, rank = 1 },
      { id = 838, n = "Spider Web", w = 5, rank = 3 },
      { id = 843, n = "Giant Bird Plume", w = 10, rank = 2 },
      { id = 844, n = "Phoenix Feather", w = 1, rank = 6 },
    },
  } },
  [119] = { n = "Meriphataud Mountains", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2604, n = "Coin of Advancement", w = 5, rank = 8 },
    },
    Regular = {
      { id = 768, n = "Flint Stone", w = 240, rank = 0 },
      { id = 17296, n = "Pebble", w = 100, rank = 0 },
      { id = 640, n = "Chunk of Copper Ore", w = 50, rank = 1 },
      { id = 893, n = "Giant Femur", w = 50, rank = 1 },
      { id = 869, n = "Lizard Molt", w = 50, rank = 2 },
      { id = 845, n = "Black Chocobo Feather", w = 10, rank = 3 },
      { id = 748, n = "Gold Beastcoin", w = 10, rank = 4 },
      { id = 646, n = "Chunk of Adaman Ore", w = 5, rank = 5 },
    },
    Bore = {
      { id = 768, n = "Flint Stone", w = 240, rank = 0 },
      { id = 678, n = "Chunk of Aluminum Ore", w = 100, rank = 1 },
      { id = 737, n = "Chunk of Gold Ore", w = 50, rank = 2 },
      { id = 645, n = "Chunk of Darksteel Ore", w = 10, rank = 3 },
      { id = 646, n = "Chunk of Adaman Ore", w = 5, rank = 5 },
      { id = 738, n = "Chunk of Platinum Ore", w = 5, rank = 5 },
      { id = 739, n = "Chunk of Orichalcum Ore", w = 1, rank = 6 },
    },
    Burrow = {
      { id = 736, n = "Chunk of Silver Ore", w = 100, rank = 0 },
      { id = 643, n = "Chunk of Iron Ore", w = 100, rank = 1 },
      { id = 1650, n = "Chunk of Kopparnickel Ore", w = 100, rank = 1 },
      { id = 644, n = "Chunk of Mythril Ore", w = 100, rank = 1 },
      { id = 645, n = "Chunk of Darksteel Ore", w = 10, rank = 3 },
    },
  } },
  [120] = { n = "Sauromugue Champaign", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2605, n = "Coin of Glory", w = 5, rank = 8 },
    },
    Regular = {
      { id = 768, n = "Flint Stone", w = 240, rank = 0 },
      { id = 17296, n = "Pebble", w = 100, rank = 0 },
      { id = 880, n = "Bone Chip", w = 100, rank = 0 },
      { id = 846, n = "Insect Wing", w = 50, rank = 1 },
      { id = 869, n = "Lizard Molt", w = 50, rank = 1 },
      { id = 643, n = "Chunk of Iron Ore", w = 50, rank = 2 },
      { id = 845, n = "Black Chocobo Feather", w = 10, rank = 3 },
      { id = 106, n = "Red Jar", w = 10, rank = 3 },
      { id = 748, n = "Gold Beastcoin", w = 5, rank = 4 },
    },
    Bore = {
      { id = 880, n = "Bone Chip", w = 150, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 150, rank = 0 },
      { id = 888, n = "Seashell", w = 150, rank = 1 },
      { id = 1587, n = "Handful of High-Quality Pugil Scales", w = 50, rank = 2 },
      { id = 1586, n = "Titanictus Shell", w = 50, rank = 4 },
      { id = 902, n = "Demon Horn", w = 10, rank = 5 },
      { id = 866, n = "Handful of Wyvern Scales", w = 5, rank = 6 },
      { id = 885, n = "Turtle Shell", w = 5, rank = 6 },
      { id = 886, n = "Demon Skull", w = 1, rank = 7 },
      { id = 867, n = "Handful of Dragon Scales", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 656, n = "Beastcoin", w = 100, rank = 0 },
      { id = 750, n = "Silver Beastcoin", w = 50, rank = 1 },
      { id = 748, n = "Gold Beastcoin", w = 10, rank = 2 },
      { id = 749, n = "Mythril Beastcoin", w = 5, rank = 3 },
      { id = 751, n = "Platinum Beastcoin", w = 1, rank = 4 },
    },
  } },
  [121] = { n = "The Sanctuary of ZiTah", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
      { id = 2606, n = "Coin of Decay", w = 5, rank = 8 },
    },
    Regular = {
      { id = 17296, n = "Pebble", w = 100, rank = 0 },
      { id = 833, n = "Clump of Moko Grass", w = 100, rank = 0 },
      { id = 880, n = "Bone Chip", w = 100, rank = 0 },
      { id = 688, n = "Arrowwood Log", w = 50, rank = 1 },
      { id = 696, n = "Yew Log", w = 50, rank = 1 },
      { id = 690, n = "Elm Log", w = 50, rank = 2 },
      { id = 4386, n = "King Truffle", w = 5, rank = 3 },
      { id = 703, n = "Petrified Log", w = 5, rank = 4 },
    },
    Bore = {
      { id = 688, n = "Arrowwood Log", w = 240, rank = 0 },
      { id = 696, n = "Yew Log", w = 150, rank = 0 },
      { id = 690, n = "Elm Log", w = 100, rank = 1 },
      { id = 699, n = "Oak Log", w = 50, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 10, rank = 3 },
      { id = 700, n = "Mahogany Log", w = 5, rank = 4 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
      { id = 720, n = "Piece of Ancient Lumber", w = 1, rank = 6 },
      { id = 1446, n = "Lacquer Tree Log", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 656, n = "Beastcoin", w = 100, rank = 0 },
      { id = 750, n = "Silver Beastcoin", w = 50, rank = 1 },
      { id = 748, n = "Gold Beastcoin", w = 10, rank = 2 },
      { id = 749, n = "Mythril Beastcoin", w = 5, rank = 3 },
      { id = 751, n = "Platinum Beastcoin", w = 1, rank = 4 },
    },
  } },
  [123] = { n = "Yuhtunga Jungle", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
    },
    Regular = {
      { id = 880, n = "Bone Chip", w = 100, rank = 0 },
      { id = 4375, n = "Danceshroom", w = 100, rank = 0 },
      { id = 628, n = "Stick of Cinnamon", w = 50, rank = 1 },
      { id = 721, n = "Piece of Rattan Lumber", w = 50, rank = 1 },
      { id = 701, n = "Rosewood Log", w = 50, rank = 2 },
      { id = 4448, n = "Puffball", w = 50, rank = 2 },
      { id = 703, n = "Petrified Log", w = 10, rank = 3 },
      { id = 4386, n = "King Truffle", w = 10, rank = 3 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
    },
    Bore = {
      { id = 688, n = "Arrowwood Log", w = 240, rank = 0 },
      { id = 696, n = "Yew Log", w = 150, rank = 0 },
      { id = 690, n = "Elm Log", w = 100, rank = 1 },
      { id = 699, n = "Oak Log", w = 50, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 10, rank = 3 },
      { id = 700, n = "Mahogany Log", w = 5, rank = 4 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
      { id = 720, n = "Piece of Ancient Lumber", w = 1, rank = 6 },
      { id = 1446, n = "Lacquer Tree Log", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 4566, n = "Deathball", w = 100, rank = 0 },
      { id = 4374, n = "Sleepshroom", w = 100, rank = 0 },
      { id = 4450, n = "Coral Fungus", w = 50, rank = 1 },
      { id = 4373, n = "Woozyshroom", w = 10, rank = 2 },
      { id = 4448, n = "Puffball", w = 10, rank = 3 },
      { id = 4375, n = "Danceshroom", w = 5, rank = 4 },
      { id = 4449, n = "Reishi Mushroom", w = 1, rank = 5 },
      { id = 4386, n = "King Truffle", w = 1, rank = 6 },
    },
  } },
  [124] = { n = "Yhoator Jungle", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
    },
    Regular = {
      { id = 880, n = "Bone Chip", w = 100, rank = 0 },
      { id = 4432, n = "Kazham Pineapple", w = 50, rank = 0 },
      { id = 689, n = "Lauan Log", w = 50, rank = 0 },
      { id = 700, n = "Mahogany Log", w = 50, rank = 1 },
      { id = 923, n = "Dryad Root", w = 50, rank = 1 },
      { id = 4449, n = "Reishi Mushroom", w = 10, rank = 1 },
      { id = 4450, n = "Coral Fungus", w = 10, rank = 3 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
    },
    Bore = {
      { id = 688, n = "Arrowwood Log", w = 240, rank = 0 },
      { id = 696, n = "Yew Log", w = 150, rank = 0 },
      { id = 690, n = "Elm Log", w = 100, rank = 1 },
      { id = 699, n = "Oak Log", w = 50, rank = 2 },
      { id = 701, n = "Rosewood Log", w = 10, rank = 3 },
      { id = 700, n = "Mahogany Log", w = 5, rank = 4 },
      { id = 702, n = "Ebony Log", w = 5, rank = 5 },
      { id = 720, n = "Piece of Ancient Lumber", w = 1, rank = 6 },
      { id = 1446, n = "Lacquer Tree Log", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 4566, n = "Deathball", w = 100, rank = 0 },
      { id = 4374, n = "Sleepshroom", w = 100, rank = 0 },
      { id = 4450, n = "Coral Fungus", w = 50, rank = 1 },
      { id = 4373, n = "Woozyshroom", w = 10, rank = 2 },
      { id = 4448, n = "Puffball", w = 10, rank = 3 },
      { id = 4375, n = "Danceshroom", w = 5, rank = 4 },
      { id = 4449, n = "Reishi Mushroom", w = 1, rank = 5 },
      { id = 4386, n = "King Truffle", w = 1, rank = 6 },
    },
  } },
  [125] = { n = "Western Altepa Desert", pools = {
    Treasure = {
      { id = 3509, n = "Plate of Heavy Metal", w = 5, rank = 8 },
    },
    Regular = {
      { id = 880, n = "Bone Chip", w = 240, rank = 0 },
      { id = 17296, n = "Pebble", w = 150, rank = 0 },
      { id = 642, n = "Chunk of Zinc Ore", w = 100, rank = 1 },
      { id = 893, n = "Giant Femur", w = 100, rank = 1 },
      { id = 643, n = "Chunk of Iron Ore", w = 50, rank = 2 },
      { id = 645, n = "Chunk of Darksteel Ore", w = 10, rank = 3 },
      { id = 737, n = "Chunk of Gold Ore", w = 10, rank = 3 },
      { id = 887, n = "Coral Fragment", w = 5, rank = 4 },
      { id = 942, n = "Philosophers Stone", w = 5, rank = 4 },
    },
    Bore = {
      { id = 880, n = "Bone Chip", w = 150, rank = 0 },
      { id = 864, n = "Handful of Fish Scales", w = 150, rank = 0 },
      { id = 888, n = "Seashell", w = 150, rank = 1 },
      { id = 1587, n = "Handful of High-Quality Pugil Scales", w = 50, rank = 2 },
      { id = 1586, n = "Titanictus Shell", w = 50, rank = 4 },
      { id = 902, n = "Demon Horn", w = 10, rank = 5 },
      { id = 866, n = "Handful of Wyvern Scales", w = 5, rank = 6 },
      { id = 885, n = "Turtle Shell", w = 5, rank = 6 },
      { id = 886, n = "Demon Skull", w = 1, rank = 7 },
      { id = 867, n = "Handful of Dragon Scales", w = 1, rank = 7 },
    },
    Burrow = {
      { id = 1845, n = "Clump of Red Moko Grass", w = 100, rank = 0 },
      { id = 845, n = "Black Chocobo Feather", w = 50, rank = 1 },
      { id = 838, n = "Spider Web", w = 5, rank = 3 },
      { id = 843, n = "Giant Bird Plume", w = 10, rank = 2 },
      { id = 844, n = "Phoenix Feather", w = 1, rank = 6 },
    },
  } },
},

-- ---------------------------------------------------------------------------
-- Conditional Regular-pool drops, as static rule tables (maps + gates). These
-- layer onto the Regular pool when their condition is live. The three sources
-- and their gates are encoded here so digcalc / the panel can mark each one
-- active or inactive against the live Vana'diel clock.
-- ---------------------------------------------------------------------------
cond = {

  -- Weather crystals/clusters: the current weather's element yields that
  -- element's crystal (~10% in any digging zone, no rank gate); double weather
  -- yields the cluster instead. byElement maps the 8 elements to the standard
  -- FFXI crystal/cluster item ids. Weather element -> crystal is a pure lookup;
  -- the panel resolves the live weather element to the row.
  crystals = {
    chance  = 10,     -- ~10% per dig, any digging zone
    minRank = 0,      -- no rank requirement
    byElement = {
      Fire      = { crystal = 4096, cluster = 4104 },
      Ice       = { crystal = 4097, cluster = 4105 },
      Wind      = { crystal = 4098, cluster = 4106 },
      Earth     = { crystal = 4099, cluster = 4107 },
      Lightning = { crystal = 4100, cluster = 4108 },
      Water     = { crystal = 4101, cluster = 4109 },
      Light     = { crystal = 4102, cluster = 4110 },
      Dark      = { crystal = 4103, cluster = 4111 },
    },
  },

  -- Day rocks: the current Vana'diel day's element yields that element's rock
  -- (~5% in any digging zone, requires dig rank >= Novice). byDay maps the 8
  -- Vana'diel days to their element; byElement carries the concrete rock item
  -- id/name PER ELEMENT -- RESOLVED BY THE GENERATOR from the server's item
  -- constants (empty here; see DATA STATUS). The day->element map + the gate
  -- are the stable, well-formed part.
  rocks = {
    chance  = 5,      -- ~5% per dig, any digging zone
    minRank = 3,      -- >= Novice
    byDay = {
      Firesday     = "Fire",
      Iceday       = "Ice",
      Windsday     = "Wind",
      Earthsday    = "Earth",
      Lightningday = "Lightning",
      Watersday    = "Water",
      Lightsday    = "Light",
      Darksday     = "Dark",
    },
    byElement = {
      Fire      = { id = 769, n = "Red Rock" },
      Ice       = { id = 773, n = "Translucent Rock" },
      Wind      = { id = 772, n = "Green Rock" },
      Earth     = { id = 771, n = "Yellow Rock" },
      Lightning = { id = 774, n = "Purple Rock" },
      Water     = { id = 770, n = "Blue Rock" },
      Light     = { id = 776, n = "White Rock" },
      Dark      = { id = 775, n = "Black Rock" },
    },
  },

  -- Day ores: the current day's element yields that element's ore, but only
  -- under the full gate -- dig rank >= Craftsman, the matching elemental weather
  -- is up, the Vana'diel moon phase percent is within 7..21, and only in the 9 elemental-
  -- ore zones (~10% there). byDay maps day->element; byElement carries the ore
  -- item id/name per element (generated); zones is the elemental-ore zone set
  -- (generated). The maps + gate are the stable part.
  ores = {
    chance  = 10,     -- ~10% per dig, ore zones only
    minRank = 6,      -- >= Craftsman
    requiresElementalWeather = true,
    moonPhaseWindow = { min = 7, max = 21 },   -- moon phase percent (0-100, = VanadielMoonPhase) window
    byDay = {
      Firesday     = "Fire",
      Iceday       = "Ice",
      Windsday     = "Wind",
      Earthsday    = "Earth",
      Lightningday = "Lightning",
      Watersday    = "Water",
      Lightsday    = "Light",
      Darksday     = "Dark",
    },
    byElement = {
      Fire      = { id = 1255, n = "Chunk of Fire Ore" },
      Ice       = { id = 1256, n = "Chunk of Ice Ore" },
      Wind      = { id = 1257, n = "Chunk of Wind Ore" },
      Earth     = { id = 1258, n = "Chunk of Earth Ore" },
      Lightning = { id = 1259, n = "Chunk of Lightning Ore" },
      Water     = { id = 1260, n = "Chunk of Water Ore" },
      Light     = { id = 1261, n = "Chunk of Light Ore" },
      Dark      = { id = 1262, n = "Chunk of Dark Ore" },
    },
    zones = {
      [102] = true,
      [104] = true,
      [105] = true,
      [108] = true,
      [109] = true,
      [110] = true,
      [117] = true,
      [119] = true,
      [120] = true,
    },
  },

},

}
