-- digdata.lua -- the chocobo-digging database, to be GENERATED by
-- tools/gen_digdata.py from the CatsEyeXI server's chocobo-digging data
-- (following the gen_petmods.py / gen_zones.py pattern). Do not hand-edit the
-- generated sections; rebuild with:
--   python tools/gen_digdata.py      (maintainer only, ships with updates)
-- Loaded lazily and fails soft (feature/digcalc.lua M.db) -- a missing or
-- partial table disables the data-backed queries, never errors.
--
-- ===========================================================================
-- !! DATA STATUS (issue #94) !!  The per-zone loot pools below (`zones`) are
-- the CatsEyeXI-SPECIFIC part of the data: the 26 enabled digging zones, each
-- item's dig weight and rank requirement, grouped by pool. Those numbers live
-- ONLY in the server's private chocobo-digging source and MUST be populated by
-- running gen_digdata.py against that checkout (maintainer-only) BEFORE the
-- digging guide ships. Until then `zones` is empty and every by-zone query
-- fails soft. The odds engine (digcalc) is fully implemented and tested against
-- hand-computed pools independent of this table; the conditional rule tables
-- below are FFXI-standard and complete. See the PR for #94 for the hand-over.
-- ===========================================================================
--
-- Shapes (docs/design/chocobo-dig.md, PRD #93 / issue #94):
--   zones[zoneId] = { n = "Zone Name", pools = { <Pool> = { <item>, ... } } }
--     <Pool> in { "Treasure", "Regular", "Bore", "Burrow" } (server grant order)
--     <item> = { id = <itemId>, n = "English Name", w = <weight>, rank = <req> }
--       w    = dig weight (higher = more likely; digcalc: q = min(1, w/(1000*mu)))
--       rank = dig-rank requirement, index into `ranks` below (0 = Amateur)
--   cond = the conditional Regular-pool rule tables (maps + gates), below.
--   ranks = the 0..8 dig-rank ladder (index = rank number).

return {

-- The dig-rank ladder (0..8), matching the server's first-dig timing bracket
-- (60 - 5*rank seconds). PROPOSED player-facing labels -- pending maintainer
-- sign-off (issue #94 PR); the data foundation only needs the numeric ladder,
-- rock/ore gates reference it by index (Novice = 3, Craftsman = 6).
ranks = {
  [0] = "Amateur",
  [1] = "Recruit",
  [2] = "Initiate",
  [3] = "Novice",
  [4] = "Apprentice",
  [5] = "Journeyman",
  [6] = "Craftsman",
  [7] = "Artisan",
  [8] = "Adept",
},

-- The enabled digging zones + their loot pools. GENERATED (see DATA STATUS
-- above) -- empty until gen_digdata.py runs against the private source. The
-- generator emits exactly the 26 zones where digging is enabled on the server
-- (not the 58 that merely carry loot data).
zones = {
},

-- ---------------------------------------------------------------------------
-- Conditional Regular-pool drops, as static rule tables (maps + gates). These
-- layer onto the Regular pool when their condition is live. The three sources
-- and their gates are encoded here so digcalc / the panel can mark each one
-- active or inactive against the live Vana'diel clock.
-- ---------------------------------------------------------------------------
cond = {

  -- Weather crystals/clusters: the current weather's element yields that
  -- element's crystal (~10% in any digging zone, no rank gate); double weather
  -- yields the cluster instead. byElement maps the 8 elements to the standard
  -- FFXI crystal/cluster item ids. Weather element -> crystal is a pure lookup;
  -- the panel resolves the live weather element to the row.
  crystals = {
    chance  = 10,     -- ~10% per dig, any digging zone
    minRank = 0,      -- no rank requirement
    byElement = {
      Fire      = { crystal = 4096, cluster = 4104 },
      Ice       = { crystal = 4097, cluster = 4105 },
      Wind      = { crystal = 4098, cluster = 4106 },
      Earth     = { crystal = 4099, cluster = 4107 },
      Lightning = { crystal = 4100, cluster = 4108 },
      Water     = { crystal = 4101, cluster = 4109 },
      Light     = { crystal = 4102, cluster = 4110 },
      Dark      = { crystal = 4103, cluster = 4111 },
    },
  },

  -- Day rocks: the current Vana'diel day's element yields that element's rock
  -- (~5% in any digging zone, requires dig rank >= Novice). byDay maps the 8
  -- Vana'diel days to their element; byElement carries the concrete rock item
  -- id/name PER ELEMENT -- RESOLVED BY THE GENERATOR from the server's item
  -- constants (empty here; see DATA STATUS). The day->element map + the gate
  -- are the stable, well-formed part.
  rocks = {
    chance  = 5,      -- ~5% per dig, any digging zone
    minRank = 3,      -- >= Novice
    byDay = {
      Firesday     = "Fire",
      Iceday       = "Ice",
      Windsday     = "Wind",
      Earthsday    = "Earth",
      Lightningday = "Lightning",
      Watersday    = "Water",
      Lightsday    = "Light",
      Darksday     = "Dark",
    },
    byElement = {
      -- [element] = { id = <itemId>, n = "English Name" }  -- generated
    },
  },

  -- Day ores: the current day's element yields that element's ore, but only
  -- under the full gate -- dig rank >= Craftsman, the matching elemental weather
  -- is up, the Vana'diel moon day is within 7..21, and only in the 9 elemental-
  -- ore zones (~10% there). byDay maps day->element; byElement carries the ore
  -- item id/name per element (generated); zones is the elemental-ore zone set
  -- (generated). The maps + gate are the stable part.
  ores = {
    chance  = 10,     -- ~10% per dig, ore zones only
    minRank = 6,      -- >= Craftsman
    requiresElementalWeather = true,
    moonDays = { min = 7, max = 21 },   -- Vana'diel moon day window
    byDay = {
      Firesday     = "Fire",
      Iceday       = "Ice",
      Windsday     = "Wind",
      Earthsday    = "Earth",
      Lightningday = "Lightning",
      Watersday    = "Water",
      Lightsday    = "Light",
      Darksday     = "Dark",
    },
    byElement = {
      -- [element] = { id = <itemId>, n = "English Name" }  -- generated
    },
    zones = {
      -- [zoneId] = true  -- the 9 elemental-ore zones, generated
    },
  },

},

}
