-- dlac gear-set bonuses -- GENERATED by tools/gen_gearsets.py from the CatsEyeXI
-- server's scripts/globals/gear_sets.lua. pieces[] + value-at-count tiers
-- (replacement, not cumulative); active when count >= min; runtime picks
-- tiers[math.min(count, max)], nil below min. Piece lists may EXCEED max
-- (alternate pieces, weapons included); an item can belong to multiple sets.
-- Counting is per composition slot (two copies count twice) and level-gated --
-- see docs/design/conditional-effects.md #3.1/#7.2 and gear/geareffects.lua.
-- Do not hand-edit; re-run the generator instead.
return {
    [1] = {
        pieces = { 14554, 14969, 15633, 15719, 16092 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { Haste = 5 },
        },
    },
    [2] = {
        pieces = { 14550, 14965, 15629, 15715, 16088 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { CriticalHitRate = 5 },
        },
    },
    [3] = {
        pieces = { 14546, 14961, 15625, 15711, 16084 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { DoubleAttack = 5 },
        },
    },
    [4] = {
        pieces = { 14569, 14984, 15648, 15734, 16107 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { Accuracy = 20 },
        },
    },
    [5] = {
        pieces = { 14568, 14983, 15647, 15733, 16106 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { HPP = 10 },
        },
    },
    [6] = {
        pieces = { 14530, 14940, 15609, 15695, 16069 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { SubtleBlow = 8 },
        },
    },
    [7] = {
        pieces = { 14562, 14977, 15641, 15727, 16100 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { MagicAttackBonus = 5 },
        },
    },
    [8] = {
        pieces = { 14558, 14973, 15637, 15723, 16096 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { FastCast = 5 },
        },
    },
    [9] = {
        pieces = { 14570, 14985, 15649, 15735, 16108 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { MagicDefenseBonus = 10 },
        },
    },
    [10] = {
        pieces = { 14527, 14935, 15606, 15690, 16064 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { Refresh = 1 },
        },
    },
    [11] = {
        pieces = { 11413, 11503, 12745, 13759, 14210 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { Haste = 5 },
        },
    },
    [12] = {
        pieces = { 11414, 11504, 12746, 13760, 14257 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { StoreTP = 8 },
        },
    },
    [13] = {
        pieces = { 11415, 11505, 12747, 13778, 14258 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { FastCast = 4 },
            [3] = { FastCast = 6 },
            [4] = { FastCast = 8 },
            [5] = { FastCast = 10 },
        },
    },
    [14] = {
        pieces = { 10462, 10512, 10610, 10890, 11980 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { Haste = 6 },
        },
    },
    [15] = {
        pieces = { 10464, 10514, 10612, 10892, 11982 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { MagicAccuracy = 5 },
        },
    },
    [16] = {
        pieces = { 10463, 10513, 10611, 10891, 11981 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { CriticalHitRate = 5 },
        },
    },
    [17] = {
        pieces = { 15744, 16126 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { RangedAttack = 15 },
        },
    },
    [18] = {
        pieces = { 14589, 15010, 15756, 16147, 16316 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Attack = 1 },
            [3] = { Attack = 5 },
            [4] = { Attack = 10 },
            [5] = { Attack = 15 },
        },
    },
    [19] = {
        pieces = { 14590, 15011, 15757, 16148, 16317 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Counter = 1 },
            [3] = { Counter = 2 },
            [4] = { Counter = 3 },
            [5] = { Counter = 4 },
        },
    },
    [20] = {
        pieces = { 14591, 15012, 15758, 16149, 16318 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { MagicAccuracy = 1 },
            [3] = { MagicAccuracy = 2 },
            [4] = { MagicAccuracy = 3 },
            [5] = { MagicAccuracy = 4 },
        },
    },
    [21] = {
        pieces = { 14581, 15005, 15749, 16141, 16312 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 1, Attack = 1 },
            [3] = { Accuracy = 2, Attack = 2 },
            [4] = { Accuracy = 3, Attack = 3 },
            [5] = { Accuracy = 4, Attack = 4 },
        },
    },
    [22] = {
        pieces = { 14582, 15006, 15750, 16142, 16313 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { HP = 10 },
            [3] = { HP = 20 },
            [4] = { HP = 30 },
            [5] = { HP = 40 },
        },
    },
    [23] = {
        pieces = { 14583, 15007, 15751, 16143, 16314 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { MP = 10 },
            [3] = { MP = 20 },
            [4] = { MP = 30 },
            [5] = { MP = 40 },
        },
    },
    [24] = {
        pieces = { 14525, 14933, 15604, 15688, 16062 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { UDMGBREATH = -800, UDMGMAGIC = -800 },
        },
    },
    [25] = {
        pieces = { 11281, 11364, 15015, 16337 },
        min = 2,
        max = 4,
        tiers = {
            [2] = { StoreTP = 5 },
            [3] = { StoreTP = 10 },
            [4] = { StoreTP = 20 },
        },
    },
    [26] = {
        pieces = { 11064, 11084, 11104, 11124, 11144 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { DA_DOUBLE_DMG_RATE = 2 },
            [3] = { DA_DOUBLE_DMG_RATE = 3 },
            [4] = { DA_DOUBLE_DMG_RATE = 4 },
            [5] = { DA_DOUBLE_DMG_RATE = 5 },
        },
    },
    [27] = {
        pieces = { 11808, 11824, 11850, 11857, 11858 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { DoubleAttack = 5 },
        },
    },
    [28] = {
        pieces = { 11809, 11825, 11851, 11855, 11859 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { Haste = 8 },
        },
    },
    [29] = {
        pieces = { 11810, 11826, 11852, 11856, 11860 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { MagicAccuracy = 5 },
        },
    },
    [30] = {
        pieces = { 10450, 10500, 10600, 10876, 11969 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Refresh = 1 },
            [3] = { Refresh = 1 },
            [4] = { Refresh = 2 },
            [5] = { Refresh = 2 },
        },
    },
    [31] = {
        pieces = { 10451, 10501, 10601, 10877, 11970 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { CriticalHitRate = 3 },
            [3] = { CriticalHitRate = 4 },
            [4] = { CriticalHitRate = 5 },
            [5] = { CriticalHitRate = 6 },
        },
    },
    [32] = {
        pieces = { 10452, 10502, 10602, 10878, 11971 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { FastCast = 4 },
            [3] = { FastCast = 4 },
            [4] = { FastCast = 10 },
            [5] = { FastCast = 10 },
        },
    },
    [33] = {
        pieces = { 11080, 11100, 11120, 11140, 11160 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { QUICK_DRAW_TRIPLE_DAMAGE = 2 },
            [3] = { QUICK_DRAW_TRIPLE_DAMAGE = 3 },
            [4] = { QUICK_DRAW_TRIPLE_DAMAGE = 4 },
            [5] = { QUICK_DRAW_TRIPLE_DAMAGE = 5 },
        },
    },
    [34] = {
        pieces = { 11082, 11102, 11122, 11142, 11162 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { SAMBA_DOUBLE_DAMAGE = 2 },
            [3] = { SAMBA_DOUBLE_DAMAGE = 3 },
            [4] = { SAMBA_DOUBLE_DAMAGE = 4 },
            [5] = { SAMBA_DOUBLE_DAMAGE = 5 },
        },
    },
    [35] = {
        pieces = { 11076, 11096, 11116, 11136, 11156 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { EXTRA_DUAL_WIELD_ATTACK = 2 },
            [3] = { EXTRA_DUAL_WIELD_ATTACK = 3 },
            [4] = { EXTRA_DUAL_WIELD_ATTACK = 4 },
            [5] = { EXTRA_DUAL_WIELD_ATTACK = 5 },
        },
    },
    [36] = {
        pieces = { 11074, 11094, 11114, 11134, 11154 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { RAPID_SHOT_DOUBLE_DAMAGE = 2 },
            [3] = { RAPID_SHOT_DOUBLE_DAMAGE = 3 },
            [4] = { RAPID_SHOT_DOUBLE_DAMAGE = 4 },
            [5] = { RAPID_SHOT_DOUBLE_DAMAGE = 5 },
        },
    },
    [37] = {
        pieces = { 11070, 11090, 11110, 11130, 11150 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { AbsorbDamageChance = 2 },
            [3] = { AbsorbDamageChance = 3 },
            [4] = { AbsorbDamageChance = 4 },
            [5] = { AbsorbDamageChance = 5 },
        },
    },
    [38] = {
        pieces = { 11075, 11095, 11115, 11135, 11155 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { ZANSHIN_DOUBLE_DAMAGE = 2 },
            [3] = { ZANSHIN_DOUBLE_DAMAGE = 3 },
            [4] = { ZANSHIN_DOUBLE_DAMAGE = 4 },
            [5] = { ZANSHIN_DOUBLE_DAMAGE = 5 },
        },
    },
    [39] = {
        pieces = { 11065, 11085, 11105, 11125, 11145 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { EXTRA_KICK_ATTACK = 2 },
            [3] = { EXTRA_KICK_ATTACK = 3 },
            [4] = { EXTRA_KICK_ATTACK = 4 },
            [5] = { EXTRA_KICK_ATTACK = 5 },
        },
    },
    [40] = {
        pieces = { 11069, 11089, 11109, 11129, 11149 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { TA_TRIPLE_DMG_RATE = 2 },
            [3] = { TA_TRIPLE_DMG_RATE = 3 },
            [4] = { TA_TRIPLE_DMG_RATE = 4 },
            [5] = { TA_TRIPLE_DMG_RATE = 5 },
        },
    },
    [41] = {
        pieces = { 11066, 11086, 11106, 11126, 11146 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { BAR_ELEMENT_NULL_CHANCE = 2 },
            [3] = { BAR_ELEMENT_NULL_CHANCE = 3 },
            [4] = { BAR_ELEMENT_NULL_CHANCE = 4 },
            [5] = { BAR_ELEMENT_NULL_CHANCE = 5 },
        },
    },
    [42] = {
        pieces = { 11083, 11103, 11123, 11143, 11163 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { GRIMOIRE_INSTANT_CAST = 2 },
            [3] = { GRIMOIRE_INSTANT_CAST = 3 },
            [4] = { GRIMOIRE_INSTANT_CAST = 4 },
            [5] = { GRIMOIRE_INSTANT_CAST = 5 },
        },
    },
    [43] = {
        pieces = { 16005, 17756, 17962, 18596, 18760, 19112, 19156, 19215, 19271 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { Accuracy = 6, HP = 30, RangedAccuracy = 6, VIT = 6 },
        },
    },
    [44] = {
        pieces = { 16004, 17757, 18128, 18500, 18597, 18761, 18951, 19218 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { Attack = 4, MagicAttackBonus = 2, RangedAttack = 4, STR = 6 },
        },
    },
    [45] = {
        pieces = { 16006, 18450, 18499, 18861, 18862, 18952, 19111, 19217, 19272 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { Enmity = -5, Evasion = 10, HHP = 10 },
        },
    },
    [46] = {
        pieces = { 11362, 11798 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { RERAISE_III = 1 },
        },
    },
    [54] = {
        pieces = { 28520, 28521 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { DoubleAttack = 7 },
        },
    },
    [55] = {
        pieces = { 28522, 28523 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { DualWield = 7 },
        },
    },
    [56] = {
        pieces = { 28524, 28525 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { MagicAccuracy = 12 },
        },
    },
    [57] = {
        pieces = { 26762, 26763, 26920, 26921, 27074, 27075, 27259, 27260, 27433, 27434 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { ZANSHIN_DOUBLE_DAMAGE = 2 },
            [3] = { ZANSHIN_DOUBLE_DAMAGE = 3 },
            [4] = { ZANSHIN_DOUBLE_DAMAGE = 4 },
            [5] = { ZANSHIN_DOUBLE_DAMAGE = 5 },
        },
    },
    [58] = {
        pieces = { 26742, 26743, 26900, 26901, 27054, 27055, 27239, 27240, 27413, 27414 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { EXTRA_KICK_ATTACK = 2 },
            [3] = { EXTRA_KICK_ATTACK = 3 },
            [4] = { EXTRA_KICK_ATTACK = 4 },
            [5] = { EXTRA_KICK_ATTACK = 5 },
        },
    },
    [59] = {
        pieces = { 26740, 26741, 26898, 26899, 27052, 27053, 27237, 27238, 27411, 27412 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { DA_DOUBLE_DMG_RATE = 2 },
            [3] = { DA_DOUBLE_DMG_RATE = 3 },
            [4] = { DA_DOUBLE_DMG_RATE = 4 },
            [5] = { DA_DOUBLE_DMG_RATE = 5 },
        },
    },
    [60] = {
        pieces = { 26750, 26751, 26908, 26909, 27062, 27063, 27247, 27248, 27421, 27422 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { TA_TRIPLE_DMG_RATE = 2 },
            [3] = { TA_TRIPLE_DMG_RATE = 3 },
            [4] = { TA_TRIPLE_DMG_RATE = 4 },
            [5] = { TA_TRIPLE_DMG_RATE = 5 },
        },
    },
    [61] = {
        pieces = { 26760, 26761, 26918, 26919, 27072, 27073, 27257, 27258, 27431, 27432 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { RAPID_SHOT_DOUBLE_DAMAGE = 2 },
            [3] = { RAPID_SHOT_DOUBLE_DAMAGE = 3 },
            [4] = { RAPID_SHOT_DOUBLE_DAMAGE = 4 },
            [5] = { RAPID_SHOT_DOUBLE_DAMAGE = 5 },
        },
    },
    [62] = {
        pieces = { 26752, 26753, 26910, 26911, 27064, 27065, 27249, 27250, 27423, 27424 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { AbsorbDamageChance = 2 },
            [3] = { AbsorbDamageChance = 3 },
            [4] = { AbsorbDamageChance = 4 },
            [5] = { AbsorbDamageChance = 5 },
        },
    },
    [63] = {
        pieces = { 26764, 26765, 26922, 26923, 27076, 27077, 27261, 27262, 27435, 27436 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { EXTRA_DUAL_WIELD_ATTACK = 2 },
            [3] = { EXTRA_DUAL_WIELD_ATTACK = 3 },
            [4] = { EXTRA_DUAL_WIELD_ATTACK = 4 },
            [5] = { EXTRA_DUAL_WIELD_ATTACK = 5 },
        },
    },
    [64] = {
        pieces = { 26772, 26773, 26930, 26931, 27084, 27085, 27269, 27270, 27443, 27444 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { QUICK_DRAW_TRIPLE_DAMAGE = 2 },
            [3] = { QUICK_DRAW_TRIPLE_DAMAGE = 3 },
            [4] = { QUICK_DRAW_TRIPLE_DAMAGE = 4 },
            [5] = { QUICK_DRAW_TRIPLE_DAMAGE = 5 },
        },
    },
    [65] = {
        pieces = { 26778, 26779, 26936, 26937, 27090, 27091, 27275, 27276, 27449, 27450 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { GRIMOIRE_INSTANT_CAST = 2 },
            [3] = { GRIMOIRE_INSTANT_CAST = 3 },
            [4] = { GRIMOIRE_INSTANT_CAST = 4 },
            [5] = { GRIMOIRE_INSTANT_CAST = 5 },
        },
    },
    [66] = {
        pieces = { 26744, 26745, 26902, 26903, 27056, 27057, 27241, 27242, 27415, 27416 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { BAR_ELEMENT_NULL_CHANCE = 2 },
            [3] = { BAR_ELEMENT_NULL_CHANCE = 3 },
            [4] = { BAR_ELEMENT_NULL_CHANCE = 4 },
            [5] = { BAR_ELEMENT_NULL_CHANCE = 5 },
        },
    },
    [67] = {
        pieces = { 10865, 10868, 11864, 11867, 11870 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { Refresh = 3 },
        },
    },
    [68] = {
        pieces = { 15852, 15853 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { HP = 50, MP = 50 },
        },
    },
    [69] = {
        pieces = { 16037, 16038 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { MagicAccuracy = 5, MagicAttackBonus = 5 },
        },
    },
    [70] = {
        pieces = { 15850, 15851 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { Accuracy = 12, Attack = 6, DEF = 6 },
        },
    },
    [71] = {
        pieces = { 14588, 15009, 15755, 16146, 16315 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { DARK_MEVA = 5, EARTH_MEVA = 5, FIRE_MEVA = 5, ICE_MEVA = 5, LIGHT_MEVA = 5, THUNDER_MEVA = 5, WATER_MEVA = 5, WIND_MEVA = 5 },
            [3] = { DARK_MEVA = 10, EARTH_MEVA = 10, FIRE_MEVA = 10, ICE_MEVA = 10, LIGHT_MEVA = 10, THUNDER_MEVA = 10, WATER_MEVA = 10, WIND_MEVA = 10 },
            [4] = { DARK_MEVA = 15, EARTH_MEVA = 15, FIRE_MEVA = 15, ICE_MEVA = 15, LIGHT_MEVA = 15, THUNDER_MEVA = 15, WATER_MEVA = 15, WIND_MEVA = 15 },
            [5] = { DARK_MEVA = 30, EARTH_MEVA = 30, FIRE_MEVA = 30, ICE_MEVA = 30, LIGHT_MEVA = 30, THUNDER_MEVA = 30, WATER_MEVA = 30, WIND_MEVA = 30 },
        },
    },
    [72] = {
        pieces = { 16035, 16036 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { AGI = 8 },
        },
    },
    [73] = {
        pieces = { 11402, 15042 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { Attack = 5, RangedAttack = 5 },
        },
    },
    [74] = {
        pieces = { 26713, 27853, 27999, 28140, 28279 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { FastCast = 4 },
            [3] = { FastCast = 6 },
            [4] = { FastCast = 8 },
            [5] = { FastCast = 10 },
        },
    },
    [75] = {
        pieces = { 26712, 27852, 27998, 28139, 28278 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { StoreTP = 2 },
            [3] = { StoreTP = 4 },
            [4] = { StoreTP = 6 },
            [5] = { StoreTP = 8 },
        },
    },
    [76] = {
        pieces = { 26711, 27851, 27997, 28138, 28277 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Haste = 0 },
            [3] = { Haste = 0 },
            [4] = { Haste = 0 },
            [5] = { Haste = 0 },
        },
    },
    [77] = {
        pieces = { 27652, 27792, 27932, 28075, 28212 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { MagicAttackBonus = 3 },
            [3] = { MagicAttackBonus = 5 },
            [4] = { MagicAttackBonus = 7 },
            [5] = { MagicAttackBonus = 9 },
        },
    },
    [78] = {
        pieces = { 27651, 27791, 27931, 28074, 28211 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { FastCast = 3 },
            [3] = { FastCast = 5 },
            [4] = { FastCast = 7 },
            [5] = { FastCast = 9 },
        },
    },
    [79] = {
        pieces = { 27650, 27790, 27930, 28073, 28210 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Haste = 3 },
            [3] = { Haste = 5 },
            [4] = { Haste = 7 },
            [5] = { Haste = 9 },
        },
    },
    [80] = {
        pieces = { 27649, 27789, 27929, 28072, 28209 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { CriticalHitRate = 3 },
            [3] = { CriticalHitRate = 5 },
            [4] = { CriticalHitRate = 7 },
            [5] = { CriticalHitRate = 9 },
        },
    },
    [81] = {
        pieces = { 27648, 27788, 27928, 28071, 28208 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { DoubleAttack = 3 },
            [3] = { DoubleAttack = 5 },
            [4] = { DoubleAttack = 7 },
            [5] = { DoubleAttack = 9 },
        },
    },
    [82] = {
        pieces = { 10315, 10598 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { MDT = -5 },
        },
    },
    [83] = {
        pieces = { 25574, 25790, 25828, 25879, 25946, 26204 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { SubtleBlow = 5 },
            [3] = { SubtleBlow = 10 },
            [4] = { SubtleBlow = 15 },
            [5] = { SubtleBlow = 20 },
        },
    },
    [84] = {
        pieces = { 25576, 25792, 25830, 25881, 25948, 26206 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Counter = 4 },
            [3] = { Counter = 8 },
            [4] = { Counter = 12 },
            [5] = { Counter = 16 },
        },
    },
    [85] = {
        pieces = { 25577, 25793, 25831, 25882, 25949, 26207 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Refresh = 1 },
            [3] = { Refresh = 2 },
            [4] = { Refresh = 3 },
            [5] = { Refresh = 4 },
        },
    },
    [86] = {
        pieces = { 25575, 25791, 25829, 25880, 25947, 26205 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Regen = 3 },
            [3] = { Regen = 6 },
            [4] = { Regen = 9 },
            [5] = { Regen = 12 },
        },
    },
    [87] = {
        pieces = { 25578, 25794, 25832, 25883, 25950, 26208 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { FastCast = 1 },
            [3] = { FastCast = 2 },
            [4] = { FastCast = 3 },
            [5] = { FastCast = 4 },
        },
    },
    [88] = {
        pieces = { 25569, 25797, 25835, 25886, 25953, 26211 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { DEX = 8, STR = 8, VIT = 8 },
            [3] = { DEX = 16, STR = 16, VIT = 16 },
            [4] = { DEX = 24, STR = 24, VIT = 24 },
            [5] = { DEX = 32, STR = 32, VIT = 32 },
        },
    },
    [89] = {
        pieces = { 25573, 25796, 25834, 25885, 25952, 26210 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { CHR = 8, DEX = 8, VIT = 8 },
            [3] = { CHR = 16, DEX = 16, VIT = 16 },
            [4] = { CHR = 24, DEX = 24, VIT = 24 },
            [5] = { CHR = 32, DEX = 32, VIT = 32 },
        },
    },
    [90] = {
        pieces = { 25570, 25798, 25836, 25887, 25954, 26212 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { AGI = 8, CHR = 8, DEX = 8 },
            [3] = { AGI = 16, CHR = 16, DEX = 16 },
            [4] = { AGI = 24, CHR = 24, DEX = 24 },
            [5] = { AGI = 32, CHR = 32, DEX = 32 },
        },
    },
    [91] = {
        pieces = { 25572, 25795, 25833, 25884, 25951, 26209 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { MND = 8, STR = 8, VIT = 8 },
            [3] = { MND = 16, STR = 16, VIT = 16 },
            [4] = { MND = 24, STR = 24, VIT = 24 },
            [5] = { MND = 32, STR = 32, VIT = 32 },
        },
    },
    [92] = {
        pieces = { 25571, 25799, 25837, 25888, 25955, 26213 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { INT = 8, MND = 8, VIT = 8 },
            [3] = { INT = 16, MND = 16, VIT = 16 },
            [4] = { INT = 24, MND = 24, VIT = 24 },
            [5] = { INT = 32, MND = 32, VIT = 32 },
        },
    },
    [93] = {
        pieces = { 23040, 23107, 23174, 23241, 23308, 23375, 23442, 23509, 23576, 23643, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [94] = {
        pieces = { 23041, 23108, 23175, 23242, 23309, 23376, 23443, 23510, 23577, 23644, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [95] = {
        pieces = { 23042, 23109, 23176, 23243, 23310, 23377, 23444, 23511, 23578, 23645, 26085 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [96] = {
        pieces = { 23043, 23110, 23177, 23244, 23311, 23378, 23445, 23512, 23579, 23646, 26085 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [97] = {
        pieces = { 23044, 23111, 23178, 23245, 23312, 23379, 23446, 23513, 23580, 23647, 26085 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [98] = {
        pieces = { 23045, 23112, 23179, 23246, 23313, 23380, 23447, 23514, 23581, 23648, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [99] = {
        pieces = { 23046, 23113, 23180, 23247, 23314, 23381, 23448, 23515, 23582, 23649, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [100] = {
        pieces = { 23047, 23114, 23181, 23248, 23315, 23382, 23449, 23516, 23583, 23650, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [101] = {
        pieces = { 23048, 23115, 23182, 23249, 23316, 23383, 23450, 23517, 23584, 23651, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [102] = {
        pieces = { 23049, 23116, 23183, 23250, 23317, 23384, 23451, 23518, 23585, 23652, 26085 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [103] = {
        pieces = { 23050, 23117, 23184, 23251, 23318, 23385, 23452, 23519, 23586, 23653, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [104] = {
        pieces = { 23051, 23118, 23185, 23252, 23319, 23386, 23453, 23520, 23587, 23654, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [105] = {
        pieces = { 23052, 23119, 23186, 23253, 23320, 23387, 23454, 23521, 23588, 23655, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [106] = {
        pieces = { 23053, 23120, 23187, 23254, 23321, 23388, 23455, 23522, 23589, 23656, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [107] = {
        pieces = { 23054, 23121, 23188, 23255, 23322, 23389, 23456, 23523, 23590, 23657, 26342 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [108] = {
        pieces = { 23055, 23122, 23189, 23256, 23323, 23390, 23457, 23524, 23591, 23658, 26085 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [109] = {
        pieces = { 23056, 23123, 23190, 23257, 23324, 23391, 23458, 23525, 23592, 23659, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [110] = {
        pieces = { 23057, 23124, 23191, 23258, 23325, 23392, 23459, 23526, 23593, 23660, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [111] = {
        pieces = { 23058, 23125, 23192, 23259, 23326, 23393, 23460, 23527, 23594, 23661, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [112] = {
        pieces = { 23059, 23126, 23193, 23260, 23327, 23394, 23461, 23528, 23595, 23662, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [113] = {
        pieces = { 23060, 23127, 23194, 23261, 23328, 23395, 23462, 23529, 23596, 23663, 26085 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [114] = {
        pieces = { 23061, 23128, 23195, 23262, 23329, 23396, 23463, 23530, 23597, 23664, 26085 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [115] = {
        pieces = { 23062, 23129, 23196, 23263, 23330, 23397, 23464, 23531, 23598, 23665, 26191 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
            [3] = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
            [4] = { Accuracy = 45, MagicAccuracy = 45, RangedAccuracy = 45 },
            [5] = { Accuracy = 60, MagicAccuracy = 60, RangedAccuracy = 60 },
        },
    },
    [116] = {
        pieces = { 27740, 27881, 28029, 28168, 28306 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { PDT = -10 },
        },
    },
    [117] = {
        pieces = { 27741, 27882, 28030, 28169, 28307 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { CRIT_DMG_INCREASE = 10 },
        },
    },
    [118] = {
        pieces = { 27742, 27883, 28031, 28170, 28308 },
        min = 5,
        max = 5,
        tiers = {
            [5] = { Refresh = 3 },
        },
    },
    [119] = {
        pieces = { 26677, 26853, 27029, 27205, 27381 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { BloodPactDamage = 4 },
            [3] = { BloodPactDamage = 6 },
            [4] = { BloodPactDamage = 8 },
            [5] = { BloodPactDamage = 10 },
        },
    },
    [120] = {
        pieces = { 25612, 25685, 27116, 27301, 27472 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Attack = 20 },
            [3] = { Attack = 30 },
            [4] = { Attack = 40 },
            [5] = { Attack = 50 },
        },
    },
    [121] = {
        pieces = { 26671, 26847, 27023, 27199, 27375 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { DT = -4 },
            [3] = { DT = -6 },
            [4] = { DT = -8 },
            [5] = { DT = -10 },
        },
    },
    [122] = {
        pieces = { 25610, 25683, 27114, 27299, 27470 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { DoubleAttack = 4 },
            [3] = { DoubleAttack = 6 },
            [4] = { DoubleAttack = 8 },
            [5] = { DoubleAttack = 10 },
        },
    },
    [123] = {
        pieces = { 25618, 25691, 27122, 27307, 27478 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { CURE_POTENCY_II = 4 },
            [3] = { CURE_POTENCY_II = 6 },
            [4] = { CURE_POTENCY_II = 8 },
            [5] = { CURE_POTENCY_II = 10 },
        },
    },
    [124] = {
        pieces = { 26675, 26851, 27027, 27203, 27379 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { MARTIAL_ARTS = 8 },
            [3] = { MARTIAL_ARTS = 12 },
            [4] = { MARTIAL_ARTS = 16 },
            [5] = { MARTIAL_ARTS = 20 },
        },
    },
    [125] = {
        pieces = { 25614, 25687, 27118, 27303, 27474 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { CriticalHitRate = 4 },
            [3] = { CriticalHitRate = 6 },
            [4] = { CriticalHitRate = 8 },
            [5] = { CriticalHitRate = 10 },
        },
    },
    [126] = {
        pieces = { 26679, 26855, 27031, 27207, 27383 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { Accuracy = 20 },
            [3] = { Accuracy = 30 },
            [4] = { Accuracy = 40 },
            [5] = { Accuracy = 50 },
        },
    },
    [127] = {
        pieces = { 26669, 26845, 27021, 27197, 27373 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { ALL_WSDMG_FIRST_HIT = 4 },
            [3] = { ALL_WSDMG_FIRST_HIT = 6 },
            [4] = { ALL_WSDMG_FIRST_HIT = 8 },
            [5] = { ALL_WSDMG_FIRST_HIT = 10 },
        },
    },
    [128] = {
        pieces = { 26673, 26849, 27025, 27201, 27377 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { DoubleAttack = 4 },
            [3] = { DoubleAttack = 6 },
            [4] = { DoubleAttack = 8 },
            [5] = { DoubleAttack = 10 },
        },
    },
    [129] = {
        pieces = { 25616, 25689, 27120, 27305, 27476 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { MagicAttackBonus = 20 },
            [3] = { MagicAttackBonus = 30 },
            [4] = { MagicAttackBonus = 40 },
            [5] = { MagicAttackBonus = 50 },
        },
    },
    [130] = {
        pieces = { 15818, 18947 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { Accuracy = 5, SOULEATER_EFFECT = 2 },
        },
    },
    [131] = {
        pieces = { 11079, 11099, 11119, 11139, 11159 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { AUGMENT_BLU_MAGIC = 2 },
            [3] = { AUGMENT_BLU_MAGIC = 3 },
            [4] = { AUGMENT_BLU_MAGIC = 4 },
            [5] = { AUGMENT_BLU_MAGIC = 5 },
        },
    },
    [132] = {
        pieces = { 26770, 26771, 26928, 26929, 27082, 27083, 27267, 27268, 27441, 27442 },
        min = 2,
        max = 5,
        tiers = {
            [2] = { AUGMENT_BLU_MAGIC = 2 },
            [3] = { AUGMENT_BLU_MAGIC = 3 },
            [4] = { AUGMENT_BLU_MAGIC = 4 },
            [5] = { AUGMENT_BLU_MAGIC = 5 },
        },
    },
    [133] = {
        pieces = { 14999, 15745 },
        min = 2,
        max = 2,
        tiers = {
            [2] = { ENH_DRAIN_ASPIR = 5 },
        },
    },
};
