--[[
    dlac/levelstats.lua -- resolve LEVEL-SCALING item stats (Rajas/Tamas/Sattva rings
    and every other item the CatsEyeXI server scales via level latents).

    levelscaling.lua (generated by tools/gen_levelscaling.py from the server's
    item_latents) maps item Id -> additive threshold rows:
        { stat = "STR", add = 1, from = 45 }     -- active while level >= 45
        { stat = "HP",  add = 10, below = 30 }   -- active while level <  30
    M.apply(id, level, baseStats) returns the EFFECTIVE stats table for that level
    (a fresh copy -- the catalog's base table is never mutated). Items without
    scaling pass through untouched, so callers can apply unconditionally.

    Consumed by gearui (worn/set totals, tooltips, row summaries, scoring),
    gearoptim (slot ranking) and triggersui (automation manifest MP values) --
    all through M.effective, THE central stats-at-level resolver. The dispatch
    engine never needs it -- it equips by name; the GAME applies the real latents.
]]--

local M = {};

local _ok, DATA = pcall(require, "dlac\\data\\levelscaling");
if not _ok or type(DATA) ~= 'table' then DATA = {}; end

-- Does this item scale with level at all?
function M.has(id)
    return id ~= nil and DATA[id] ~= nil;
end

-- THE central "stats of this item at this level". Every section that reads item
-- stats for a character resolves through here -- gearui (display, totals,
-- scoring), gearoptim (slot ranking), triggersui (automation manifests) -- so a
-- scaling item (Tamas Ring: MP 15 base, 29 at Lv74, 30 at 75) is never valued
-- at its base stats by one section and its real stats by another. nil level or
-- a non-scaling item returns rec.Stats untouched.
function M.effective(rec, level)
    if type(rec) ~= 'table' then return nil; end
    if level == nil or rec.Id == nil or DATA[rec.Id] == nil then return rec.Stats; end
    return M.apply(rec.Id, level, rec.Stats);
end

-- Effective stats for `id` at `level`, starting from baseStats (catalog values).
-- Returns baseStats itself when the item has no scaling (zero-copy fast path).
function M.apply(id, level, baseStats)
    local rows = (id ~= nil) and DATA[id] or nil;
    if rows == nil then return baseStats; end
    local out = {};
    if type(baseStats) == 'table' then
        for k, v in pairs(baseStats) do out[k] = v; end
    end
    level = tonumber(level) or 0;
    for _, r in ipairs(rows) do
        local active = false;
        if r.from ~= nil then active = (level >= r.from);
        elseif r.below ~= nil then active = (level < r.below); end
        if active and type(r.stat) == 'string' and type(r.add) == 'number' then
            out[r.stat] = (out[r.stat] or 0) + r.add;
        end
    end
    return out;
end

return M;
