-- dlac level-scaling stats -- GENERATED by tools/gen_levelscaling.py from the
-- CatsEyeXI server's item_latents (latent 51: active at level >= from; latent 50:
-- active while level < below). Resolved at display/scoring time by levelstats.lua.
-- Do not hand-edit; re-run the generator instead.
return {
    [10293] = {
        { stat = "Accuracy", add = 50, below = 31 },
        { stat = "MagicAccuracy", add = 50, below = 31 },
        { stat = "RangedAccuracy", add = 50, below = 31 },
    },
    [11811] = {
        { stat = "COMBAT_SKILLUP_RATE", add = 1, below = 31 },
        { stat = "MAGIC_SKILLUP_RATE", add = 1, below = 31 },
        { stat = "MovementSpeed", add = 12, below = 31 },
        { stat = "RERAISE_I", add = 1, below = 31 },
        { stat = "Refresh", add = 1, below = 31 },
        { stat = "Regen", add = 1, below = 31 },
    },
    [13680] = {
        { stat = "DEF", add = 1, from = 30 },
        { stat = "DEF", add = 1, from = 40 },
        { stat = "DEF", add = 1, from = 50 },
        { stat = "DEF", add = 1, from = 60 },
        { stat = "DEF", add = 1, from = 70 },
        { stat = "DEF", add = 1, from = 80 },
        { stat = "DEF", add = 1, from = 90 },
    },
    [13681] = {
        { stat = "DEF", add = 1, from = 30 },
        { stat = "DEF", add = 1, from = 40 },
        { stat = "DEF", add = 1, from = 50 },
        { stat = "DEF", add = 1, from = 60 },
        { stat = "DEF", add = 1, from = 70 },
        { stat = "DEF", add = 1, from = 80 },
        { stat = "DEF", add = 1, from = 90 },
        { stat = "MP", add = 2, from = 25 },
        { stat = "MP", add = 2, from = 30 },
        { stat = "MP", add = 2, from = 35 },
        { stat = "MP", add = 2, from = 40 },
        { stat = "MP", add = 2, from = 45 },
        { stat = "MP", add = 2, from = 50 },
        { stat = "MP", add = 2, from = 55 },
        { stat = "MP", add = 2, from = 60 },
        { stat = "MP", add = 2, from = 65 },
        { stat = "MP", add = 2, from = 70 },
        { stat = "MP", add = 2, from = 75 },
        { stat = "MP", add = 2, from = 80 },
        { stat = "MP", add = 2, from = 85 },
        { stat = "MP", add = 2, from = 90 },
        { stat = "MP", add = 2, from = 95 },
    },
    [15186] = {
        { stat = "HP", add = 14, from = 20 },
        { stat = "HP", add = 1, from = 30 },
        { stat = "HP", add = 1, from = 34 },
        { stat = "HP", add = 1, from = 40 },
        { stat = "HP", add = 1, from = 44 },
        { stat = "HP", add = 1, from = 47 },
        { stat = "HP", add = 1, from = 50 },
        { stat = "HP", add = 1, from = 55 },
        { stat = "HP", add = 1, from = 58 },
        { stat = "HP", add = 1, from = 61 },
        { stat = "HP", add = 1, from = 65 },
        { stat = "HP", add = 1, from = 70 },
        { stat = "HP", add = 1, from = 73 },
        { stat = "HP", add = 1, from = 75 },
        { stat = "MP", add = 14, from = 20 },
        { stat = "MP", add = 1, from = 30 },
        { stat = "MP", add = 1, from = 34 },
        { stat = "MP", add = 1, from = 40 },
        { stat = "MP", add = 1, from = 44 },
        { stat = "MP", add = 1, from = 47 },
        { stat = "MP", add = 1, from = 50 },
        { stat = "MP", add = 1, from = 55 },
        { stat = "MP", add = 1, from = 58 },
        { stat = "MP", add = 1, from = 61 },
        { stat = "MP", add = 1, from = 65 },
        { stat = "MP", add = 1, from = 70 },
        { stat = "MP", add = 1, from = 73 },
        { stat = "MP", add = 1, from = 75 },
    },
    [15543] = {
        { stat = "DEX", add = 1, from = 45 },
        { stat = "DEX", add = 1, from = 60 },
        { stat = "DEX", add = 1, from = 75 },
        { stat = "STR", add = 1, from = 45 },
        { stat = "STR", add = 1, from = 60 },
        { stat = "STR", add = 1, from = 75 },
    },
    [15544] = {
        { stat = "AGI", add = 1, from = 45 },
        { stat = "AGI", add = 1, from = 60 },
        { stat = "AGI", add = 1, from = 75 },
        { stat = "HP", add = 1, from = 33 },
        { stat = "HP", add = 1, from = 36 },
        { stat = "HP", add = 1, from = 39 },
        { stat = "HP", add = 1, from = 42 },
        { stat = "HP", add = 1, from = 45 },
        { stat = "HP", add = 1, from = 48 },
        { stat = "HP", add = 1, from = 51 },
        { stat = "HP", add = 1, from = 54 },
        { stat = "HP", add = 1, from = 57 },
        { stat = "HP", add = 1, from = 60 },
        { stat = "HP", add = 1, from = 63 },
        { stat = "HP", add = 1, from = 66 },
        { stat = "HP", add = 1, from = 69 },
        { stat = "HP", add = 1, from = 72 },
        { stat = "HP", add = 1, from = 75 },
        { stat = "VIT", add = 1, from = 45 },
        { stat = "VIT", add = 1, from = 60 },
        { stat = "VIT", add = 1, from = 75 },
    },
    [15545] = {
        { stat = "INT", add = 1, from = 45 },
        { stat = "INT", add = 1, from = 60 },
        { stat = "INT", add = 1, from = 75 },
        { stat = "MND", add = 1, from = 45 },
        { stat = "MND", add = 1, from = 60 },
        { stat = "MND", add = 1, from = 75 },
        { stat = "MP", add = 1, from = 33 },
        { stat = "MP", add = 1, from = 36 },
        { stat = "MP", add = 1, from = 39 },
        { stat = "MP", add = 1, from = 42 },
        { stat = "MP", add = 1, from = 45 },
        { stat = "MP", add = 1, from = 48 },
        { stat = "MP", add = 1, from = 51 },
        { stat = "MP", add = 1, from = 54 },
        { stat = "MP", add = 1, from = 57 },
        { stat = "MP", add = 1, from = 60 },
        { stat = "MP", add = 1, from = 63 },
        { stat = "MP", add = 1, from = 66 },
        { stat = "MP", add = 1, from = 69 },
        { stat = "MP", add = 1, from = 72 },
        { stat = "MP", add = 1, from = 75 },
    },
    [18905] = {
        { stat = "DMG_RATING", add = 2, from = 59 },
    },
    [20531] = {
        { stat = "DMG_RATING", add = 2, from = 59 },
    },
    [20597] = {
        { stat = "MAX_SWINGS", add = 2, below = 50 },
    },
    [20617] = {
        { stat = "DMG_RATING", add = 6, from = 59 },
    },
    [20719] = {
        { stat = "DMG_RATING", add = 8, from = 59 },
    },
    [20760] = {
        { stat = "DMG_RATING", add = 8, from = 59 },
    },
    [20903] = {
        { stat = "DMG_RATING", add = 8, from = 59 },
    },
    [20947] = {
        { stat = "DMG_RATING", add = 8, from = 59 },
    },
    [20993] = {
        { stat = "DMG_RATING", add = 6, from = 59 },
    },
    [21109] = {
        { stat = "DMG_RATING", add = 6, from = 59 },
    },
    [21172] = {
        { stat = "DMG_RATING", add = 8, from = 59 },
    },
    [21226] = {
        { stat = "DMG_RATING", add = 4, from = 59 },
    },
    [21275] = {
        { stat = "DMG_RATING", add = 4, from = 59 },
    },
    [21406] = {
        { stat = "WIND", add = 2, from = 59 },
    },
    [21510] = {
        { stat = "DMG_RATING", add = 2, from = 29 },
    },
    [21566] = {
        { stat = "DMG_RATING", add = 2, from = 29 },
    },
    [21622] = {
        { stat = "DMG_RATING", add = 5, from = 29 },
    },
    [21665] = {
        { stat = "DMG_RATING", add = 8, from = 29 },
    },
    [21712] = {
        { stat = "DMG_RATING", add = 8, from = 29 },
    },
    [21769] = {
        { stat = "DMG_RATING", add = 16, from = 29 },
    },
    [21822] = {
        { stat = "DMG_RATING", add = 12, from = 29 },
    },
    [21864] = {
        { stat = "DMG_RATING", add = 16, from = 29 },
    },
    [21912] = {
        { stat = "DMG_RATING", add = 7, from = 29 },
    },
    [21976] = {
        { stat = "DMG_RATING", add = 10, from = 29 },
    },
    [22006] = {
        { stat = "DMG_RATING", add = 8, from = 29 },
    },
    [22088] = {
        { stat = "DMG_RATING", add = 8, from = 29 },
    },
    [22133] = {
        { stat = "DMG_RATING", add = 12, from = 29 },
    },
    [22144] = {
        { stat = "DMG_RATING", add = 8, from = 29 },
    },
    [22219] = {
        { stat = "DMG_RATING", add = 8, from = 29 },
    },
    [22291] = {
        { stat = "DMG_RATING", add = 8, from = 29 },
    },
    [22296] = {
        { stat = "WIND", add = 3, from = 29 },
    },
    [23996] = {
        { stat = "Accuracy", add = 50, below = 31 },
        { stat = "MagicAccuracy", add = 50, below = 31 },
        { stat = "RangedAccuracy", add = 50, below = 31 },
        { stat = "STR", add = 1, below = 31 },
        { stat = "VIT", add = 1, below = 31 },
    },
    [23997] = {
        { stat = "AGI", add = 1, below = 31 },
        { stat = "Accuracy", add = 50, below = 31 },
        { stat = "DEX", add = 1, below = 31 },
        { stat = "MagicAccuracy", add = 50, below = 31 },
        { stat = "RangedAccuracy", add = 50, below = 31 },
    },
    [23998] = {
        { stat = "Accuracy", add = 50, below = 31 },
        { stat = "CHR", add = 1, below = 31 },
        { stat = "INT", add = 1, below = 31 },
        { stat = "MND", add = 1, below = 31 },
        { stat = "MagicAccuracy", add = 50, below = 31 },
        { stat = "RangedAccuracy", add = 50, below = 31 },
    },
    [25567] = {
        { stat = "Regen", add = 1, below = 51 },
    },
    [25907] = {
        { stat = "HASTE_GEAR", add = 200, below = 51 },
    },
    [26413] = {
        { stat = "DEF", add = 2, from = 29 },
    },
    [26543] = {
        { stat = "Refresh", add = 1, below = 51 },
    },
    [27624] = {
        { stat = "DEF", add = 2, from = 59 },
    },
    [39018] = {
        { stat = "Refresh", add = 1, below = 51 },
    },
    [39028] = {
        { stat = "Refresh", add = 1, below = 51 },
    },
    [39038] = {
        { stat = "Refresh", add = 1, below = 51 },
    },
};
