-- dlac pet-channel gear stats -- GENERATED by tools/gen_petmods.py from the
-- CatsEyeXI server's item_mods_pet (stats the gear grants TO YOUR PET; the live
-- API never exposes this channel, so apicrawl cannot supply it). Keys are the
-- canonical catalog stat keys; pet names are the server's PetModType enum.
-- Display-first (gear/gearfmt.lua). Do not hand-edit; re-run the generator instead.
return {
    [10296] = {
        Automaton = { Accuracy = 3, MagicAccuracy = 3, RangedAccuracy = 3 },
    },
    [10299] = {
        All = { DoubleAttack = 2 },
    },
    [10370] = {
        Avatar = { BloodPactDamage = 3, MagicAccuracy = 3, MagicAttackBonus = 3 },
    },
    [10440] = {
        Automaton = { Haste = 6 },
    },
    [10530] = {
        Avatar = { MagicAttackBonus = 5 },
    },
    [10531] = {
        Avatar = { MagicAttackBonus = 5 },
    },
    [10532] = {
        Avatar = { MagicAttackBonus = 5 },
    },
    [10537] = {
        Avatar = { Attack = 9, BloodPactDamage = 4 },
    },
    [10542] = {
        Avatar = { Attack = 12, BloodPactDamage = 5 },
    },
    [10664] = {
        Avatar = { MagicAttackBonus = 4, PerpetuationCost = 3 },
    },
    [10684] = {
        Avatar = { CriticalHitRate = 6, PerpetuationCost = 3 },
    },
    [10724] = {
        Avatar = { MagicAccuracy = 5 },
    },
    [10744] = {
        Avatar = { MagicCriticalHitRate = 5 },
    },
    [10817] = {
        All = { Haste = 5 },
    },
    [10914] = {
        All = { Enmity = -2 },
    },
    [10915] = {
        All = { Enmity = -3 },
    },
    [10972] = {
        All = { PDT = -3, RDT = -3 },
    },
    [11052] = {
        Avatar = { BloodPactDamage = 3 },
    },
    [11072] = {
        All = { MonsterCorrelation = 20 },
    },
    [11098] = {
        Avatar = { BloodPactDamage = 10 },
    },
    [11118] = {
        Avatar = { Accuracy = 15 },
    },
    [11138] = {
        Avatar = { TPBonus = 500 },
    },
    [11158] = {
        Avatar = { MagicAccuracy = 5 },
    },
    [11172] = {
        All = { MonsterCorrelation = 10 },
    },
    [11198] = {
        Avatar = { BloodPactDamage = 5 },
    },
    [11218] = {
        Avatar = { Accuracy = 10 },
    },
    [11238] = {
        Avatar = { TPBonus = 250 },
    },
    [11258] = {
        Avatar = { MagicAccuracy = 5 },
    },
    [11261] = {
        Automaton = { INT = 10, MND = 10 },
    },
    [11297] = {
        Harlequin = { HP = 20, MP = 20 },
        Valoredge = { HP = 24 },
        Sharpshot = { HP = 18 },
        Stormwaker = { HP = 16, MP = 24 },
    },
    [11298] = {
        Automaton = { Accuracy = 10 },
    },
    [11299] = {
        Automaton = { Accuracy = 10 },
    },
    [11338] = {
        All = { Accuracy = 3, SubtleBlow = 3 },
    },
    [11388] = {
        Automaton = { MagicAttackBonus = 5 },
    },
    [11389] = {
        Automaton = { MagicAttackBonus = 5 },
    },
    [11392] = {
        Avatar = { Attack = 5, DEF = 10 },
    },
    [11470] = {
        Automaton = { HHP = 3, HMP = 3 },
    },
    [11471] = {
        Automaton = { Regen = 1 },
    },
    [11472] = {
        Automaton = { Regen = 1 },
    },
    [11497] = {
        All = { Haste = 5 },
    },
    [11531] = {
        All = { StoreTP = 3 },
    },
    [11555] = {
        All = { Accuracy = 10 },
    },
    [11564] = {
        Avatar = { MagicAttackBonus = 1 },
    },
    [11571] = {
        Automaton = { Accuracy = 12 },
    },
    [11612] = {
        Avatar = { MagicAttackBonus = 2 },
    },
    [11617] = {
        All = { DoubleAttack = 2 },
    },
    [11619] = {
        Avatar = { Regain = 25 },
    },
    [11711] = {
        All = { Accuracy = 3 },
    },
    [11720] = {
        Automaton = { Attack = 2, MagicAttackBonus = 3, RangedAttack = 3 },
    },
    [11739] = {
        Avatar = { Enmity = 2, MagicAttackBonus = 2 },
    },
    [11776] = {
        Avatar = { Attack = 10 },
    },
    [11987] = {
        Avatar = { BloodPactDamage = 5, Regen = 1 },
    },
    [12520] = {
        Avatar = { Enmity = -3 },
    },
    [12649] = {
        Wyvern = { Regen = 1 },
    },
    [12650] = {
        Avatar = { Enmity = -2 },
    },
    [13974] = {
        Wyvern = { Accuracy = 5 },
    },
    [13975] = {
        Avatar = { Enmity = -2 },
    },
    [14103] = {
        Avatar = { Enmity = -2, Evasion = 5 },
    },
    [14227] = {
        Wyvern = { HPP = 10 },
    },
    [14228] = {
        Avatar = { Accuracy = 10, Enmity = -2 },
    },
    [14405] = {
        Wyvern = { HHP = 65, HP = 65 },
    },
    [14468] = {
        Avatar = { Enmity = 5 },
    },
    [14486] = {
        Wyvern = { Regen = 1 },
    },
    [14514] = {
        Avatar = { CriticalHitRate = 4 },
    },
    [14523] = {
        Harlequin = { HP = 20, MP = 20 },
        Valoredge = { HP = 24 },
        Sharpshot = { HP = 18 },
        Stormwaker = { HP = 16, MP = 24 },
    },
    [14872] = {
        Wyvern = { HP = 10 },
    },
    [14903] = {
        Wyvern = { Accuracy = 5 },
    },
    [14904] = {
        Avatar = { Enmity = -2 },
    },
    [14923] = {
        Avatar = { Accuracy = 14 },
    },
    [14958] = {
        All = { DEFP = 5 },
    },
    [15031] = {
        Automaton = { Haste = 3 },
    },
    [15032] = {
        Automaton = { Haste = 3 },
    },
    [15101] = {
        Avatar = { CriticalHitRate = 3 },
    },
    [15116] = {
        Avatar = { Accuracy = 7 },
    },
    [15146] = {
        Avatar = { Attack = 7, BloodPactDelay = -2 },
    },
    [15239] = {
        Avatar = { Enmity = -3 },
    },
    [15267] = {
        Automaton = { HHP = 3, HMP = 3 },
    },
    [15366] = {
        Avatar = { Enmity = -4, Evasion = 5 },
    },
    [15367] = {
        Wyvern = { HP = 30 },
    },
    [15574] = {
        Wyvern = { HPP = 15 },
    },
    [15575] = {
        Avatar = { Accuracy = 14, Enmity = -2 },
    },
    [15594] = {
        Avatar = { Enmity = 2 },
    },
    [15602] = {
        Automaton = { CurePotency = 5, SpellInterruptionRateDown = 10 },
    },
    [15647] = {
        All = { DEF = 10 },
    },
    [15649] = {
        All = { DEF = 10 },
    },
    [15661] = {
        Wyvern = { HP = 50 },
    },
    [15679] = {
        Avatar = { Attack = 10, BloodPactDelay = -2, Enmity = 2 },
    },
    [15910] = {
        All = { DEF = 5, Enmity = 3 },
    },
    [15944] = {
        All = { MDT = -7 },
    },
    [16173] = {
        All = { DEF = 10 },
    },
    [16245] = {
        Automaton = { Attack = 15 },
    },
    [16270] = {
        Wyvern = { HP = 50 },
    },
    [16297] = {
        All = { PDT = -2, RDT = -2 },
    },
    [16351] = {
        Automaton = { CurePotency = 5, SpellInterruptionRateDown = 10 },
    },
    [16352] = {
        Automaton = { MagicAccuracy = 5 },
    },
    [16353] = {
        Automaton = { MagicAccuracy = 7 },
    },
    [16368] = {
        All = { Accuracy = 10 },
    },
    [16654] = {
        All = { Regain = 10 },
    },
    [16843] = {
        Wyvern = { Accuracy = 10, Attack = 10 },
    },
    [17579] = {
        Wyvern = { HP = 50 },
    },
    [17857] = {
        Harlequin = { HP = 50, MP = 50 },
        Valoredge = { HP = 60 },
        Sharpshot = { HP = 45 },
        Stormwaker = { HP = 40, MP = 60 },
    },
    [17961] = {
        All = { DEF = 10 },
    },
    [18547] = {
        All = { Regen = 3 },
    },
    [18745] = {
        Automaton = { HPP = 1 },
    },
    [18746] = {
        Automaton = { HPP = 2 },
    },
    [18778] = {
        Automaton = { Refresh = 1, Regen = 1 },
    },
    [18780] = {
        Automaton = { Regain = 10 },
    },
    [18791] = {
        Automaton = { Attack = 9, HP = 30, RangedAttack = 9 },
    },
    [18792] = {
        Automaton = { Attack = 10, HP = 40, RangedAttack = 10 },
    },
    [18999] = {
        All = { Attack = 40 },
    },
    [19005] = {
        Avatar = { MagicAttackBonus = 20 },
    },
    [19068] = {
        All = { Attack = 50 },
    },
    [19074] = {
        Avatar = { MagicAttackBonus = 25 },
    },
    [19088] = {
        All = { Attack = 60 },
    },
    [19094] = {
        Avatar = { MagicAttackBonus = 30 },
    },
    [19620] = {
        All = { Attack = 70 },
    },
    [19626] = {
        Avatar = { MagicAttackBonus = 35 },
    },
    [19718] = {
        All = { Attack = 70 },
    },
    [19724] = {
        Avatar = { MagicAttackBonus = 35 },
    },
    [19772] = {
        Avatar = { MagicAttackBonus = 1 },
    },
    [19827] = {
        All = { Attack = 80 },
    },
    [19833] = {
        Avatar = { MagicAttackBonus = 40 },
    },
    [19956] = {
        All = { Attack = 80 },
    },
    [19962] = {
        Avatar = { MagicAttackBonus = 40 },
    },
    [20516] = {
        Automaton = { Refresh = 4, Regen = 4 },
    },
    [20535] = {
        Automaton = { Refresh = 1, Regain = 10 },
    },
    [20536] = {
        Automaton = { Attack = 15, MagicAttackBonus = 15, RangedAttack = 15 },
    },
    [20549] = {
        Automaton = { Accuracy = 20, MagicAccuracy = 20, RangedAccuracy = 20 },
    },
    [20792] = {
        All = { Attack = 80 },
    },
    [20793] = {
        All = { Attack = 80 },
    },
    [20822] = {
        All = { Enmity = 6, Evasion = 40 },
    },
    [20831] = {
        All = { DoubleAttack = 2 },
    },
    [20832] = {
        All = { DoubleAttack = 3 },
    },
    [20944] = {
        Wyvern = { PDT = 3, Regen = 2 },
    },
    [21141] = {
        Avatar = { BloodPactDamage = 40 },
    },
    [21142] = {
        Avatar = { BloodPactDamage = 40 },
    },
    [21155] = {
        Avatar = { BloodPactDamage = 3, MagicAccuracy = 35, MagicAttackBonus = 110 },
    },
    [21167] = {
        Avatar = { Enmity = 10, MagicAccuracy = 20, MagicAttackBonus = 120 },
    },
    [21183] = {
        Avatar = { MagicAttackBonus = 108 },
    },
    [21361] = {
        All = { MagicAttackBonus = 6 },
    },
    [21372] = {
        Luopan = { DT = -5 },
    },
    [21430] = {
        All = { Accuracy = 10, MagicAccuracy = 10, RangedAccuracy = 10 },
    },
    [21432] = {
        Avatar = { BloodPactDamage = 16 },
    },
    [21433] = {
        Automaton = { MainDMGRating = 10 },
    },
    [21452] = {
        Automaton = { AGI = 89, CHR = 89, DEX = 89, INT = 89, MND = 89, STR = 89, VIT = 89 },
    },
    [21453] = {
        Automaton = { AGI = 77, CHR = 77, DEX = 77, INT = 77, MND = 77, STR = 77, VIT = 77 },
    },
    [21454] = {
        Automaton = { AGI = 46, CHR = 46, DEX = 46, INT = 46, MND = 46, STR = 46, VIT = 46 },
    },
    [21455] = {
        Automaton = { AGI = 70, CHR = 70, DEX = 70, INT = 70, MND = 70, STR = 70, VIT = 70 },
    },
    [21456] = {
        Automaton = { AGI = 104, CHR = 104, DEX = 104, INT = 104, MND = 104, STR = 104, VIT = 104 },
    },
    [21457] = {
        Automaton = { AGI = 109, CHR = 109, DEX = 109, INT = 109, MND = 109, STR = 109, VIT = 109 },
    },
    [21458] = {
        Automaton = { AGI = 104, CHR = 104, DEX = 104, INT = 104, MND = 104, STR = 104, VIT = 104 },
    },
    [21459] = {
        Automaton = { AGI = 109, CHR = 109, DEX = 109, INT = 109, MND = 109, STR = 109, VIT = 109 },
    },
    [21504] = {
        Automaton = { Accuracy = 10, MagicAccuracy = 10 },
    },
    [21505] = {
        Automaton = { Accuracy = 15, MagicAccuracy = 15 },
    },
    [21526] = {
        Automaton = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [21527] = {
        Automaton = { AGI = 20, Accuracy = 50, CHR = 20, DEX = 20, INT = 20, MND = 20, MagicAccuracy = 50, RangedAccuracy = 50, STR = 20, VIT = 20 },
    },
    [21528] = {
        All = { Accuracy = 40, MagicAccuracy = 40, RangedAccuracy = 40 },
    },
    [21529] = {
        All = { Accuracy = 40, MagicAccuracy = 40, RangedAccuracy = 40 },
    },
    [21704] = {
        All = { Accuracy = 10 },
    },
    [21705] = {
        All = { Accuracy = 15 },
    },
    [21715] = {
        All = { Accuracy = 30, MagicAccuracy = 30, RangedAccuracy = 30 },
    },
    [21716] = {
        All = { Accuracy = 40, MagicAccuracy = 40, RangedAccuracy = 40 },
    },
    [21717] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [21751] = {
        All = { Attack = 80 },
    },
    [21865] = {
        Wyvern = { Regen = 5 },
    },
    [21866] = {
        Wyvern = { Regen = 8 },
    },
    [22015] = {
        Avatar = { MagicAccuracy = 10 },
    },
    [22016] = {
        Avatar = { MagicAccuracy = 15 },
    },
    [22054] = {
        Avatar = { MagicAccuracy = 35, MagicAttackBonus = 115 },
    },
    [22063] = {
        Avatar = { BloodPactDamage = 40 },
    },
    [22074] = {
        Avatar = { BloodPactDamage = 3 },
    },
    [22075] = {
        Avatar = { BloodPactDamage = 5 },
    },
    [22096] = {
        Avatar = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [22210] = {
        Avatar = { BloodPactDamage = 3 },
    },
    [22211] = {
        Avatar = { BloodPactDamage = 5 },
    },
    [22260] = {
        Automaton = { AGI = 46, CHR = 46, DEX = 46, INT = 46, MND = 46, STR = 46, VIT = 46 },
    },
    [22261] = {
        Automaton = { AGI = 89, CHR = 89, DEX = 89, INT = 89, MND = 89, STR = 89, VIT = 89 },
    },
    [23048] = {
        All = { Accuracy = 30 },
    },
    [23057] = {
        Automaton = { Accuracy = 31, Haste = 6, Refresh = 1, Regen = 3 },
    },
    [23071] = {
        All = { Haste = 5 },
    },
    [23077] = {
        Avatar = { Attack = 47, MagicAttackBonus = 53 },
    },
    [23080] = {
        Automaton = { Accuracy = 27, Attack = 47, RangedAccuracy = 27, RangedAttack = 47, Refresh = 4, Regen = 4 },
    },
    [23083] = {
        Luopan = { HP = 500 },
    },
    [23093] = {
        All = { Accuracy = 51, MagicAccuracy = 51, MonsterCorrelation = 26, RangedAccuracy = 51 },
    },
    [23098] = {
        Wyvern = { AbsorbDamageChance = 16, Accuracy = 51, MagicAccuracy = 51 },
    },
    [23099] = {
        Avatar = { Accuracy = 51, MagicAccuracy = 51, RangedAccuracy = 51 },
    },
    [23102] = {
        Automaton = { Accuracy = 51, MagicAccuracy = 51, Pet_TPBonus = 575, RangedAccuracy = 51 },
    },
    [23105] = {
        Luopan = { Regen = 4 },
    },
    [23120] = {
        Wyvern = { Regen = 10 },
    },
    [23121] = {
        Avatar = { Accuracy = 35, BloodPactDamage = 14, MagicAccuracy = 35 },
    },
    [23124] = {
        Automaton = { HP = 165, Haste = 4, MP = 165 },
    },
    [23138] = {
        All = { DoubleAttack = 3, Haste = 6 },
    },
    [23144] = {
        Avatar = { CriticalHitRate = 16, DoubleAttack = 10 },
    },
    [23147] = {
        Automaton = { Accuracy = 40, Attack = 50, RangedAccuracy = 40, RangedAttack = 50, StoreTP = 14 },
    },
    [23160] = {
        All = { Accuracy = 54, MagicAccuracy = 54, RangedAccuracy = 54 },
    },
    [23165] = {
        Wyvern = { Accuracy = 54, MagicAccuracy = 54 },
    },
    [23166] = {
        Avatar = { Accuracy = 54, BloodPactDamage = 12, MagicAccuracy = 54, RangedAccuracy = 54 },
    },
    [23169] = {
        Automaton = { Accuracy = 54, MagicAccuracy = 54, RangedAccuracy = 54 },
    },
    [23191] = {
        Automaton = { Accuracy = 32, Haste = 5 },
    },
    [23195] = {
        Luopan = { DT = -12 },
    },
    [23205] = {
        All = { PDT = -5, RDT = -5 },
    },
    [23210] = {
        Wyvern = { MDT = -10 },
    },
    [23211] = {
        Avatar = { Accuracy = 42, Haste = 6 },
    },
    [23214] = {
        Automaton = { Haste = 6, SubtleBlow = 10 },
    },
    [23227] = {
        All = { Accuracy = 52, MagicAccuracy = 52, RangedAccuracy = 52 },
    },
    [23232] = {
        Wyvern = { Accuracy = 52, MagicAccuracy = 52 },
    },
    [23233] = {
        Avatar = { Accuracy = 52, BloodPactDamage = 8, MagicAccuracy = 52, RangedAccuracy = 52 },
    },
    [23236] = {
        Automaton = { Accuracy = 52, DEX = 21, MagicAccuracy = 52, RangedAccuracy = 52, STR = 21, VIT = 21 },
    },
    [23249] = {
        All = { Attack = 30 },
    },
    [23254] = {
        Wyvern = { HPP = 25 },
    },
    [23258] = {
        Automaton = { CurePotency = 14, DT = -3, Haste = 4, MP = 75 },
    },
    [23272] = {
        All = { Haste = 5, StoreTP = 4 },
    },
    [23277] = {
        Wyvern = { PDT = -10, RDT = -10 },
    },
    [23278] = {
        Avatar = { MagicAccuracy = 35, MagicAttackBonus = 44 },
    },
    [23281] = {
        Automaton = { FastCast = 9, MagicAccuracy = 38, MagicAttackBonus = 44 },
    },
    [23294] = {
        All = { Accuracy = 53, MagicAccuracy = 53, RangedAccuracy = 53 },
    },
    [23299] = {
        Wyvern = { Accuracy = 53, MagicAccuracy = 53 },
    },
    [23300] = {
        Avatar = { Accuracy = 53, MagicAccuracy = 53, RangedAccuracy = 53 },
    },
    [23303] = {
        Automaton = { Accuracy = 53, MagicAccuracy = 53, RangedAccuracy = 53 },
    },
    [23316] = {
        All = { Accuracy = 20, Attack = 20 },
    },
    [23322] = {
        Avatar = { Attack = 30, BloodPactDamage = 8, Evasion = 30, MagicAccuracy = 30 },
    },
    [23325] = {
        Automaton = { Haste = 4, MagicAccuracy = 40, MagicAttackBonus = 20 },
    },
    [23339] = {
        All = { Evasion = 28, PDT = -4, RDT = -4 },
    },
    [23344] = {
        Wyvern = { HP = 260, Regen = 7 },
    },
    [23345] = {
        Avatar = { Accuracy = 26, Attack = 74, MagicCriticalHitRate = 11 },
    },
    [23348] = {
        Automaton = { MagicAccuracy = 33, MagicAttackBonus = 50 },
    },
    [23351] = {
        Luopan = { Regen = 4 },
    },
    [23361] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23366] = {
        Wyvern = { Accuracy = 50, MagicAccuracy = 50 },
    },
    [23367] = {
        Avatar = { Accuracy = 50, BloodPactDamage = 8, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23370] = {
        Automaton = { Accuracy = 50, INT = 25, MND = 25, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23383] = {
        All = { Accuracy = 40 },
    },
    [23392] = {
        Automaton = { Accuracy = 41, Haste = 7, Refresh = 2, Regen = 6 },
    },
    [23418] = {
        Luopan = { HP = 600 },
    },
    [23455] = {
        Wyvern = { Regen = 15 },
    },
    [23456] = {
        Avatar = { Accuracy = 45, BloodPactDamage = 16, MagicAccuracy = 45 },
    },
    [23459] = {
        Automaton = { HP = 220, Haste = 5, MP = 220 },
    },
    [23526] = {
        Automaton = { Accuracy = 42, Haste = 5 },
    },
    [23530] = {
        Luopan = { DT = -13 },
    },
    [23584] = {
        All = { Attack = 40 },
    },
    [23589] = {
        Wyvern = { HPP = 27 },
    },
    [23593] = {
        Automaton = { CurePotency = 14, DT = -6, Haste = 6, MP = 75 },
    },
    [23660] = {
        Automaton = { Haste = 5, MagicAccuracy = 50, MagicAttackBonus = 25 },
    },
    [23674] = {
        All = { Evasion = 38, PDT = -5, RDT = -5 },
    },
    [23679] = {
        Wyvern = { HP = 290, Regen = 10 },
    },
    [23680] = {
        Avatar = { Accuracy = 36, Attack = 89, MagicCriticalHitRate = 13 },
    },
    [23683] = {
        Automaton = { MagicAccuracy = 43, MagicAttackBonus = 57 },
    },
    [23686] = {
        Luopan = { Regen = 5 },
    },
    [23756] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23758] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23760] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23761] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23763] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23765] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23767] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23768] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23770] = {
        All = { Accuracy = 50, DT = -8, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23772] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
        Automaton = { WeaponSkillDamage = 10 },
    },
    [23774] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23775] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23777] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23779] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23781] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23782] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23784] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23786] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23788] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [23789] = {
        All = { Accuracy = 50, MagicAccuracy = 50, RangedAccuracy = 50 },
    },
    [25465] = {
        All = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
    },
    [25466] = {
        All = { Accuracy = 20, MagicAccuracy = 20, RangedAccuracy = 20 },
    },
    [25467] = {
        All = { Accuracy = 25, MagicAccuracy = 25, RangedAccuracy = 25 },
    },
    [25501] = {
        Avatar = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
    },
    [25502] = {
        Avatar = { Accuracy = 20, MagicAccuracy = 20, RangedAccuracy = 20 },
    },
    [25503] = {
        Avatar = { Accuracy = 25, MagicAccuracy = 25, RangedAccuracy = 25 },
    },
    [25519] = {
        Automaton = { Accuracy = 15, MagicAccuracy = 15, RangedAccuracy = 15 },
    },
    [25520] = {
        Automaton = { Accuracy = 20, MagicAccuracy = 20, RangedAccuracy = 20 },
    },
    [25521] = {
        Automaton = { Accuracy = 25, MagicAccuracy = 25, RangedAccuracy = 25 },
    },
    [25563] = {
        All = { Accuracy = 40, Enmity = 8, Haste = 6, RangedAccuracy = 40 },
    },
    [25564] = {
        All = { Accuracy = 50, Enmity = 10, Haste = 6, RangedAccuracy = 50 },
    },
    [25565] = {
        Avatar = { Regain = 3 },
    },
    [25566] = {
        Avatar = { Regain = 4 },
    },
    [25593] = {
        Avatar = { Accuracy = 38, BloodPactDamage = 10, MagicAccuracy = 38, MagicAttackBonus = 38, RangedAccuracy = 38 },
    },
    [25683] = {
        All = { DT = -4, MagicAttackBonus = 35 },
    },
    [26026] = {
        All = { Accuracy = 20, Attack = 20, DoubleAttack = 5 },
    },
    [26082] = {
        Avatar = { Accuracy = 15, BloodPactDamage = 10, MagicAccuracy = 15, RangedAccuracy = 15 },
    },
    [26201] = {
        All = { Accuracy = 22, Attack = 23, DT = -4, Haste = 4, RangedAccuracy = 22, RangedAttack = 23 },
    },
    [26241] = {
        All = { Attack = 16, CriticalHitRate = 3, MagicAttackBonus = 16 },
    },
    [26260] = {
        Avatar = { BloodPactDamage = 5 },
    },
    [26640] = {
        All = { Haste = 3 },
    },
    [26641] = {
        All = { Haste = 4 },
    },
    [26652] = {
        Avatar = { MagicAttackBonus = 20 },
    },
    [26653] = {
        Avatar = { MagicAttackBonus = 23 },
    },
    [26658] = {
        Automaton = { Refresh = 2, Regen = 3 },
    },
    [26659] = {
        Automaton = { Refresh = 3, Regen = 3 },
    },
    [26677] = {
        Avatar = { Accuracy = 35, Enmity = 10, HP = 110 },
    },
    [26756] = {
        All = { MonsterCorrelation = 22 },
    },
    [26757] = {
        All = { MonsterCorrelation = 24 },
    },
    [26774] = {
        Automaton = { TPBonus = 525 },
    },
    [26775] = {
        Automaton = { TPBonus = 550 },
    },
    [26816] = {
        All = { Haste = 4 },
    },
    [26817] = {
        All = { Haste = 5 },
    },
    [26828] = {
        Avatar = { CriticalHitRate = 8 },
    },
    [26829] = {
        Avatar = { CriticalHitRate = 12 },
    },
    [26834] = {
        Automaton = { Accuracy = 18, RangedAccuracy = 18, StoreTP = 12 },
    },
    [26835] = {
        Automaton = { Accuracy = 21, RangedAccuracy = 21, StoreTP = 13 },
    },
    [26853] = {
        Avatar = { HP = 160 },
    },
    [26888] = {
        Avatar = { Enmity = 14 },
    },
    [26926] = {
        Avatar = { BloodPactDamage = 10 },
    },
    [26927] = {
        Avatar = { BloodPactDamage = 11 },
    },
    [26992] = {
        All = { PDT = -3, RDT = -3 },
    },
    [26993] = {
        All = { PDT = -4, RDT = -4 },
    },
    [27004] = {
        Avatar = { Accuracy = 20, Haste = 2 },
    },
    [27005] = {
        Avatar = { Accuracy = 28, Haste = 3 },
    },
    [27010] = {
        Automaton = { Haste = 4, SubtleBlow = 7 },
    },
    [27011] = {
        Automaton = { Haste = 5, SubtleBlow = 9 },
    },
    [27044] = {
        Wyvern = { HP = 50 },
    },
    [27080] = {
        Avatar = { Accuracy = 20 },
    },
    [27081] = {
        Avatar = { Accuracy = 30 },
    },
    [27086] = {
        Automaton = { AGI = 13, DEX = 13, STR = 13 },
    },
    [27087] = {
        Automaton = { AGI = 16, DEX = 16, STR = 16 },
    },
    [27106] = {
        Avatar = { MagicAttackBonus = 25 },
    },
    [27107] = {
        Avatar = { MagicAttackBonus = 26 },
    },
    [27108] = {
        Avatar = { MagicAttackBonus = 25 },
    },
    [27109] = {
        Avatar = { MagicAttackBonus = 26 },
    },
    [27168] = {
        All = { Haste = 3 },
    },
    [27169] = {
        All = { Haste = 4 },
    },
    [27180] = {
        Avatar = { MagicAccuracy = 10 },
    },
    [27181] = {
        Avatar = { MagicAccuracy = 13 },
    },
    [27186] = {
        Automaton = { FastCast = 7, MagicAccuracy = 15 },
    },
    [27187] = {
        Automaton = { FastCast = 8, MagicAccuracy = 18 },
    },
    [27221] = {
        Avatar = { BloodPactDamage = 7, Enmity = 4 },
    },
    [27265] = {
        Avatar = { TPBonus = 550 },
    },
    [27266] = {
        Avatar = { TPBonus = 600 },
    },
    [27299] = {
        All = { CriticalHitRate = 5, DoubleAttack = 5 },
        Wyvern = { HPP = 21 },
    },
    [27344] = {
        All = { Evasion = 15, PDT = -3, RDT = -3 },
    },
    [27345] = {
        All = { Evasion = 18, PDT = -3, RDT = -3 },
    },
    [27356] = {
        Avatar = { Attack = 28, MagicCriticalHitRate = 7 },
    },
    [27357] = {
        Avatar = { Attack = 28, MagicCriticalHitRate = 9 },
    },
    [27362] = {
        Automaton = { MagicAccuracy = 12, MagicAttackBonus = 15 },
    },
    [27363] = {
        Automaton = { MagicAccuracy = 15, MagicAttackBonus = 18 },
    },
    [27368] = {
        Luopan = { Regen = 2 },
    },
    [27369] = {
        Luopan = { Regen = 3 },
    },
    [27439] = {
        Avatar = { MagicAccuracy = 17 },
    },
    [27440] = {
        Avatar = { MagicAccuracy = 27 },
    },
    [27445] = {
        Automaton = { INT = 17, MND = 17 },
    },
    [27446] = {
        Automaton = { INT = 20, MND = 20 },
    },
    [27470] = {
        Wyvern = { AbsorbDamageChance = 6 },
    },
    [27671] = {
        All = { Accuracy = 20 },
    },
    [27677] = {
        Avatar = { Enmity = 4 },
    },
    [27680] = {
        Automaton = { HHP = 6, HMP = 6, Haste = 5 },
    },
    [27692] = {
        All = { Accuracy = 20 },
    },
    [27698] = {
        Avatar = { Enmity = 4 },
    },
    [27701] = {
        Automaton = { HHP = 8, HMP = 8, Haste = 5 },
    },
    [27820] = {
        Wyvern = { Regen = 2 },
    },
    [27821] = {
        Avatar = { BloodPactDamage = 11 },
    },
    [27824] = {
        Automaton = { HP = 85, Haste = 3, MP = 85 },
    },
    [27841] = {
        Wyvern = { Regen = 3 },
    },
    [27842] = {
        Avatar = { BloodPactDamage = 12 },
    },
    [27845] = {
        Automaton = { HP = 110, Haste = 3, MP = 110 },
    },
    [27951] = {
        All = { Haste = 3 },
    },
    [27957] = {
        Avatar = { Enmity = 5 },
    },
    [27960] = {
        Automaton = { Haste = 3 },
    },
    [27972] = {
        All = { Haste = 3 },
    },
    [27978] = {
        Avatar = { Enmity = 5 },
    },
    [27981] = {
        Automaton = { Haste = 4 },
    },
    [27985] = {
        Luopan = { DT = -11 },
    },
    [28025] = {
        All = { Accuracy = 20, Haste = 6, MagicAccuracy = 20, RangedAccuracy = 20 },
    },
    [28066] = {
        Luopan = { DT = -10 },
    },
    [28098] = {
        All = { Attack = 20 },
    },
    [28103] = {
        Wyvern = { HPP = 20 },
    },
    [28104] = {
        Avatar = { Accuracy = 20, Enmity = 4 },
    },
    [28107] = {
        Automaton = { CurePotency = 10, Haste = 3, MP = 40 },
    },
    [28119] = {
        All = { Attack = 20 },
    },
    [28124] = {
        Wyvern = { HPP = 23 },
    },
    [28125] = {
        Avatar = { Accuracy = 20, Enmity = 4 },
    },
    [28128] = {
        Automaton = { CurePotency = 12, Haste = 3, MP = 50 },
    },
    [28141] = {
        All = { Accuracy = 20, Attack = 10, Evasion = 20, Haste = 3, RangedAccuracy = 20, RangedAttack = 10 },
    },
    [28211] = {
        Avatar = { Attack = 15, Haste = 2 },
    },
    [28213] = {
        Wyvern = { Attack = 13 },
    },
    [28214] = {
        All = { Evasion = 5 },
    },
    [28219] = {
        All = { Evasion = 2 },
    },
    [28231] = {
        All = { Accuracy = 10, Attack = 10 },
    },
    [28237] = {
        Avatar = { BloodPactDamage = 5, Enmity = 5, Evasion = 20 },
    },
    [28240] = {
        Automaton = { Haste = 3 },
    },
    [28252] = {
        All = { Accuracy = 10, Attack = 10 },
    },
    [28258] = {
        Avatar = { BloodPactDamage = 6, Enmity = 5, Evasion = 20 },
    },
    [28261] = {
        Automaton = { Haste = 3 },
    },
    [28356] = {
        Avatar = { MagicAttackBonus = 5 },
    },
    [28418] = {
        All = { Accuracy = 15, DoubleAttack = 4, MagicAccuracy = 15, RangedAccuracy = 15 },
    },
    [28432] = {
        Automaton = { Accuracy = 15, FastCast = 5, Haste = 5, MagicAccuracy = 15, RangedAccuracy = 15 },
    },
    [28490] = {
        All = { PDT = -3, RDT = -3 },
    },
    [28491] = {
        All = { PDT = -4, RDT = -4 },
    },
    [28495] = {
        All = { DT = 1, Enmity = 5, Haste = 3 },
    },
    [28588] = {
        Automaton = { Accuracy = 15, Attack = 15, Evasion = 10 },
    },
    [28605] = {
        Avatar = { Accuracy = 7, MagicAccuracy = 7 },
    },
    [28643] = {
        Automaton = { INT = 8, MND = 8, MagicAccuracy = 3 },
    },
}
