--[[
    dlac/servers/vanaheim/manifest.lua -- the Vanaheim server pack (dlac ADR 0035).
    GENERATED by the vanaheim repo's tools/dlac-pack/gen_pack.py -- do not hand-edit;
    re-run the generator after a server data change and commit the pack to dlac.
]]--
return {
    fmt  = 1,
    id   = 'vanaheim',
    name = 'Vanaheim',

    maxLevel = 75,

    -- Vanaheim is stock-LSB-lineage: no game modes, no prestige, no 0x1A4
    -- protocol family, no venture economy -- those capabilities simply do
    -- not exist here, so the CEXI modules never mount and their gates stay
    -- shut by construction.
    caps = {
        wearMainJobOnly = true,   -- LSB equip eligibility: sub never widens
    },

    const = {
        augFormat          = 'lsb',   -- stock LSB augment extdata (not CEXI's private format)
        catalogMin         = 10267,
        mpPlayerMultiplier = 1,
        mpSjDivisor        = 2,
    },

    -- no pack modules yet
    modules = {},

    files = {
        'catalog', 'spells', 'abilities', 'zones',
        'gearsets', 'latentstats', 'levelscaling',
    },

    counts = {
        catalog      = 15401,
        spells       = 537,
        abilities    = 485,
        zones        = 300,
        gearsets     = 126,
        latentstats  = 856,
        levelscaling = 8,
    },
};
